import Link from "next/link";
import { ArrowLeft, ArrowRight, BookOpen, CheckCircle2, Compass, ExternalLink, Info, Lightbulb, Link2, Route, UserRound } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { PageContainer } from "@/components/shared/page-header";
import type { HelpArticle as HelpArticleType } from "@/lib/help/articles";

export default function HelpArticle({ article }: { article: HelpArticleType }) {
  const targetRoute = article.route.includes(":") ? article.route.split("/:")[0] : article.route;
  return <PageContainer className="pb-16">
    <nav aria-label="เส้นทางบทความ" className="flex flex-wrap items-center gap-2 text-sm text-slate-500"><Link href="/help" className="rounded-md py-2 font-semibold text-blue-700">Help Center</Link><span>/</span><span>{article.category}</span><span>/</span><span className="text-slate-800">{article.title}</span></nav>
    <header className="overflow-hidden rounded-2xl border border-blue-100 bg-gradient-to-br from-blue-50 via-white to-cyan-50 p-6 shadow-sm md:p-9"><div className="flex flex-wrap gap-2"><Badge className="bg-blue-800 text-white">{article.category}</Badge><Badge variant="outline" className="bg-white font-mono text-xs text-slate-600">{article.route}</Badge></div><div className="mt-5 grid gap-6 lg:grid-cols-[minmax(0,1fr)_18rem] lg:items-end"><div><p className="text-xs font-bold tracking-[.14em] text-blue-700">คู่มือประจำหน้า</p><h1 className="mt-2 text-3xl font-bold tracking-tight text-slate-950 md:text-4xl">{article.title}</h1><p className="mt-4 max-w-3xl text-base leading-7 text-slate-600">{article.summary}</p></div><div className="rounded-xl border border-blue-100 bg-white/80 p-4"><p className="flex items-center gap-2 text-xs font-bold text-slate-500"><UserRound className="size-4 text-blue-700" />เหมาะสำหรับ</p><p className="mt-2 text-sm font-semibold leading-6 text-slate-800">{article.audience}</p></div></div></header>
    <div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_18rem] lg:items-start"><article className="space-y-6">
      <Card><CardContent className="p-6 md:p-7"><section><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-lg bg-blue-50 text-blue-800"><Compass className="size-4" /></span><h2 className="text-xl font-bold">ความหมายและวัตถุประสงค์</h2></div><p className="mt-4 text-sm leading-7 text-slate-700">{article.purpose}</p></section></CardContent></Card>
      <Card><CardContent className="p-6 md:p-7"><section><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-lg bg-cyan-50 text-cyan-800"><Info className="size-4" /></span><h2 className="text-xl font-bold">คำสำคัญบนหน้านี้</h2></div><dl className="mt-5 divide-y divide-slate-100">{article.meanings.map((item) => <div key={item.term} className="grid gap-1 py-4 first:pt-0 last:pb-0 sm:grid-cols-[10rem_1fr] sm:gap-5"><dt className="font-bold">{item.term}</dt><dd className="text-sm leading-6 text-slate-600">{item.description}</dd></div>)}</dl></section></CardContent></Card>
      <Card><CardContent className="p-6 md:p-7"><section><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-lg bg-emerald-50 text-emerald-700"><Route className="size-4" /></span><h2 className="text-xl font-bold">ขั้นตอนการใช้งาน</h2></div><ol className="mt-6 space-y-5">{article.steps.map((step, index) => <li key={step} className="flex gap-4"><span className="grid size-8 shrink-0 place-items-center rounded-full bg-blue-800 text-sm font-bold text-white">{index + 1}</span><p className="pt-1 text-sm leading-6 text-slate-700">{step}</p></li>)}</ol></section></CardContent></Card>
      <Card><CardContent className="p-6 md:p-7"><section><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-lg bg-violet-50 text-violet-700"><Link2 className="size-4" /></span><h2 className="text-xl font-bold">เชื่อมกับหน้าอื่นอย่างไร</h2></div><div className="mt-5 grid gap-3">{article.connections.map((connection, index) => <Link key={`${connection.slug}-${index}`} href={`/help/${connection.slug}`} className="group flex min-h-16 items-center gap-4 rounded-xl border border-slate-200 p-4 hover:border-blue-300 hover:bg-blue-50/60"><span className="grid size-8 shrink-0 place-items-center rounded-full bg-slate-100 text-slate-500 group-hover:bg-blue-100 group-hover:text-blue-800"><ArrowRight className="size-4" /></span><span><strong className="block text-sm">{connection.label}</strong><span className="mt-1 block text-xs leading-5 text-slate-600">{connection.relation}</span></span></Link>)}</div></section></CardContent></Card>
    </article><aside className="space-y-4 lg:sticky lg:top-24"><Card className="border-amber-200 bg-amber-50"><CardContent className="p-5"><h2 className="flex items-center gap-2 text-sm font-bold text-amber-950"><Lightbulb className="size-4" />ข้อควรรู้</h2><ul className="mt-4 space-y-3">{article.tips.map((tip) => <li key={tip} className="flex gap-2 text-xs leading-5 text-amber-950/80"><CheckCircle2 className="mt-0.5 size-4 shrink-0 text-amber-700" />{tip}</li>)}</ul></CardContent></Card><Button asChild className="w-full justify-between"><Link href={targetRoute}>ไปยังหน้าระบบ<ExternalLink className="size-4" /></Link></Button><Button asChild variant="outline" className="w-full justify-start"><Link href="/help"><ArrowLeft className="size-4" />กลับไปบทความทั้งหมด</Link></Button><div className="rounded-xl border bg-white p-4"><p className="flex items-center gap-2 text-xs font-bold"><BookOpen className="size-4 text-blue-700" />ค้นหาไม่เจอ?</p><p className="mt-2 text-xs leading-5 text-slate-500">กลับไป Help Center แล้วค้นด้วยชื่อเมนู สถานะ หรือสิ่งที่ต้องการทำ</p></div></aside></div>
  </PageContainer>;
}
