"use client";

import * as DialogPrimitive from "@radix-ui/react-dialog";
import { TriangleAlert, X } from "lucide-react";
import { Button } from "@/components/ui/button";

export function ConfirmDialog({ open, onOpenChange, title, description, confirmLabel, destructive = true, pending, onConfirm }: { open: boolean; onOpenChange: (open: boolean) => void; title: string; description: string; confirmLabel: string; destructive?: boolean; pending?: boolean; onConfirm: () => void | Promise<void> }) {
  return <DialogPrimitive.Root open={open} onOpenChange={onOpenChange}><DialogPrimitive.Portal><DialogPrimitive.Overlay className="fixed inset-0 z-50 bg-slate-950/50" /><DialogPrimitive.Content className="fixed left-1/2 top-1/2 z-50 w-[min(30rem,calc(100vw-2rem))] -translate-x-1/2 -translate-y-1/2 rounded-xl border border-slate-200 bg-white p-6 text-slate-950 shadow-2xl"><div className="flex gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-full bg-amber-100 text-amber-800"><TriangleAlert className="size-5" /></span><div><DialogPrimitive.Title className="text-lg font-bold">{title}</DialogPrimitive.Title><DialogPrimitive.Description className="mt-2 text-sm leading-6 text-slate-600">{description}</DialogPrimitive.Description></div></div><div className="mt-6 flex flex-col-reverse gap-2 sm:flex-row sm:justify-end"><DialogPrimitive.Close asChild><Button variant="outline" disabled={pending}>Cancel</Button></DialogPrimitive.Close><Button variant={destructive ? "destructive" : "default"} disabled={pending} onClick={onConfirm}>{pending ? "Working…" : confirmLabel}</Button></div><DialogPrimitive.Close className="absolute right-3 top-3 grid size-9 place-items-center rounded-lg text-slate-500 hover:bg-slate-100" aria-label="Close confirmation"><X className="size-4" /></DialogPrimitive.Close></DialogPrimitive.Content></DialogPrimitive.Portal></DialogPrimitive.Root>;
}
