import { describe, expect, it } from "vitest";
import { completionRevisionSchema, managerCompletionDecisionSchema, operatorDecisionSchema } from "../../lib/maintenance/validation";
import { transitionNotification, transitionWorkOrder } from "../../lib/maintenance/workflow";
const actor = (id: string, permissions: string[]) => ({ id, permissions: permissions as never[] });

describe("E2E governed corrective maintenance flow", () => {
  it("requires technician revision, manager approval, operator acceptance, manager WO close, and operator Notification close", () => {
    const operator = actor("operator", ["NOTIFICATION_SUBMIT", "NOTIFICATION_ACCEPT_WORK", "NOTIFICATION_CLOSE"]); const manager = actor("manager", ["NOTIFICATION_REVIEW", "NOTIFICATION_APPROVE", "WORK_ORDER_CREATE", "WORK_ORDER_ASSIGN", "WORK_ORDER_REVIEW_COMPLETION", "WORK_ORDER_APPROVE_COMPLETION", "WORK_ORDER_CLOSE"]); const technician = actor("tech", ["WORK_ORDER_ACCEPT_ASSIGNMENT", "WORK_ORDER_START", "WORK_ORDER_SUBMIT_COMPLETION"]);
    let notification = transitionNotification("DRAFT", "SUBMIT", { actor: operator }); notification = transitionNotification(notification, "START_REVIEW", { actor: manager }); notification = transitionNotification(notification, "APPROVE", { actor: manager }); notification = transitionNotification(notification, "START_MAINTENANCE", { actor: manager });
    let order = transitionWorkOrder("CREATED", "ASSIGN", { actor: manager }); order = transitionWorkOrder(order, "ACCEPT_ASSIGNMENT", { actor: technician, assignedTo: "tech" }); order = transitionWorkOrder(order, "START", { actor: technician, assignedTo: "tech" });
    const revision = completionRevisionSchema.parse({ diagnosis: "Failed bearing", rootCause: "Lubrication loss", correctiveAction: "Replaced bearing", workSummary: "Pump restored", laborMinutes: 90, partsFinalized: true, testProcedure: "Run at rated load", testResult: "Passed", beforePhotoAttachmentIds: [], afterPhotoAttachmentIds: [] });
    order = transitionWorkOrder(order, "SUBMIT_COMPLETION", { actor: technician, assignedTo: "tech", requiredTasks: [] }); order = transitionWorkOrder(order, "BEGIN_MANAGER_REVIEW", { actor: manager }); expect(managerCompletionDecisionSchema.parse({ decision: "APPROVE", comment: "Evidence accepted" }).decision).toBe("APPROVE"); order = transitionWorkOrder(order, "APPROVE_COMPLETION", { actor: manager, completionExists: Boolean(revision), completionOwnerId: "tech" }); order = transitionWorkOrder(order, "REQUEST_OPERATOR_ACCEPTANCE", { actor: manager }); notification = transitionNotification(notification, "REQUEST_OPERATOR_ACCEPTANCE", { actor: manager });
    expect(operatorDecisionSchema.parse({ decision: "ACCEPT", comment: "Machine is stable" }).decision).toBe("ACCEPT"); order = transitionWorkOrder(order, "OPERATOR_ACCEPT", { actor: operator }); notification = transitionNotification(notification, "OPERATOR_ACCEPT", { actor: operator }); order = transitionWorkOrder(order, "CLOSE", { actor: manager, note: "Closed", operatorAcceptanceExists: true }); notification = transitionNotification(notification, "WORK_ORDERS_CLOSED", { actor: manager, allWorkOrdersClosed: true }); notification = transitionNotification(notification, "CLOSE", { actor: operator, note: "Final confirmation", allWorkOrdersClosed: true });
    expect({ order, notification }).toEqual({ order: "CLOSED", notification: "CLOSED" });
  });
});
