import Link from "next/link";
import { ArrowRight, Bell, Building2, Database, ShieldCheck, Wrench } from "lucide-react";
import { getCurrentSession } from "@/lib/auth/session";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";

const capabilities = [
  { title: "Maintenance operations", description: "Control work from asset notification through supervisor-verified closure.", icon: Wrench, href: "/maintenance" },
  { title: "Organization directory", description: "Structure organizations, sites, and departments for scoped operations.", icon: Building2, href: "/organization" },
  { title: "Configurable master data", description: "Manage controlled code lists without source-code changes.", icon: Database, href: "/settings/master-data" },
  { title: "Notification center", description: "Keep assigned operational actions and updates in one auditable inbox.", icon: Bell, href: "/notifications" },
];

export default async function LandingPage() { const session = await getCurrentSession(); return <main className="min-h-screen bg-slate-950 text-white"><nav className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5"><Link href="/" className="flex items-center gap-3 text-lg font-bold"><span className="grid size-10 place-items-center rounded-xl bg-blue-500">MA</span>MA Next</Link><Button asChild variant="outline" className="border-white/30 bg-transparent text-white hover:bg-white/10 hover:text-white"><Link href={session ? "/profile" : "/login"}>{session ? "Open workspace" : "Sign in"}<ArrowRight className="size-4" /></Link></Button></nav><section className="mx-auto grid max-w-7xl gap-12 px-5 py-16 lg:grid-cols-[1.15fr_.85fr] lg:py-24"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-blue-300">Maintenance management, rebuilt with control</p><h1 className="mt-5 max-w-3xl text-5xl font-bold leading-[1.05] tracking-[-.04em] md:text-7xl">Reliable maintenance starts with a trustworthy foundation.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-300">MA Next brings identity, permissions, organization structure, auditable configuration, notifications, and maintenance execution into one responsive application.</p><div className="mt-8 flex flex-wrap gap-3"><Button asChild size="lg" className="bg-blue-500 hover:bg-blue-400"><Link href={session ? "/maintenance" : "/login"}>{session ? "Go to maintenance" : "Sign in securely"}<ArrowRight className="size-4" /></Link></Button><span className="flex items-center gap-2 px-3 text-sm text-slate-300"><ShieldCheck className="size-5 text-emerald-400" />Server-side authorization and audit trails</span></div></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-1">{capabilities.map(({ title, description, icon: Icon, href }) => <Card key={title} className="border-white/10 bg-white/[.06] text-white shadow-none"><CardHeader><span className="mb-2 grid size-10 place-items-center rounded-xl bg-blue-500/20 text-blue-300"><Icon className="size-5" /></span><CardTitle className="text-white">{title}</CardTitle><CardDescription className="text-slate-300">{description}</CardDescription></CardHeader>{session && <CardContent><Link className="inline-flex items-center gap-2 text-sm font-bold text-blue-300 hover:text-blue-200" href={href}>Open capability<ArrowRight className="size-4" /></Link></CardContent>}</Card>)} </div></section></main>; }
