"use client";
import { useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { Wrench } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

export default function LoginPage() {
  const router = useRouter(); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setError(""); const data = new FormData(event.currentTarget); const response = await fetch("/api/auth/login", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ identifier: data.get("identifier"), password: data.get("password"), rememberMe: data.get("rememberMe") === "on" }) }); const body = await response.json(); setLoading(false); if (!response.ok) return setError(body.error || "ไม่สามารถเข้าสู่ระบบได้"); router.replace(body.redirectTo); router.refresh(); }
  return <main className="auth-page"><section className="auth-panel"><div className="auth-brand"><span className="ma-brand-mark">MA</span><span>Maintenance Management</span></div><div className="auth-copy"><p className="eyebrow">MAINTENANCE OPERATIONS</p><h1>Welcome back</h1><p>Sign in to manage assets, maintenance notifications, work orders, and verified completion.</p></div><form className="auth-form" onSubmit={submit}><label>Email or username<Input name="identifier" autoComplete="username" required autoFocus placeholder="you@company.com" /></label><label>Password<Input name="password" type="password" autoComplete="current-password" required placeholder="Enter your password" /></label><label className="check"><input name="rememberMe" type="checkbox" /> Remember me</label>{error && <p className="form-error" role="alert">{error}</p>}<Button type="submit" className="auth-submit" disabled={loading}>{loading ? "Signing in…" : "Sign in"}</Button></form><p className="auth-note">Accounts are created by your administrator. There is no public registration.</p></section><aside className="auth-visual" aria-label="Maintenance management system"><div><span>CONTROLLED MAINTENANCE FLOW</span><h2>Reliable maintenance from report to verified close.</h2><p>Keep asset history, work execution, approvals, and audit-ready decisions together in one trusted workspace.</p><Wrench aria-hidden="true" className="auth-visual-icon" /></div></aside></main>;
}
