import "dotenv/config";
import { createHash, randomUUID } from "node:crypto";
import { readFile } from "node:fs/promises";
import mysql, { type Pool, type PoolConnection, type RowDataPacket } from "mysql2/promise";
import { Prisma } from "../generated/prisma/client";
import { nextifInventoryMapping, type InventorySourceMapping } from "./nextif-inventory-mapping";

type Row = RowDataPacket & Record<string, unknown>;
type Summary = Record<string, { source: number; loaded: number; rejected: number }>;
type Rejection = { sourceTable: string; sourceId: string; reasonCode: string; reason: string; raw: unknown };

const execute = process.argv.includes("--execute");
const dryRun = !execute;
const sourceUrl = process.env.NEXTIF_SOURCE_DATABASE_URL ?? process.env.SOURCE_DATABASE_URL;
const targetUrl = process.env.TARGET_DATABASE_URL ?? process.env.DEV_DATABASE_URL ?? process.env.DATABASE_URL;
const migrationActorId = "00000000-0000-5000-8000-000000000099";
const batchSize = 250;

function text(value: unknown, fallback = "") { return value === null || value === undefined ? fallback : String(value).trim(); }
function nullable(value: unknown, max = 10000) { const result = text(value); return result ? result.slice(0, max) : null; }
function numeric(value: unknown, fallback = "0") { const result = text(value); return /^-?\d+(\.\d+)?$/.test(result) ? result : fallback; }
function bool(value: unknown) { return [true, 1, "1", "true", "TRUE", "active", "ACTIVE"].includes(value as never) ? 1 : 0; }
function stableId(namespace: string, value: unknown) { const bytes = createHash("sha256").update(`NEXTIF:inventory:${namespace}:${String(value)}`).digest().subarray(0, 16); bytes[6] = (bytes[6] & 0x0f) | 0x50; bytes[8] = (bytes[8] & 0x3f) | 0x80; const hex = bytes.toString("hex"); return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20)}`; }
function json(value: unknown) { return JSON.stringify(value, (_key, item) => item instanceof Date ? item.toISOString() : typeof item === "bigint" ? Number(item) : item); }
function identifier(value: string) { if (!/^[A-Za-z0-9_]+$/.test(value)) throw new Error(`Unsafe mapping identifier: ${value}`); return `\`${value}\``; }
function date(value: unknown) { const parsed = value instanceof Date ? value : new Date(text(value)); return Number.isNaN(parsed.getTime()) ? new Date() : parsed; }
function chunks<T>(values: T[]) { const result: T[][] = []; for (let index = 0; index < values.length; index += batchSize) result.push(values.slice(index, index + batchSize)); return result; }
function decimal(value: unknown, fallback = "0") { return new Prisma.Decimal(numeric(value, fallback)).toFixed(6); }
function amount(quantity: string, unitCost: string) { return new Prisma.Decimal(quantity).times(unitCost).toFixed(6); }
function historyMovements(entity: string, row: Row, sourceId: string, mapping: InventorySourceMapping, itemId: string, sourceLocationId: string | undefined, destinationLocationId: string | undefined, documentId: string, lineId: string, actorId: string) {
  const quantity = decimal(row[mapping.quantity]); const unitCost = decimal(row[mapping.unitCost]); const beforeCost = decimal(row[mapping.movingAverageCostBefore], unitCost); const afterCost = decimal(row[mapping.movingAverageCostAfter], unitCost); const explicitBefore = row[mapping.quantityBefore]; const explicitAfter = row[mapping.quantityAfter]; const before = decimal(explicitBefore); const afterIn = decimal(explicitAfter, new Prisma.Decimal(before).plus(quantity).toFixed(6)); const afterOut = decimal(explicitAfter, new Prisma.Decimal(before).minus(quantity).toFixed(6)); const postedAt = date(row[mapping.date]);
  const base = { document_id: documentId, document_number: nullable(row[mapping.number], 80) ?? "NEXTIF-" + entity.toUpperCase() + "-" + sourceId, line_id: lineId, stock_item_id: itemId, quantity_before: before, quantity_after: afterIn, quantity_in: "0", quantity_out: "0", unit_cost: unitCost, amount_in: "0", amount_out: "0", value_before: amount(before, beforeCost), value_after: amount(afterIn, afterCost), moving_average_cost_before: beforeCost, moving_average_cost_after: afterCost, vendor_id: null, work_order_id: null, stock_count_id: null, posted_by: actorId, posted_at: postedAt };
  if (entity === "receipts") return [{ ...base, id: stableId("history-movement-receipt", sourceId), movement_type: "RECEIPT", location_id: destinationLocationId, source_location_id: null, destination_location_id: destinationLocationId, quantity_in: quantity, amount_in: amount(quantity, unitCost), value_after: amount(afterIn, afterCost) }];
  if (entity === "issues") return [{ ...base, id: stableId("history-movement-issue", sourceId), movement_type: "ISSUE", location_id: sourceLocationId, source_location_id: sourceLocationId, destination_location_id: null, quantity_out: quantity, amount_out: amount(quantity, unitCost), quantity_after: afterOut, value_after: amount(afterOut, afterCost) }];
  const sourceBefore = decimal(row[mapping.sourceQuantityBefore], before); const sourceAfter = decimal(row[mapping.sourceQuantityAfter], new Prisma.Decimal(sourceBefore).minus(quantity).toFixed(6)); const destinationBefore = decimal(row[mapping.destinationQuantityBefore], before); const destinationAfter = decimal(row[mapping.destinationQuantityAfter], new Prisma.Decimal(destinationBefore).plus(quantity).toFixed(6));
  return [{ ...base, id: stableId("history-movement-transfer-out", sourceId + ":out"), movement_type: "TRANSFER_OUT", location_id: sourceLocationId, source_location_id: sourceLocationId, destination_location_id: destinationLocationId, quantity_before: sourceBefore, quantity_after: sourceAfter, quantity_out: quantity, amount_out: amount(quantity, unitCost), value_before: amount(sourceBefore, beforeCost), value_after: amount(sourceAfter, afterCost) }, { ...base, id: stableId("history-movement-transfer-in", sourceId + ":in"), movement_type: "TRANSFER_IN", location_id: destinationLocationId, source_location_id: sourceLocationId, destination_location_id: destinationLocationId, quantity_before: destinationBefore, quantity_after: destinationAfter, quantity_in: quantity, amount_in: amount(quantity, unitCost), value_before: amount(destinationBefore, beforeCost), value_after: amount(destinationAfter, afterCost) }];
}

async function applyMappingFile(mapping: Record<string, InventorySourceMapping>) {
  const mappingPath = process.env.NEXTIF_INVENTORY_MAPPING_FILE;
  if (!mappingPath) return mapping;
  return { ...mapping, ...JSON.parse(await readFile(mappingPath, "utf8")) } as Record<string, InventorySourceMapping>;
}

async function rows(connection: Pool | PoolConnection, mapping: InventorySourceMapping) {
  const [tables] = await connection.query<Row[]>("SHOW TABLES LIKE ?", [mapping.table]);
  if (!tables.length) return null;
  const [result] = await connection.query<Row[]>(`SELECT * FROM ${identifier(mapping.table)}`);
  return result;
}

async function ensureFoundation(connection: PoolConnection) {
  await connection.query(`CREATE TABLE IF NOT EXISTS migration_runs (id VARCHAR(36) NOT NULL PRIMARY KEY, source_system VARCHAR(80) NOT NULL, source_database VARCHAR(80) NOT NULL, scope VARCHAR(190) NOT NULL, status VARCHAR(40) NOT NULL, started_at DATETIME NOT NULL, finished_at DATETIME NULL, manifest LONGTEXT NULL, summary LONGTEXT NULL, INDEX migration_runs_source_idx (source_system, started_at)) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`);
  await connection.query(`CREATE TABLE IF NOT EXISTS migration_rejections (id VARCHAR(36) NOT NULL PRIMARY KEY, migration_run_id VARCHAR(36) NOT NULL, source_table VARCHAR(80) NOT NULL, source_id VARCHAR(80) NOT NULL, reason_code VARCHAR(80) NOT NULL, reason TEXT NOT NULL, raw_data LONGTEXT NULL, created_at DATETIME NOT NULL, UNIQUE INDEX migration_rejections_record_uq (migration_run_id, source_table, source_id, reason_code), INDEX migration_rejections_reason_idx (reason_code), CONSTRAINT migration_rejections_run_fk FOREIGN KEY (migration_run_id) REFERENCES migration_runs (id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`);
}

async function upsert(connection: PoolConnection, table: string, record: Record<string, unknown>) {
  const columns = Object.keys(record); const quoted = columns.map(identifier).join(","); const updates = columns.filter((column) => column !== "id").map((column) => `${identifier(column)}=VALUES(${identifier(column)})`).join(",");
  await connection.query(`INSERT INTO ${identifier(table)} (${quoted}) VALUES (${columns.map(() => "?").join(",")}) ON DUPLICATE KEY UPDATE ${updates}`, columns.map((column) => record[column] ?? null));
}

async function main() {
  if (process.argv.includes("--help")) { console.log("npm run migrate:nextif-inventory -- --dry-run|--execute"); console.log("NEXTIF_SOURCE_DATABASE_URL and NEXTIF_INVENTORY_MAPPING_FILE are optional overrides."); return; }
  if (!sourceUrl) throw new Error("NEXTIF_SOURCE_DATABASE_URL or SOURCE_DATABASE_URL is required");
  if (!targetUrl) throw new Error("TARGET_DATABASE_URL, DEV_DATABASE_URL or DATABASE_URL is required");
  if (sourceUrl === targetUrl) throw new Error("Source and target databases must be different");
  const source = mysql.createPool({ uri: sourceUrl, connectionLimit: 4, timezone: "Z" }); const target = mysql.createPool({ uri: targetUrl, connectionLimit: 4, timezone: "Z" }); const targetConnection = execute ? await target.getConnection() : null;
  const mapping = await applyMappingFile(nextifInventoryMapping); const runId = randomUUID(); const summary: Summary = {}; const rejections: Rejection[] = []; const maps = { items: new Map<string, string>(), locations: new Map<string, string>(), vendors: new Map<string, string>() };
  const count = (name: string, sourceCount: number) => summary[name] = { source: sourceCount, loaded: 0, rejected: 0 };
  const reject = (name: string, row: Row, reasonCode: string, reason: string) => { summary[name].rejected += 1; rejections.push({ sourceTable: mapping[name].table, sourceId: text(row[mapping[name].id]), reasonCode, reason, raw: row }); };
  try {
    if (targetConnection) { await ensureFoundation(targetConnection); await targetConnection.query("INSERT INTO migration_runs (id, source_system, source_database, scope, status, started_at, manifest) VALUES (?, 'NEXTIF', DATABASE(), 'inventory', 'RUNNING', NOW(), ?)", [runId, json(mapping)]); }
    for (const entity of ["stockItems", "locations", "vendors", "vendorContacts", "balances", "receipts", "issues", "transfers"]) {
      const sourceRows = await rows(source, mapping[entity]); if (sourceRows === null) { count(entity, 0); console.warn(`[${entity}] source table ${mapping[entity].table} not found; skipped`); continue; } count(entity, sourceRows.length);
      if (entity === "stockItems") for (const row of sourceRows) { const sourceId = text(row[mapping[entity].id]); const rawCode = nullable(row[mapping[entity].code], 80); const code = rawCode || `NEXTIF-${sourceId}`; const name = nullable(row[mapping[entity].name], 190); if (!sourceId || !name) { reject(entity, row, "REQUIRED_FIELD", "Stock item id and name are required"); continue; } const id = stableId("stock-item", sourceId); maps.items.set(sourceId, id); if (targetConnection) await upsert(targetConnection, "stock_items", { id, code: code.slice(0, 80), name, description: nullable(row[mapping[entity].description]), category: nullable(row[mapping[entity].category], 120), unit: (nullable(row[mapping[entity].unit], 45) ?? "EA"), manufacturer: nullable(row[mapping[entity].manufacturer], 160), part_number: nullable(row[mapping[entity].partNumber], 120), barcode: nullable(row[mapping[entity].barcode], 160), minimum_stock: numeric(row[mapping[entity].minimumStock]), maximum_stock: nullable(row[mapping[entity].maximumStock]), reorder_point: nullable(row[mapping[entity].reorderPoint]), default_unit_cost: numeric(row[mapping[entity].defaultUnitCost]), moving_average_cost: numeric(row[mapping[entity].defaultUnitCost]), active: bool(row[mapping[entity].active]), legacy_source_id: Number(sourceId) || null, created_at: new Date(), updated_at: new Date(), created_by: migrationActorId, updated_by: migrationActorId }); summary[entity].loaded += 1; }
      if (entity === "locations") for (const row of sourceRows) { const sourceId = text(row[mapping[entity].id]); const code = nullable(row[mapping[entity].code], 80) ?? `NEXTIF-LOC-${sourceId}`; const name = nullable(row[mapping[entity].name], 190); if (!sourceId || !name) { reject(entity, row, "REQUIRED_FIELD", "Location id and name are required"); continue; } const id = stableId("location", sourceId); maps.locations.set(sourceId, id); if (targetConnection) await upsert(targetConnection, "inventory_locations", { id, code, name, plant: nullable(row[mapping[entity].plant], 120), warehouse: nullable(row[mapping[entity].warehouse], 120), zone: nullable(row[mapping[entity].zone], 120), rack: nullable(row[mapping[entity].rack], 120), shelf: nullable(row[mapping[entity].shelf], 120), bin: nullable(row[mapping[entity].bin], 120), description: nullable(row[mapping[entity].description]), active: bool(row[mapping[entity].active]), legacy_source_id: Number(sourceId) || null, created_at: new Date(), updated_at: new Date(), created_by: migrationActorId, updated_by: migrationActorId }); summary[entity].loaded += 1; }
      if (entity === "vendors") for (const row of sourceRows) { const sourceId = text(row[mapping[entity].id]); const code = nullable(row[mapping[entity].code], 80) ?? `NEXTIF-VND-${sourceId}`; const name = nullable(row[mapping[entity].name], 190); if (!sourceId || !name) { reject(entity, row, "REQUIRED_FIELD", "Vendor id and name are required"); continue; } const id = stableId("vendor", sourceId); maps.vendors.set(sourceId, id); if (targetConnection) await upsert(targetConnection, "vendors", { id, code, name, tax_id: nullable(row[mapping[entity].taxId], 80), address: nullable(row[mapping[entity].address]), country: nullable(row[mapping[entity].country], 100), province: nullable(row[mapping[entity].province], 120), phone: nullable(row[mapping[entity].phone], 80), email: nullable(row[mapping[entity].email], 190), website: nullable(row[mapping[entity].website], 255), active: bool(row[mapping[entity].active]), created_at: new Date(), updated_at: new Date(), created_by: migrationActorId, updated_by: migrationActorId }); summary[entity].loaded += 1; }
      if (entity === "vendorContacts") for (const row of sourceRows) { const sourceId = text(row[mapping[entity].id]); const vendorId = maps.vendors.get(text(row[mapping[entity].vendorId])); const name = nullable(row[mapping[entity].name], 160); if (!sourceId || !vendorId || !name) { reject(entity, row, "MISSING_VENDOR", "Contact requires a mapped vendor and name"); continue; } if (targetConnection) await upsert(targetConnection, "vendor_contacts", { id: stableId("vendor-contact", sourceId), vendor_id: vendorId, name, position: nullable(row[mapping[entity].position], 120), department: nullable(row[mapping[entity].department], 120), phone: nullable(row[mapping[entity].phone], 80), mobile: nullable(row[mapping[entity].mobile], 80), email: nullable(row[mapping[entity].email], 190), line_id: nullable(row[mapping[entity].lineId], 80), primary_contact: bool(row[mapping[entity].primaryContact]), active: bool(row[mapping[entity].active]), created_at: new Date(), updated_at: new Date() }); summary[entity].loaded += 1; }
      if (entity === "balances") for (const row of sourceRows) { const sourceId = text(row[mapping[entity].id]); const itemId = maps.items.get(text(row[mapping[entity].stockItemId])); const locationId = maps.locations.get(text(row[mapping[entity].locationId])); const quantity = numeric(row[mapping[entity].quantity]); if (!sourceId || !itemId || !locationId) { reject(entity, row, "MISSING_REFERENCE", "Balance requires mapped stock item and location"); continue; } if (targetConnection) { await upsert(targetConnection, "stock_item_locations", { id: stableId("item-location", `${itemId}:${locationId}`), stock_item_id: itemId, location_id: locationId, created_at: new Date() }); await upsert(targetConnection, "inventory_balances", { id: stableId("balance", `${itemId}:${locationId}`), stock_item_id: itemId, location_id: locationId, quantity_on_hand: quantity, reserved_quantity: "0", moving_average_cost: numeric(row[mapping[entity].movingAverageCost]), last_movement_date: new Date(), created_at: new Date(), updated_at: new Date() }); await upsert(targetConnection, "inventory_movements", { id: stableId("opening-movement", sourceId), movement_type: "RECEIPT", document_id: null, document_number: `NEXTIF-OPENING-${sourceId}`.slice(0, 80), line_id: null, stock_item_id: itemId, location_id: locationId, source_location_id: null, destination_location_id: locationId, quantity_in: quantity, quantity_out: "0", quantity_before: "0", quantity_after: quantity, unit_cost: numeric(row[mapping[entity].movingAverageCost]), amount_in: `0`, amount_out: "0", value_before: "0", value_after: "0", moving_average_cost_before: numeric(row[mapping[entity].movingAverageCost]), moving_average_cost_after: numeric(row[mapping[entity].movingAverageCost]), vendor_id: null, work_order_id: null, stock_count_id: null, posted_by: migrationActorId, posted_at: new Date() }); } summary[entity].loaded += 1; }
      if (["receipts", "issues", "transfers"].includes(entity)) for (const row of sourceRows) { const sourceId = text(row[mapping[entity].id]); const itemId = maps.items.get(text(row[mapping[entity].itemId])); const sourceLocationId = maps.locations.get(text(row[mapping[entity].sourceLocationId] ?? row[mapping[entity].locationId])); const destinationLocationId = maps.locations.get(text(row[mapping[entity].destinationLocationId] ?? row[mapping[entity].locationId])); const quantity = numeric(row[mapping[entity].quantity]); if (!sourceId || !itemId || !quantity || (entity === "transfers" && (!sourceLocationId || !destinationLocationId))) { reject(entity, row, "INVALID_HISTORY", "History row is missing a mapped item, location or positive quantity"); continue; } const documentId = stableId(`history-${entity}`, sourceId); const documentType = entity === "receipts" ? "RECEIPT" : entity === "issues" ? "ISSUE" : "TRANSFER"; const number = (nullable(row[mapping[entity].number], 80) ?? `NEXTIF-${entity.toUpperCase()}-${sourceId}`).slice(0, 80); if (targetConnection) { await upsert(targetConnection, "inventory_documents", { id: documentId, document_type: documentType, document_number: number, document_date: date(row[mapping[entity].date]), site_id: null, requester_id: migrationActorId, department_id: null, purpose: `Imported Nextif ${entity} history`, reference_work_order_id: null, reference_notification_id: null, status: "POSTED", current_approval_step: null, remark: "Imported historical record", submitted_at: date(row[mapping[entity].date]), posted_at: date(row[mapping[entity].date]), posted_by: migrationActorId, posting_transaction_id: stableId("posting", sourceId), created_at: date(row[mapping[entity].date]), updated_at: new Date(), created_by: migrationActorId, updated_by: migrationActorId }); const lineId = stableId(`history-line-${entity}`, sourceId); await upsert(targetConnection, "inventory_document_lines", { id: lineId, document_id: documentId, line_number: 1, stock_item_id: itemId, source_location_id: entity === "receipts" ? null : sourceLocationId, destination_location_id: entity === "issues" ? null : destinationLocationId, requested_quantity: quantity, approved_quantity: quantity, rejected_quantity: "0", unit: "EA", unit_cost: numeric(row[mapping[entity].unitCost]), total_amount: "0", vendor_id: maps.vendors.get(text(row[mapping[entity].vendorId])) ?? null, purchase_order_reference: null, expected_delivery_date: nullable(row[mapping[entity].expectedDate]), actual_delivery_date: nullable(row[mapping[entity].actualDate]), work_order_id: null, job_step_id: null, remark: "Imported history" }); for (const movement of historyMovements(entity, row, sourceId, mapping[entity], itemId, sourceLocationId, destinationLocationId, documentId, lineId, migrationActorId)) await upsert(targetConnection, "inventory_movements", movement); } summary[entity].loaded += 1; }
    }
    if (targetConnection) { for (const batch of chunks(rejections)) for (const rejection of batch) await upsert(targetConnection, "migration_rejections", { id: stableId("rejection", `${runId}:${rejection.sourceTable}:${rejection.sourceId}:${rejection.reasonCode}`), migration_run_id: runId, source_table: rejection.sourceTable, source_id: rejection.sourceId, reason_code: rejection.reasonCode, reason: rejection.reason, raw_data: json(rejection.raw), created_at: new Date() }); await targetConnection.query("UPDATE migration_runs SET status=?, finished_at=NOW(), summary=? WHERE id=?", [rejections.length ? "COMPLETED_WITH_REJECTIONS" : "COMPLETED", json(summary), runId]); }
    console.log(JSON.stringify({ mode: dryRun ? "dry-run" : "execute", summary, rejected: rejections.length }, null, 2));
  } catch (error) { if (targetConnection) await targetConnection.query("UPDATE migration_runs SET status=?, finished_at=NOW(), summary=? WHERE id=?", ["FAILED", json({ error: error instanceof Error ? error.message : String(error), summary }), runId]).catch(() => undefined); throw error; }
  finally { await source.end(); await targetConnection?.release(); await target.end(); }
}

main().catch((error) => { console.error(error instanceof Error ? error.message : "Nextif inventory migration failed"); process.exit(1); });
