"use client";

import { useCallback, useEffect, useMemo, useState, type FormEvent } from "react";
import { AlertTriangle, ArrowUpDown, CheckCircle2, ChevronLeft, ChevronRight, Clock3, ClipboardList, Eye, ImagePlus, Loader2, RefreshCw, Search, UserRoundCog, Wrench } from "lucide-react";
import { Alert } from "@/components/ui/alert";
import { AssetCombobox } from "@/components/shared/asset-combobox";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { PageContainer, PageHeader } from "@/components/shared/page-header";
import { cn } from "@/lib/utils";

type Permission = string;
type CurrentUser = { id: string; fullName: string; role: string; permissions: Permission[] };
type NotificationRow = { id: string; code: string; assetId: string; title: string; description: string; symptoms?: string | null; problemCategory?: string | null; operationalImpact?: string | null; safetyImpact?: string | null; productionImpact?: string | null; incidentAt?: string | null; responsibleGroup?: string | null; remarks?: string | null; contactPerson?: string | null; contactPhone?: string | null; type?: string; status: string; priority: string; requestedBy: string; departmentId: string | null; photoAttachmentIds?: string | null; dueAt: string | null; createdAt?: string; submittedAt?: string | null; informationRequest?: string | null; rejectionReason?: string | null; updatedAt: string };
type WorkOrderRow = { id: string; code: string; notificationId: string | null; title: string; status: string; priority: string; assignedTo: string | null; dueAt: string | null; updatedAt: string };
type Queue = { notifications: NotificationRow[]; workOrders: WorkOrderRow[]; technicians: Array<{ id: string; fullName: string }>; assets: Array<{ id: string; code: string; name: string; location: string }> };
type NotificationSort = "code" | "title" | "asset" | "priority" | "status" | "updatedAt";

const responsibility: Record<string, [string, string]> = {
  DRAFT: ["Operator", "กรอกข้อมูลและส่งใบแจ้ง"], SUBMITTED: ["Maintenance Manager", "เริ่มตรวจสอบ"], UNDER_REVIEW: ["Maintenance Manager", "อนุมัติ ปฏิเสธ หรือส่งกลับแก้ไข"], RETURNED: ["Operator", "แก้ไขและส่งใหม่"], NEEDS_INFORMATION: ["Operator", "ให้ข้อมูลเพิ่มเติม"], APPROVED: ["Maintenance Manager", "สร้างและมอบหมาย Work Order"], CONVERTED_TO_WORK_ORDER: ["Maintenance", "ดำเนินงานซ่อม"], IN_MAINTENANCE: ["Maintenance", "ดำเนินงานซ่อม"], WAITING_FOR_OPERATOR_ACCEPTANCE: ["Operator", "ยอมรับงานหรือขอตรวจซ้ำ"], OPERATOR_REJECTED: ["Maintenance Manager", "ส่งกลับให้ช่างตรวจซ้ำ"], READY_TO_CLOSE: ["Operator", "ปิดใบแจ้ง"],
  CREATED: ["Maintenance Manager", "มอบหมายช่าง"], ASSIGNED: ["Technician", "รับมอบหมาย"], TECHNICIAN_ACCEPTED: ["Technician", "เริ่มงาน"], IN_PROGRESS: ["Technician", "ดำเนินงานและส่งผล"], WAITING_FOR_PARTS: ["Technician", "ดำเนินงานต่อเมื่ออะไหล่พร้อม"], WAITING_FOR_VENDOR: ["Technician", "ดำเนินงานต่อเมื่อผู้รับเหมาพร้อม"], WAITING_FOR_ACCESS: ["Technician", "ดำเนินงานต่อเมื่อเข้าพื้นที่ได้"], ON_HOLD: ["Technician", "แก้เหตุพักงานและดำเนินงานต่อ"], TECHNICIAN_COMPLETED: ["Maintenance Manager", "ตรวจผลการซ่อม"], UNDER_MANAGER_REVIEW: ["Maintenance Manager", "อนุมัติหรือส่งตรวจซ้ำ"], RETURNED_TO_TECHNICIAN: ["Technician", "ตรวจซ้ำและส่ง revision ใหม่"], MANAGER_APPROVED: ["Maintenance Manager", "ขอ Operator ยอมรับงาน"], OPERATOR_ACCEPTED: ["Maintenance Manager", "ปิด Work Order"], CLOSED: ["—", "ปิดแล้ว"], CANCELLED: ["—", "ยกเลิกแล้ว"],
};
const statusTone = (status: string) => status === "CLOSED" || status === "OPERATOR_ACCEPTED" ? "border-emerald-200 bg-emerald-50 text-emerald-800" : status.includes("REJECT") || status.includes("RETURN") ? "border-red-200 bg-red-50 text-red-800" : status.includes("WAIT") || status === "ON_HOLD" ? "border-amber-200 bg-amber-50 text-amber-900" : "border-blue-200 bg-blue-50 text-blue-800";
const label = (value: string) => value.replaceAll("_", " ").toLowerCase().replace(/(^|\s)\S/g, (letter) => letter.toUpperCase());
const age = (value: string) => { const hours = Math.max(0, Math.floor((Date.now() - new Date(value).getTime()) / 3_600_000)); return hours < 24 ? `${hours} ชม.` : `${Math.floor(hours / 24)} วัน`; };
const attachmentIds = (value?: string | null) => { try { const parsed = JSON.parse(value || "[]"); return Array.isArray(parsed) ? parsed.filter((id): id is string => typeof id === "string") : []; } catch { return []; } };

async function jsonRequest(url: string, init?: RequestInit) { const response = await fetch(url, init); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error || "ไม่สามารถดำเนินการได้"); return body; }

async function uploadNotificationPhotos(files: File[]) {
  const draftId = crypto.randomUUID();
  return Promise.all(files.map(async (file) => {
    const form = new FormData(); form.set("file", file); form.set("entityType", "MAINTENANCE_NOTIFICATION_DRAFT"); form.set("entityId", draftId);
    const body = await jsonRequest("/api/attachments/upload", { method: "POST", body: form });
    return body.attachment.id as string;
  }));
}

export default function GovernedWorkflowWorkspace({ notificationOnly = false }: { notificationOnly?: boolean }) {
  const [queue, setQueue] = useState<Queue>({ notifications: [], workOrders: [], technicians: [], assets: [] }); const [user, setUser] = useState<CurrentUser | null>(null); const [tab, setTab] = useState<"notifications" | "work-orders">("notifications"); const [showCreate, setShowCreate] = useState(false); const [busy, setBusy] = useState(true); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const [notificationSearch, setNotificationSearch] = useState(""); const [notificationStatus, setNotificationStatus] = useState(""); const [notificationPriority, setNotificationPriority] = useState(""); const [notificationSort, setNotificationSort] = useState<NotificationSort>("updatedAt"); const [sortDirection, setSortDirection] = useState<"asc" | "desc">("desc"); const [notificationPage, setNotificationPage] = useState(1); const [notificationPageSize, setNotificationPageSize] = useState(10); const [selectedNotification, setSelectedNotification] = useState<NotificationRow | null>(null);
  const load = useCallback(async () => { setBusy(true); try { const [next, me] = await Promise.all([jsonRequest("/api/maintenance/workflow/queue"), jsonRequest("/api/auth/me")]); setQueue(next); setUser(me.user); setError(""); } catch (cause) { setError(cause instanceof Error ? cause.message : "โหลดคิวงานไม่สำเร็จ"); } finally { setBusy(false); } }, []);
  useEffect(() => { let active = true; Promise.all([jsonRequest("/api/maintenance/workflow/queue"), jsonRequest("/api/auth/me")]).then(([next, me]) => { if (active) { setQueue(next); setUser(me.user); setError(""); setBusy(false); } }).catch((cause) => { if (active) { setError(cause instanceof Error ? cause.message : "โหลดคิวงานไม่สำเร็จ"); setBusy(false); } }); return () => { active = false; }; }, []);
  const permitted = (permission: string) => Boolean(user?.permissions.includes(permission));
  async function command(url: string, payload: unknown, success: string) { setError(""); setMessage(""); try { await jsonRequest(url, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); setMessage(success); window.dispatchEvent(new Event("approval-count-changed")); await load(); return true; } catch (cause) { setError(cause instanceof Error ? cause.message : "ดำเนินการไม่สำเร็จ"); return false; } }
  async function editNotification(item: NotificationRow) { const title = window.prompt("แก้ไขหัวข้อ", item.title)?.trim(); if (!title) return; const description = window.prompt("แก้ไขรายละเอียดปัญหา", item.description)?.trim(); if (!description) return; setError(""); try { await jsonRequest(`/api/maintenance/workflow/notifications/${item.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ title, description }) }); setMessage("บันทึกการแก้ไขแล้ว"); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "บันทึกการแก้ไขไม่สำเร็จ"); } }
  async function createNotification(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const incidentAt = String(data.get("incidentAt") ?? ""); const photos = data.getAll("photos").filter((item): item is File => item instanceof File && item.size > 0); setError(""); setMessage(""); if (photos.length > 10) { setError("แนบรูปได้สูงสุด 10 รูปต่อใบแจ้ง"); return false; } if (photos.some((file) => file.size > 5 * 1024 * 1024)) { setError("แต่ละรูปต้องมีขนาดไม่เกิน 5 MB"); return false; } try { const photoAttachmentIds = await uploadNotificationPhotos(photos); const created = await command("/api/maintenance/workflow/notifications", { assetId: data.get("assetId"), title: data.get("title"), description: data.get("description"), symptoms: data.get("symptoms"), problemCategory: data.get("problemCategory"), operationalImpact: data.get("operationalImpact"), safetyImpact: data.get("safetyImpact"), productionImpact: data.get("productionImpact"), incidentAt: incidentAt ? new Date(incidentAt).toISOString() : null, responsibleGroup: data.get("responsibleGroup"), remarks: data.get("remarks"), requestedUrgency: data.get("requestedUrgency"), contactPerson: data.get("contactPerson"), contactPhone: data.get("contactPhone"), type: data.get("type"), priority: data.get("priority"), severity: "MODERATE", equipmentOperatingStatus: "UNKNOWN", breakdown: data.get("type") === "BREAKDOWN", photoAttachmentIds }, photoAttachmentIds.length ? `บันทึกร่างใบแจ้งพร้อมรูป ${photoAttachmentIds.length} รูปแล้ว` : "บันทึกร่างใบแจ้งแล้ว"); if (created) setShowCreate(false); return created; } catch (cause) { setError(cause instanceof Error ? cause.message : "อัปโหลดรูปไม่สำเร็จ"); return false; } }
  const counts = useMemo(() => ({ mine: queue.workOrders.filter((item) => item.assignedTo === user?.id && !["CLOSED", "CANCELLED"].includes(item.status)).length, review: queue.workOrders.filter((item) => ["TECHNICIAN_COMPLETED", "UNDER_MANAGER_REVIEW"].includes(item.status)).length, acceptance: queue.workOrders.filter((item) => item.status === "WAITING_FOR_OPERATOR_ACCEPTANCE").length, overdue: [...queue.notifications, ...queue.workOrders].filter((item) => item.dueAt && new Date(item.dueAt) < new Date() && !["CLOSED", "CANCELLED"].includes(item.status)).length, drafts: queue.notifications.filter((item) => item.status === "DRAFT").length, pendingNotifications: queue.notifications.filter((item) => ["SUBMITTED", "UNDER_REVIEW"].includes(item.status)).length, returnedNotifications: queue.notifications.filter((item) => ["RETURNED", "NEEDS_INFORMATION"].includes(item.status)).length, approvedNotifications: queue.notifications.filter((item) => ["APPROVED", "CONVERTED_TO_WORK_ORDER", "IN_MAINTENANCE"].includes(item.status)).length }), [queue, user]);
  const assetMap = useMemo(() => new Map(queue.assets.map((asset) => [asset.id, asset])), [queue.assets]);
  const notificationStatuses = useMemo(() => [...new Set(queue.notifications.map((item) => item.status))].sort((left, right) => label(left).localeCompare(label(right), "th")), [queue.notifications]);
  const sortedNotifications = useMemo(() => {
    const query = notificationSearch.trim().toLowerCase(); const priorities: Record<string, number> = { LOW: 1, MEDIUM: 2, HIGH: 3, CRITICAL: 4 };
    return queue.notifications.filter((item) => { const asset = assetMap.get(item.assetId); const matchesSearch = !query || `${item.code} ${item.title} ${item.description} ${asset?.code ?? ""} ${asset?.name ?? ""} ${item.status} ${item.priority}`.toLowerCase().includes(query); return matchesSearch && (!notificationStatus || item.status === notificationStatus) && (!notificationPriority || item.priority === notificationPriority); }).sort((left, right) => {
      const leftAsset = assetMap.get(left.assetId); const rightAsset = assetMap.get(right.assetId);
      const values: Record<NotificationSort, [string | number, string | number]> = { code: [left.code, right.code], title: [left.title, right.title], asset: [`${leftAsset?.code ?? ""} ${leftAsset?.name ?? ""}`, `${rightAsset?.code ?? ""} ${rightAsset?.name ?? ""}`], priority: [priorities[left.priority] ?? 0, priorities[right.priority] ?? 0], status: [left.status, right.status], updatedAt: [new Date(left.updatedAt).getTime(), new Date(right.updatedAt).getTime()] };
      const [a, b] = values[notificationSort]; const result = typeof a === "number" && typeof b === "number" ? a - b : String(a).localeCompare(String(b), "th"); return sortDirection === "asc" ? result : -result;
    });
  }, [assetMap, notificationPriority, notificationSearch, notificationSort, notificationStatus, queue.notifications, sortDirection]);
  const notificationPages = Math.max(1, Math.ceil(sortedNotifications.length / notificationPageSize));
  const visibleNotifications = sortedNotifications.slice((notificationPage - 1) * notificationPageSize, notificationPage * notificationPageSize);
  function sortNotifications(column: NotificationSort) { setNotificationPage(1); if (notificationSort === column) setSortDirection((value) => value === "asc" ? "desc" : "asc"); else { setNotificationSort(column); setSortDirection(column === "updatedAt" ? "desc" : "asc"); } }
  return <PageContainer className="max-w-[92rem]" id="workflow-main">
    <PageHeader eyebrow={notificationOnly ? "Maintenance notification" : "Governed maintenance"} title={notificationOnly ? "รายการแจ้งบำรุงรักษา" : "ศูนย์ควบคุมงานซ่อมบำรุง"} description={notificationOnly ? "สร้าง ติดตาม และแก้ไขใบแจ้งเหตุขัดข้องหรือคำขอบำรุงรักษาของคุณ" : "สถานะ ผู้รับผิดชอบ และขั้นตอนถัดไปจากใบแจ้งจนถึงการปิดงาน"} />
    {notificationOnly ? <div className="mb-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4" aria-label="สรุปใบแจ้งบำรุงรักษา"><Metric icon={ClipboardList} label="ฉบับร่าง" value={counts.drafts} /><Metric icon={UserRoundCog} label="รอตรวจสอบ" value={counts.pendingNotifications} /><Metric icon={RefreshCw} label="ส่งกลับให้แก้ไข" value={counts.returnedNotifications} /><Metric icon={CheckCircle2} label="อนุมัติแล้ว" value={counts.approvedNotifications} /></div> : <div className="mb-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4" aria-label="สรุปคิวงาน"><Metric icon={Wrench} label="งานที่มอบหมายให้ฉัน" value={counts.mine} /><Metric icon={UserRoundCog} label="รอ Manager ตรวจ" value={counts.review} /><Metric icon={CheckCircle2} label="รอ Operator ยอมรับ" value={counts.acceptance} /><Metric icon={AlertTriangle} label="เกินกำหนด" value={counts.overdue} danger={counts.overdue > 0} /></div>}
    <div aria-live="polite">{message && <Alert className="mb-4 border-emerald-200 bg-emerald-50 text-emerald-900">{message}</Alert>}</div><div aria-live="assertive">{error && <Alert className="mb-4 border-red-200 bg-red-50 text-red-900">{error}</Alert>}</div>
    <div className="mb-5 flex flex-wrap items-center justify-between gap-3">{notificationOnly ? <p className="text-sm font-semibold text-slate-600">ทั้งหมด {queue.notifications.length} รายการ</p> : <div className="flex rounded-xl border bg-white p-1"><Button variant={tab === "notifications" ? "default" : "ghost"} onClick={() => setTab("notifications")}><ClipboardList className="size-4" />ใบแจ้ง ({queue.notifications.length})</Button><Button variant={tab === "work-orders" ? "default" : "ghost"} onClick={() => setTab("work-orders")}><Wrench className="size-4" />Work Orders ({queue.workOrders.length})</Button></div>}<div className="flex gap-2">{permitted("NOTIFICATION_CREATE") && <Button onClick={() => setShowCreate((value) => !value)}>สร้างใบแจ้งบำรุงรักษา</Button>}<Button variant="outline" onClick={() => void load()} disabled={busy}><RefreshCw className={cn("size-4", busy && "animate-spin")} />รีเฟรช</Button></div></div>
    {showCreate && <NotificationCreateForm onSubmit={createNotification} onCancel={() => setShowCreate(false)} />}
    {notificationOnly ? <NotificationTable items={visibleNotifications} total={sortedNotifications.length} page={notificationPage} pages={notificationPages} pageSize={notificationPageSize} search={notificationSearch} status={notificationStatus} priority={notificationPriority} statuses={notificationStatuses} sort={notificationSort} direction={sortDirection} assets={assetMap} busy={busy} onSearch={(value) => { setNotificationSearch(value); setNotificationPage(1); }} onStatus={(value) => { setNotificationStatus(value); setNotificationPage(1); }} onPriority={(value) => { setNotificationPriority(value); setNotificationPage(1); }} onClear={() => { setNotificationSearch(""); setNotificationStatus(""); setNotificationPriority(""); setNotificationPage(1); }} onSort={sortNotifications} onPage={setNotificationPage} onPageSize={(value) => { setNotificationPageSize(value); setNotificationPage(1); }} onView={setSelectedNotification} /> : <div className="grid gap-4">{(tab === "notifications" ? queue.notifications : queue.workOrders).map((item) => <WorkflowCard key={item.id} item={item} kind={tab === "notifications" ? "notification" : "work-order"} currentUser={user} technicians={queue.technicians} permitted={permitted} command={command} editNotification={editNotification} />)}{!busy && (tab === "notifications" ? queue.notifications : queue.workOrders).length === 0 && <Card><CardContent className="py-12 text-center text-slate-500">ไม่มีรายการในขอบเขตที่คุณรับผิดชอบ</CardContent></Card>}</div>}
    <NotificationDetailSheet item={selectedNotification} asset={selectedNotification ? assetMap.get(selectedNotification.assetId) : undefined} onClose={() => setSelectedNotification(null)} user={user} technicians={queue.technicians} permitted={permitted} command={command} editNotification={editNotification} />
  </PageContainer>;
}

function NotificationCreateForm({ onSubmit, onCancel }: { onSubmit: (event: FormEvent<HTMLFormElement>) => Promise<boolean>; onCancel: () => void }) {
  const [photos, setPhotos] = useState<File[]>([]); const [submitting, setSubmitting] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { setSubmitting(true); try { await onSubmit(event); } finally { setSubmitting(false); } }
  return <Card className="mb-5"><CardHeader><CardTitle>สร้างใบแจ้งซ่อม</CardTitle></CardHeader><CardContent><form onSubmit={submit} className="grid gap-4 md:grid-cols-2">
    <fieldset className="grid gap-2"><legend className="text-sm font-medium">อุปกรณ์ <span className="text-red-600">*</span><span className="sr-only">จำเป็น</span></legend><AssetCombobox name="assetId" required /></fieldset>
    <Field label="ความเร่งด่วน"><select name="priority" className="wo-input"><option>MEDIUM</option><option>HIGH</option><option>CRITICAL</option><option>LOW</option></select></Field>
    <Field label="หัวข้อ"><Input name="title" required minLength={3} /></Field><Field label="วันเวลาเกิดเหตุ"><Input name="incidentAt" type="datetime-local" /></Field>
    <Field label="ประเภทปัญหา"><Input name="problemCategory" placeholder="เช่น Electrical, Mechanical" /></Field><Field label="ประเภทงาน"><select name="type" className="wo-input"><option>CORRECTIVE</option><option>BREAKDOWN</option><option>INSPECTION</option></select></Field>
    <Field label="อาการที่พบ"><Input name="symptoms" /></Field><Field label="Team / Responsible Group"><Input name="responsibleGroup" /></Field>
    <Field label="รายละเอียดปัญหา" wide><textarea name="description" required minLength={5} className="wo-input min-h-24" /></Field>
    <Field label="ผลกระทบต่อการปฏิบัติงาน"><textarea name="operationalImpact" className="wo-input min-h-20" /></Field><Field label="ผลกระทบด้านการผลิต"><textarea name="productionImpact" className="wo-input min-h-20" /></Field>
    <Field label="ผลกระทบด้านความปลอดภัย"><textarea name="safetyImpact" className="wo-input min-h-20" /></Field><Field label="ผู้ติดต่อ"><Input name="contactPerson" /></Field>
    <Field label="โทรศัพท์"><Input name="contactPhone" /></Field><Field label="หมายเหตุ"><textarea name="remarks" className="wo-input min-h-20" /></Field>
    <fieldset className="grid gap-2 md:col-span-2"><legend className="text-sm font-medium">รูปประกอบ</legend><label htmlFor="notification-photos" className="flex min-h-24 cursor-pointer items-center gap-3 rounded-xl border border-dashed border-slate-300 bg-slate-50 p-4 transition-colors hover:border-blue-400 hover:bg-blue-50 focus-within:ring-2 focus-within:ring-blue-600 focus-within:ring-offset-2"><ImagePlus className="size-8 shrink-0 text-blue-700" /><span><strong className="block text-sm">เลือกรูปได้หลายรูป</strong><span id="notification-photos-help" className="mt-1 block text-xs font-normal text-slate-500">รองรับ JPEG, PNG และ WebP สูงสุด 10 รูป รูปละไม่เกิน 5 MB</span></span><input id="notification-photos" name="photos" type="file" accept="image/jpeg,image/png,image/webp" multiple disabled={submitting} className="sr-only" aria-describedby="notification-photos-help notification-photos-status" onChange={(event) => setPhotos(Array.from(event.target.files ?? []))} /></label><div id="notification-photos-status" aria-live="polite">{photos.length > 0 && <><p className="text-sm font-semibold text-slate-700">เลือกแล้ว {photos.length} รูป</p><ul className="grid gap-1 text-xs text-slate-600 sm:grid-cols-2">{photos.map((file, index) => <li key={`${file.name}-${file.lastModified}-${index}`} className="truncate rounded-lg border bg-white px-3 py-2">{index + 1}. {file.name} · {(file.size / 1024 / 1024).toFixed(2)} MB</li>)}</ul></>}</div></fieldset>
    <div className="flex gap-2 md:col-span-2"><Button type="submit" disabled={submitting}>{submitting && <Loader2 className="size-4 animate-spin" />}{submitting ? `กำลังอัปโหลด ${photos.length} รูป…` : "บันทึกร่าง"}</Button><Button type="button" variant="outline" onClick={onCancel} disabled={submitting}>ยกเลิก</Button></div>
  </form></CardContent></Card>;
}

function NotificationTable({ items, total, page, pages, pageSize, search, status, priority, statuses, sort, direction, assets, busy, onSearch, onStatus, onPriority, onClear, onSort, onPage, onPageSize, onView }: { items: NotificationRow[]; total: number; page: number; pages: number; pageSize: number; search: string; status: string; priority: string; statuses: string[]; sort: NotificationSort; direction: "asc" | "desc"; assets: Map<string, Queue["assets"][number]>; busy: boolean; onSearch: (value: string) => void; onStatus: (value: string) => void; onPriority: (value: string) => void; onClear: () => void; onSort: (value: NotificationSort) => void; onPage: (value: number) => void; onPageSize: (value: number) => void; onView: (item: NotificationRow) => void }) {
  const first = total ? (page - 1) * pageSize + 1 : 0; const last = Math.min(page * pageSize, total);
  const hasFilters = Boolean(search || status || priority);
  return <Card className="overflow-hidden"><CardContent className="p-0"><div className="grid gap-3 border-b bg-slate-50 p-4 lg:grid-cols-[minmax(16rem,1fr)_auto]"><div className="relative"><Search className="pointer-events-none absolute left-3 top-3.5 size-4 text-slate-400" /><Input value={search} onChange={(event) => onSearch(event.target.value)} className="pl-9" placeholder="ค้นหาเลขที่ หัวข้อ หรือ Asset" aria-label="ค้นหาใบแจ้งบำรุงรักษา" /></div><div className="grid gap-2 sm:grid-cols-2 lg:flex lg:items-end"><label className="grid gap-1 text-xs font-medium text-slate-600"><span>Status</span><select value={status} onChange={(event) => onStatus(event.target.value)} className="min-h-10 rounded-lg border bg-white px-3 text-sm" aria-label="กรองตามสถานะ"><option value="">ทุกสถานะ</option>{statuses.map((value) => <option key={value} value={value}>{label(value)}</option>)}</select></label><label className="grid gap-1 text-xs font-medium text-slate-600"><span>Priority</span><select value={priority} onChange={(event) => onPriority(event.target.value)} className="min-h-10 rounded-lg border bg-white px-3 text-sm" aria-label="กรองตามความสำคัญ"><option value="">ทุก Priority</option><option value="CRITICAL">Critical</option><option value="HIGH">High</option><option value="MEDIUM">Medium</option><option value="LOW">Low</option></select></label><label className="flex items-center gap-2 self-end text-sm text-slate-600">แสดง<select value={pageSize} onChange={(event) => onPageSize(Number(event.target.value))} className="min-h-10 rounded-lg border bg-white px-2" aria-label="จำนวนรายการต่อหน้า"><option value={10}>10</option><option value={20}>20</option><option value={50}>50</option></select>รายการ</label>{hasFilters && <Button type="button" variant="ghost" className="self-end" onClick={onClear}>ล้างตัวกรอง</Button>}</div></div>
    <div className="overflow-x-auto"><table className="w-full min-w-[70rem] text-left text-sm"><thead className="border-b bg-white text-xs uppercase tracking-wide text-slate-500"><tr><SortHeader column="code" label="เลขที่ใบแจ้ง" active={sort} direction={direction} onSort={onSort} /><SortHeader column="title" label="หัวข้อ" active={sort} direction={direction} onSort={onSort} /><SortHeader column="asset" label="Asset" active={sort} direction={direction} onSort={onSort} /><SortHeader column="priority" label="Priority" active={sort} direction={direction} onSort={onSort} /><SortHeader column="status" label="Status" active={sort} direction={direction} onSort={onSort} /><SortHeader column="updatedAt" label="อัปเดตล่าสุด" active={sort} direction={direction} onSort={onSort} /><th className="px-4 py-3 text-right font-semibold">ดูรายละเอียด</th></tr></thead><tbody className="divide-y">{items.map((item) => { const asset = assets.get(item.assetId); return <tr key={item.id} className="hover:bg-blue-50/40"><td className="px-4 py-4 font-mono text-xs font-bold text-blue-700">{item.code}</td><td className="max-w-xs px-4 py-4"><strong className="block truncate">{item.title}</strong><span className="mt-1 block truncate text-xs text-slate-500">{item.description}</span></td><td className="px-4 py-4"><strong className="block text-xs">{asset?.code ?? "—"}</strong><span className="block max-w-52 truncate text-xs text-slate-500">{asset?.name ?? "ไม่พบข้อมูล Asset"}</span></td><td className="px-4 py-4"><span className={cn("font-bold", item.priority === "CRITICAL" ? "text-red-700" : item.priority === "HIGH" ? "text-amber-700" : "text-slate-700")}>{item.priority}</span></td><td className="px-4 py-4"><Badge className={statusTone(item.status)}>{label(item.status)}</Badge></td><td className="px-4 py-4 text-slate-600">{new Date(item.updatedAt).toLocaleString("th-TH")}</td><td className="px-4 py-4 text-right"><Button size="sm" variant="outline" onClick={() => onView(item)}><Eye className="size-4" />ดู</Button></td></tr>; })}</tbody></table></div>
    {!busy && items.length === 0 && <div className="p-12 text-center"><ClipboardList className="mx-auto size-9 text-slate-400" /><p className="mt-3 font-semibold">ไม่พบใบแจ้งบำรุงรักษา</p><p className="mt-1 text-sm text-slate-500">ลองเปลี่ยนคำค้นหา หรือสร้างใบแจ้งใหม่</p></div>}
    <div className="flex flex-col gap-3 border-t px-4 py-3 text-sm text-slate-600 sm:flex-row sm:items-center sm:justify-between"><span>แสดง {first}–{last} จาก {total} รายการ</span><div className="flex items-center gap-2"><Button size="icon" variant="outline" aria-label="หน้าก่อน" disabled={page <= 1} onClick={() => onPage(page - 1)}><ChevronLeft className="size-4" /></Button><span>หน้า {page} / {pages}</span><Button size="icon" variant="outline" aria-label="หน้าถัดไป" disabled={page >= pages} onClick={() => onPage(page + 1)}><ChevronRight className="size-4" /></Button></div></div>
  </CardContent></Card>;
}

function SortHeader({ column, label: text, active, direction, onSort }: { column: NotificationSort; label: string; active: NotificationSort; direction: "asc" | "desc"; onSort: (value: NotificationSort) => void }) {
  return <th className="px-4 py-3 font-semibold" aria-sort={active === column ? direction === "asc" ? "ascending" : "descending" : "none"}><button type="button" onClick={() => onSort(column)} className="inline-flex min-h-9 items-center gap-1 rounded-md px-1 hover:text-slate-900 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-600">{text}<ArrowUpDown className={cn("size-3.5", active === column ? "text-blue-700" : "text-slate-300")} /></button></th>;
}

function NotificationDetailSheet({ item, asset, onClose, user, technicians, permitted, command, editNotification }: { item: NotificationRow | null; asset?: Queue["assets"][number]; onClose: () => void; user: CurrentUser | null; technicians: Queue["technicians"]; permitted: (permission: string) => boolean; command: (url: string, payload: unknown, success: string) => Promise<boolean>; editNotification: (item: NotificationRow) => Promise<void> }) {
  const photos = attachmentIds(item?.photoAttachmentIds);
  return <Sheet open={Boolean(item)} onOpenChange={(open) => { if (!open) onClose(); }}><SheetContent className="w-full overflow-y-auto p-0 sm:max-w-2xl"><SheetHeader className="sticky top-0 z-10 border-b bg-white p-5 pr-14"><SheetTitle>{item?.code ?? "รายละเอียดใบแจ้ง"}</SheetTitle><SheetDescription>{item?.title ?? "ข้อมูลใบแจ้งบำรุงรักษา"}</SheetDescription></SheetHeader>{item && <div className="space-y-5 p-5"><section className="grid gap-3 rounded-xl border bg-slate-50 p-4 sm:grid-cols-2"><Info label="Asset" value={asset ? `${asset.code} — ${asset.name}` : "—"} /><Info label="Location" value={asset?.location ?? "—"} /><Info label="Priority" value={item.priority} /><Info label="Status" value={label(item.status)} /><Info label="ประเภทงาน" value={item.type ? label(item.type) : "—"} /><Info label="วันที่เกิดเหตุ" value={item.incidentAt ? new Date(item.incidentAt).toLocaleString("th-TH") : "—"} /></section><DetailSection title="รายละเอียดปัญหา" value={item.description} /><div className="grid gap-4 sm:grid-cols-2"><DetailSection title="อาการที่พบ" value={item.symptoms} /><DetailSection title="ประเภทปัญหา" value={item.problemCategory} /><DetailSection title="ผลกระทบต่อการปฏิบัติงาน" value={item.operationalImpact} /><DetailSection title="ผลกระทบด้านการผลิต" value={item.productionImpact} /><DetailSection title="ผลกระทบด้านความปลอดภัย" value={item.safetyImpact} /><DetailSection title="Team / Responsible Group" value={item.responsibleGroup} /><DetailSection title="ผู้ติดต่อ" value={[item.contactPerson, item.contactPhone].filter(Boolean).join(" · ")} /><DetailSection title="หมายเหตุ" value={item.remarks} /></div>{photos.length > 0 && <section><h3 className="text-xs font-bold uppercase tracking-wide text-slate-500">รูปประกอบ ({photos.length})</h3><div className="mt-2 grid gap-2 sm:grid-cols-2">{photos.map((id, index) => <a key={id} href={`/api/attachments/${id}/content`} target="_blank" rel="noreferrer" className="flex min-h-11 items-center gap-2 rounded-lg border bg-white px-3 py-2 text-sm font-medium text-blue-700 hover:bg-blue-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-600"><ImagePlus className="size-4" />เปิดรูปที่ {index + 1}</a>)}</div></section>}{(item.informationRequest || item.rejectionReason) && <Alert className="border-amber-200 bg-amber-50 text-amber-900">{item.informationRequest || item.rejectionReason}</Alert>}<WorkflowCard item={item} kind="notification" currentUser={user} technicians={technicians} permitted={permitted} command={command} editNotification={editNotification} /></div>}</SheetContent></Sheet>;
}

function DetailSection({ title, value }: { title: string; value?: string | null }) { return <section><h3 className="text-xs font-bold uppercase tracking-wide text-slate-500">{title}</h3><p className="mt-1 whitespace-pre-wrap text-sm leading-6 text-slate-700">{value || "—"}</p></section>; }

function Metric({ icon: Icon, label: text, value, danger }: { icon: typeof Wrench; label: string; value: number; danger?: boolean }) { return <Card className={cn(danger && "border-red-200 bg-red-50")}><CardContent className="flex items-center gap-4 p-4"><div className="rounded-xl bg-slate-900 p-2.5 text-white"><Icon className="size-5" /></div><div><p className="text-xs text-slate-500">{text}</p><strong className="text-2xl tabular-nums">{value}</strong></div></CardContent></Card>; }

function WorkflowCard({ item, kind, currentUser, technicians, permitted, command, editNotification }: { item: NotificationRow | WorkOrderRow; kind: "notification" | "work-order"; currentUser: CurrentUser | null; technicians: Queue["technicians"]; permitted: (permission: string) => boolean; command: (url: string, payload: unknown, success: string) => Promise<boolean>; editNotification: (item: NotificationRow) => Promise<void> }) {
  const [responsibleRole, nextAction] = responsibility[item.status] ?? ["Maintenance", "ตรวจสอบรายการ"]; const overdue = Boolean(item.dueAt && new Date(item.dueAt) < new Date() && !["CLOSED", "CANCELLED"].includes(item.status)); const base = kind === "notification" ? `/api/maintenance/workflow/notifications/${item.id}/commands` : `/api/maintenance/workflow/work-orders/${item.id}/commands`;
  const ask = (text: string) => window.prompt(text)?.trim();
  const techId = () => technicians[0]?.id;
  return <Card className={cn("overflow-hidden", overdue && "border-red-300")}><CardHeader className="border-b bg-slate-50/70 pb-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="mb-1 font-mono text-xs font-bold text-blue-700">{item.code}</p><CardTitle className="text-lg">{item.title}</CardTitle></div><Badge className={statusTone(item.status)}>{label(item.status)}</Badge></div></CardHeader><CardContent className="grid gap-5 p-5 lg:grid-cols-[1fr_auto]"><dl className="grid gap-x-8 gap-y-3 text-sm sm:grid-cols-2 xl:grid-cols-4"><Info label="ผู้รับผิดชอบปัจจุบัน" value={responsibleRole} /><Info label="ขั้นตอนถัดไป" value={nextAction} /><Info label="เวลาในสถานะ" value={age(item.updatedAt)} icon={<Clock3 className="size-3.5" />} /><Info label="กำหนดเสร็จ" value={item.dueAt ? new Date(item.dueAt).toLocaleString("th-TH") : "ยังไม่กำหนด"} danger={overdue} /></dl><div className="flex max-w-lg flex-wrap items-center justify-start gap-2 lg:justify-end" aria-label={`การดำเนินการสำหรับ ${item.code}`}>
    {kind === "notification" && item.status === "DRAFT" && permitted("NOTIFICATION_SUBMIT") && <Button size="sm" onClick={() => void command(`${base}/submit`, { comment: "ส่งใบแจ้งเพื่อพิจารณา" }, "ส่งใบแจ้งแล้ว")}>ส่งใบแจ้ง</Button>}
    {kind === "notification" && "description" in item && ["DRAFT", "RETURNED", "NEEDS_INFORMATION"].includes(item.status) && item.requestedBy === currentUser?.id && permitted("NOTIFICATION_EDIT_OWN_DRAFT") && <Button size="sm" variant="outline" onClick={() => void editNotification(item)}>แก้ไขใบแจ้ง</Button>}
    {kind === "notification" && item.status === "SUBMITTED" && permitted("NOTIFICATION_REVIEW") && <Button size="sm" onClick={() => void command(`${base}/review`, { action: "START_REVIEW", comment: "เริ่มตรวจสอบ" }, "เริ่มตรวจสอบแล้ว")}>เริ่มตรวจสอบ</Button>}
    {kind === "notification" && item.status === "UNDER_REVIEW" && permitted("NOTIFICATION_APPROVE") && <Button size="sm" onClick={() => void command(`${base}/review`, { action: "APPROVE", comment: "อนุมัติให้ดำเนินงาน" }, "อนุมัติใบแจ้งแล้ว")}>อนุมัติ</Button>}
    {kind === "notification" && item.status === "UNDER_REVIEW" && permitted("NOTIFICATION_REQUEST_INFORMATION") && <Button size="sm" variant="outline" onClick={() => { const comment = ask("ระบุข้อมูลที่ต้องการเพิ่มเติม"); if (comment) void command(`${base}/review`, { action: "REQUEST_INFORMATION", comment }, "ส่งคำขอข้อมูลแล้ว"); }}>ขอข้อมูลเพิ่ม</Button>}
    {kind === "notification" && item.status === "UNDER_REVIEW" && permitted("NOTIFICATION_REJECT") && <Button size="sm" variant="outline" onClick={() => { const comment = ask("ระบุเหตุผลที่ปฏิเสธ"); if (comment) void command(`${base}/review`, { action: "REJECT", comment }, "ปฏิเสธใบแจ้งแล้ว"); }}>ปฏิเสธ</Button>}
    {kind === "notification" && ["RETURNED", "NEEDS_INFORMATION"].includes(item.status) && permitted("NOTIFICATION_SUBMIT") && <Button size="sm" onClick={() => { const response = ask("สรุปข้อมูลที่แก้ไขก่อนส่งใหม่"); if (response) void command(`${base}/provide-information`, { response, attachmentIds: [] }, "ส่งใบแจ้งเข้าตรวจสอบรอบใหม่แล้ว"); }}>ส่งใหม่เพื่อตรวจสอบ</Button>}
    {kind === "notification" && item.status === "APPROVED" && permitted("WORK_ORDER_CREATE") && techId() && <Button size="sm" onClick={() => void command(`${base}/create-work-order`, { technicianId: techId(), instructions: "ตรวจสอบและดำเนินการตามมาตรฐานความปลอดภัย", teamName: "Maintenance" }, "สร้างและมอบหมาย Work Order แล้ว")}>สร้าง Work Order</Button>}
    {kind === "notification" && item.status === "READY_TO_CLOSE" && permitted("NOTIFICATION_CLOSE") && <Button size="sm" onClick={() => void command(`${base}/close`, { comment: "Operator ยืนยันปิดใบแจ้ง" }, "ปิดใบแจ้งแล้ว")}>ปิดใบแจ้ง</Button>}
    {kind === "work-order" && "assignedTo" in item && item.status === "ASSIGNED" && item.assignedTo === currentUser?.id && permitted("WORK_ORDER_ACCEPT_ASSIGNMENT") && <Button size="sm" onClick={() => void command(`${base}/accept-assignment`, { note: "รับทราบการมอบหมาย" }, "รับมอบหมายแล้ว")}>รับมอบหมาย</Button>}
    {kind === "work-order" && "assignedTo" in item && ["TECHNICIAN_ACCEPTED", "RETURNED_TO_TECHNICIAN"].includes(item.status) && item.assignedTo === currentUser?.id && permitted("WORK_ORDER_START") && <Button size="sm" onClick={() => void command(`${base}/start`, { note: item.status === "RETURNED_TO_TECHNICIAN" ? "เริ่มตรวจซ้ำ" : "เริ่มปฏิบัติงาน" }, "เริ่มงานแล้ว")}>เริ่มงาน</Button>}
    {kind === "work-order" && "assignedTo" in item && item.status === "IN_PROGRESS" && item.assignedTo === currentUser?.id && permitted("WORK_ORDER_UPDATE_PROGRESS") && <Button size="sm" variant="outline" onClick={() => { const reason = ask("ระบุเหตุผลที่รออะไหล่"); if (reason) void command(`${base}/wait`, { status: "WAITING_FOR_PARTS", reason }, "บันทึกสถานะรออะไหล่แล้ว"); }}>รออะไหล่</Button>}
    {kind === "work-order" && "assignedTo" in item && ["WAITING_FOR_PARTS", "WAITING_FOR_VENDOR", "WAITING_FOR_ACCESS", "ON_HOLD"].includes(item.status) && item.assignedTo === currentUser?.id && permitted("WORK_ORDER_UPDATE_PROGRESS") && <Button size="sm" onClick={() => void command(`${base}/resume`, { note: "เหตุรอได้รับการแก้ไขแล้ว" }, "กลับมาดำเนินงานแล้ว")}>ดำเนินงานต่อ</Button>}
    {kind === "work-order" && "assignedTo" in item && item.status === "IN_PROGRESS" && item.assignedTo === currentUser?.id && permitted("WORK_ORDER_SUBMIT_COMPLETION") && <Button size="sm" onClick={() => { const summary = ask("สรุปงานและผลการแก้ไข"); if (summary) void command(`${base}/submit-completion`, { diagnosis: summary, rootCauseUnknownReason: "บันทึกสาเหตุโดยละเอียดในสรุปงาน", correctiveAction: summary, workSummary: summary, laborMinutes: 30, partsFinalized: true, noPartsUsed: true, testProcedure: "ทดสอบการทำงานตามสภาวะใช้งาน", testResult: "ผ่าน", beforePhotoAttachmentIds: [], afterPhotoAttachmentIds: [] }, "ส่ง completion revision แล้ว"); }}>ส่งผลการซ่อม</Button>}
    {kind === "work-order" && ["TECHNICIAN_COMPLETED", "UNDER_MANAGER_REVIEW"].includes(item.status) && permitted("WORK_ORDER_APPROVE_COMPLETION") && <Button size="sm" onClick={() => void command(`${base}/manager-decision`, { decision: "APPROVE", comment: "ตรวจหลักฐานและผลทดสอบแล้ว" }, "Manager อนุมัติงานแล้ว")}>อนุมัติผลซ่อม</Button>}
    {kind === "work-order" && ["TECHNICIAN_COMPLETED", "UNDER_MANAGER_REVIEW"].includes(item.status) && permitted("WORK_ORDER_RETURN_FOR_RECHECK") && <Button size="sm" variant="outline" onClick={() => { const comment = ask("ระบุเหตุผลและสิ่งที่ต้องแก้ไข"); if (comment) void command(`${base}/manager-decision`, { decision: "RETURN", comment, requiredActions: [comment] }, "ส่งกลับให้ตรวจซ้ำแล้ว"); }}>ส่งตรวจซ้ำ</Button>}
    {kind === "work-order" && item.status === "OPERATOR_REJECTED" && permitted("WORK_ORDER_RETURN_FOR_RECHECK") && <Button size="sm" onClick={() => { const comment = ask("ระบุคำสั่งตรวจซ้ำ"); if (comment) void command(`${base}/return-operator-rejection`, { decision: "RETURN", comment, requiredActions: [comment] }, "ส่งงานกลับให้ช่างแล้ว"); }}>ส่งกลับให้ช่าง</Button>}
    {kind === "work-order" && item.status === "WAITING_FOR_OPERATOR_ACCEPTANCE" && permitted("NOTIFICATION_ACCEPT_WORK") && <Button size="sm" onClick={() => void command(`${base}/operator-decision`, { decision: "ACCEPT", comment: "ผลการซ่อมเป็นที่ยอมรับ" }, "ยอมรับงานแล้ว")}>ยอมรับงาน</Button>}
    {kind === "work-order" && item.status === "WAITING_FOR_OPERATOR_ACCEPTANCE" && permitted("NOTIFICATION_REJECT_WORK") && <Button size="sm" variant="outline" onClick={() => { const reason = ask("ระบุปัญหาที่ยังพบ"); if (reason) void command(`${base}/operator-decision`, { decision: "REJECT", reason, remainingProblem: reason, attachmentIds: [] }, "ส่งคำขอตรวจซ้ำแล้ว"); }}>ขอตรวจซ้ำ</Button>}
    {kind === "work-order" && item.status === "OPERATOR_ACCEPTED" && permitted("WORK_ORDER_CLOSE") && <Button size="sm" onClick={() => void command(`${base}/close`, { note: "ปิดหลัง Operator ยอมรับงาน" }, "ปิด Work Order แล้ว")}>ปิด Work Order</Button>}
  </div></CardContent></Card>;
}
function Info({ label: term, value, danger, icon }: { label: string; value: string; danger?: boolean; icon?: React.ReactNode }) { return <div><dt className="mb-1 text-xs text-slate-500">{term}</dt><dd className={cn("flex items-center gap-1 font-medium", danger && "text-red-700")}>{icon}{value}</dd></div>; }
function Field({ label: text, children, wide }: { label: string; children: React.ReactNode; wide?: boolean }) { return <label className={cn("grid gap-1 text-sm font-medium", wide && "md:col-span-2")}><span>{text}</span>{children}</label>; }
