"use client";

import { useCallback, useEffect, useMemo, useState, type FormEvent } from "react";
import { AlertTriangle, CheckCircle2, Clock3, ClipboardList, RefreshCw, UserRoundCog, Wrench } from "lucide-react";
import { Alert } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { PageContainer, PageHeader } from "@/components/shared/page-header";
import { cn } from "@/lib/utils";

type Permission = string;
type CurrentUser = { id: string; fullName: string; role: string; permissions: Permission[] };
type NotificationRow = { id: string; code: string; title: string; status: string; priority: string; requestedBy: string; departmentId: string | null; dueAt: string | null; updatedAt: string };
type WorkOrderRow = { id: string; code: string; notificationId: string | null; title: string; status: string; priority: string; assignedTo: string | null; dueAt: string | null; updatedAt: string };
type Queue = { notifications: NotificationRow[]; workOrders: WorkOrderRow[]; technicians: Array<{ id: string; fullName: string }>; assets: Array<{ id: string; code: string; name: string; location: string }> };

const responsibility: Record<string, [string, string]> = {
  DRAFT: ["Operator", "กรอกข้อมูลและส่งใบแจ้ง"], SUBMITTED: ["Maintenance Manager", "เริ่มตรวจสอบ"], UNDER_REVIEW: ["Maintenance Manager", "อนุมัติ ปฏิเสธ หรือขอข้อมูลเพิ่ม"], NEEDS_INFORMATION: ["Operator", "ให้ข้อมูลเพิ่มเติม"], APPROVED: ["Maintenance Manager", "สร้างและมอบหมาย Work Order"], IN_MAINTENANCE: ["Maintenance", "ดำเนินงานซ่อม"], WAITING_FOR_OPERATOR_ACCEPTANCE: ["Operator", "ยอมรับงานหรือขอตรวจซ้ำ"], OPERATOR_REJECTED: ["Maintenance Manager", "ส่งกลับให้ช่างตรวจซ้ำ"], READY_TO_CLOSE: ["Operator", "ปิดใบแจ้ง"],
  CREATED: ["Maintenance Manager", "มอบหมายช่าง"], ASSIGNED: ["Technician", "รับมอบหมาย"], TECHNICIAN_ACCEPTED: ["Technician", "เริ่มงาน"], IN_PROGRESS: ["Technician", "ดำเนินงานและส่งผล"], WAITING_FOR_PARTS: ["Technician", "ดำเนินงานต่อเมื่ออะไหล่พร้อม"], WAITING_FOR_VENDOR: ["Technician", "ดำเนินงานต่อเมื่อผู้รับเหมาพร้อม"], WAITING_FOR_ACCESS: ["Technician", "ดำเนินงานต่อเมื่อเข้าพื้นที่ได้"], ON_HOLD: ["Technician", "แก้เหตุพักงานและดำเนินงานต่อ"], TECHNICIAN_COMPLETED: ["Maintenance Manager", "ตรวจผลการซ่อม"], UNDER_MANAGER_REVIEW: ["Maintenance Manager", "อนุมัติหรือส่งตรวจซ้ำ"], RETURNED_TO_TECHNICIAN: ["Technician", "ตรวจซ้ำและส่ง revision ใหม่"], MANAGER_APPROVED: ["Maintenance Manager", "ขอ Operator ยอมรับงาน"], OPERATOR_ACCEPTED: ["Maintenance Manager", "ปิด Work Order"], CLOSED: ["—", "ปิดแล้ว"], CANCELLED: ["—", "ยกเลิกแล้ว"],
};
const statusTone = (status: string) => status === "CLOSED" || status === "OPERATOR_ACCEPTED" ? "border-emerald-200 bg-emerald-50 text-emerald-800" : status.includes("REJECT") || status.includes("RETURN") ? "border-red-200 bg-red-50 text-red-800" : status.includes("WAIT") || status === "ON_HOLD" ? "border-amber-200 bg-amber-50 text-amber-900" : "border-blue-200 bg-blue-50 text-blue-800";
const label = (value: string) => value.replaceAll("_", " ").toLowerCase().replace(/(^|\s)\S/g, (letter) => letter.toUpperCase());
const age = (value: string) => { const hours = Math.max(0, Math.floor((Date.now() - new Date(value).getTime()) / 3_600_000)); return hours < 24 ? `${hours} ชม.` : `${Math.floor(hours / 24)} วัน`; };

async function jsonRequest(url: string, init?: RequestInit) { const response = await fetch(url, init); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error || "ไม่สามารถดำเนินการได้"); return body; }

export default function GovernedWorkflowWorkspace() {
  const [queue, setQueue] = useState<Queue>({ notifications: [], workOrders: [], technicians: [], assets: [] }); const [user, setUser] = useState<CurrentUser | null>(null); const [tab, setTab] = useState<"notifications" | "work-orders">("notifications"); const [showCreate, setShowCreate] = useState(false); const [busy, setBusy] = useState(true); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const load = useCallback(async () => { setBusy(true); try { const [next, me] = await Promise.all([jsonRequest("/api/maintenance/workflow/queue"), jsonRequest("/api/auth/me")]); setQueue(next); setUser(me.user); setError(""); } catch (cause) { setError(cause instanceof Error ? cause.message : "โหลดคิวงานไม่สำเร็จ"); } finally { setBusy(false); } }, []);
  useEffect(() => { let active = true; Promise.all([jsonRequest("/api/maintenance/workflow/queue"), jsonRequest("/api/auth/me")]).then(([next, me]) => { if (active) { setQueue(next); setUser(me.user); setError(""); setBusy(false); } }).catch((cause) => { if (active) { setError(cause instanceof Error ? cause.message : "โหลดคิวงานไม่สำเร็จ"); setBusy(false); } }); return () => { active = false; }; }, []);
  const permitted = (permission: string) => Boolean(user?.permissions.includes(permission));
  async function command(url: string, payload: unknown, success: string) { setError(""); setMessage(""); try { await jsonRequest(url, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); setMessage(success); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "ดำเนินการไม่สำเร็จ"); } }
  async function createNotification(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); await command("/api/maintenance/workflow/notifications", { assetId: data.get("assetId"), title: data.get("title"), description: data.get("description"), symptoms: data.get("symptoms"), operationalImpact: data.get("operationalImpact"), requestedUrgency: data.get("requestedUrgency"), contactPerson: data.get("contactPerson"), contactPhone: data.get("contactPhone"), type: "CORRECTIVE", priority: data.get("priority"), severity: "MODERATE", equipmentOperatingStatus: "UNKNOWN", breakdown: false, photoAttachmentIds: [] }, "บันทึกร่างใบแจ้งแล้ว"); setShowCreate(false); }
  const counts = useMemo(() => ({ mine: queue.workOrders.filter((item) => item.assignedTo === user?.id && !["CLOSED", "CANCELLED"].includes(item.status)).length, review: queue.workOrders.filter((item) => ["TECHNICIAN_COMPLETED", "UNDER_MANAGER_REVIEW"].includes(item.status)).length, acceptance: queue.workOrders.filter((item) => item.status === "WAITING_FOR_OPERATOR_ACCEPTANCE").length, overdue: [...queue.notifications, ...queue.workOrders].filter((item) => item.dueAt && new Date(item.dueAt) < new Date() && !["CLOSED", "CANCELLED"].includes(item.status)).length }), [queue, user]);
  return <PageContainer className="max-w-[92rem]" id="workflow-main">
    <PageHeader eyebrow="Governed maintenance" title="ศูนย์ควบคุมงานซ่อมบำรุง" description="สถานะ ผู้รับผิดชอบ และขั้นตอนถัดไปจากใบแจ้งจนถึงการปิดงาน" />
    <div className="mb-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4" aria-label="สรุปคิวงาน"><Metric icon={Wrench} label="งานที่มอบหมายให้ฉัน" value={counts.mine} /><Metric icon={UserRoundCog} label="รอ Manager ตรวจ" value={counts.review} /><Metric icon={CheckCircle2} label="รอ Operator ยอมรับ" value={counts.acceptance} /><Metric icon={AlertTriangle} label="เกินกำหนด" value={counts.overdue} danger={counts.overdue > 0} /></div>
    <div aria-live="polite">{message && <Alert className="mb-4 border-emerald-200 bg-emerald-50 text-emerald-900">{message}</Alert>}</div><div aria-live="assertive">{error && <Alert className="mb-4 border-red-200 bg-red-50 text-red-900">{error}</Alert>}</div>
    <div className="mb-5 flex flex-wrap items-center justify-between gap-3"><div className="flex rounded-xl border bg-white p-1"><Button variant={tab === "notifications" ? "default" : "ghost"} onClick={() => setTab("notifications")}><ClipboardList className="size-4" />ใบแจ้ง ({queue.notifications.length})</Button><Button variant={tab === "work-orders" ? "default" : "ghost"} onClick={() => setTab("work-orders")}><Wrench className="size-4" />Work Orders ({queue.workOrders.length})</Button></div><div className="flex gap-2">{permitted("NOTIFICATION_CREATE") && <Button onClick={() => setShowCreate((value) => !value)}>สร้างใบแจ้ง</Button>}<Button variant="outline" onClick={() => void load()} disabled={busy}><RefreshCw className={cn("size-4", busy && "animate-spin")} />รีเฟรช</Button></div></div>
    {showCreate && <Card className="mb-5"><CardHeader><CardTitle>สร้างใบแจ้งซ่อม</CardTitle></CardHeader><CardContent><form onSubmit={createNotification} className="grid gap-4 md:grid-cols-2"><Field label="อุปกรณ์"><select name="assetId" required className="rounded-lg border px-3 py-2"><option value="">เลือกอุปกรณ์</option>{queue.assets.map((asset) => <option key={asset.id} value={asset.id}>{asset.code} — {asset.name}</option>)}</select></Field><Field label="ความเร่งด่วน"><select name="priority" className="rounded-lg border px-3 py-2"><option>MEDIUM</option><option>HIGH</option><option>CRITICAL</option><option>LOW</option></select></Field><Field label="หัวข้อ"><input name="title" required minLength={3} className="rounded-lg border px-3 py-2" /></Field><Field label="อาการที่พบ"><input name="symptoms" className="rounded-lg border px-3 py-2" /></Field><Field label="รายละเอียดปัญหา" wide><textarea name="description" required minLength={5} className="min-h-24 rounded-lg border px-3 py-2" /></Field><Field label="ผลกระทบต่อการปฏิบัติงาน"><input name="operationalImpact" className="rounded-lg border px-3 py-2" /></Field><Field label="ผู้ติดต่อ"><input name="contactPerson" className="rounded-lg border px-3 py-2" /></Field><Field label="โทรศัพท์"><input name="contactPhone" className="rounded-lg border px-3 py-2" /></Field><div className="flex gap-2 md:col-span-2"><Button type="submit">บันทึกร่าง</Button><Button type="button" variant="outline" onClick={() => setShowCreate(false)}>ยกเลิก</Button></div></form></CardContent></Card>}
    <div className="grid gap-4">{(tab === "notifications" ? queue.notifications : queue.workOrders).map((item) => <WorkflowCard key={item.id} item={item} kind={tab === "notifications" ? "notification" : "work-order"} currentUser={user} technicians={queue.technicians} permitted={permitted} command={command} />)}{!busy && (tab === "notifications" ? queue.notifications : queue.workOrders).length === 0 && <Card><CardContent className="py-12 text-center text-slate-500">ไม่มีรายการในขอบเขตที่คุณรับผิดชอบ</CardContent></Card>}</div>
  </PageContainer>;
}

function Metric({ icon: Icon, label: text, value, danger }: { icon: typeof Wrench; label: string; value: number; danger?: boolean }) { return <Card className={cn(danger && "border-red-200 bg-red-50")}><CardContent className="flex items-center gap-4 p-4"><div className="rounded-xl bg-slate-900 p-2.5 text-white"><Icon className="size-5" /></div><div><p className="text-xs text-slate-500">{text}</p><strong className="text-2xl tabular-nums">{value}</strong></div></CardContent></Card>; }

function WorkflowCard({ item, kind, currentUser, technicians, permitted, command }: { item: NotificationRow | WorkOrderRow; kind: "notification" | "work-order"; currentUser: CurrentUser | null; technicians: Queue["technicians"]; permitted: (permission: string) => boolean; command: (url: string, payload: unknown, success: string) => Promise<void> }) {
  const [responsibleRole, nextAction] = responsibility[item.status] ?? ["Maintenance", "ตรวจสอบรายการ"]; const overdue = Boolean(item.dueAt && new Date(item.dueAt) < new Date() && !["CLOSED", "CANCELLED"].includes(item.status)); const base = kind === "notification" ? `/api/maintenance/workflow/notifications/${item.id}/commands` : `/api/maintenance/workflow/work-orders/${item.id}/commands`;
  const ask = (text: string) => window.prompt(text)?.trim();
  const techId = () => technicians[0]?.id;
  return <Card className={cn("overflow-hidden", overdue && "border-red-300")}><CardHeader className="border-b bg-slate-50/70 pb-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="mb-1 font-mono text-xs font-bold text-blue-700">{item.code}</p><CardTitle className="text-lg">{item.title}</CardTitle></div><Badge className={statusTone(item.status)}>{label(item.status)}</Badge></div></CardHeader><CardContent className="grid gap-5 p-5 lg:grid-cols-[1fr_auto]"><dl className="grid gap-x-8 gap-y-3 text-sm sm:grid-cols-2 xl:grid-cols-4"><Info label="ผู้รับผิดชอบปัจจุบัน" value={responsibleRole} /><Info label="ขั้นตอนถัดไป" value={nextAction} /><Info label="เวลาในสถานะ" value={age(item.updatedAt)} icon={<Clock3 className="size-3.5" />} /><Info label="กำหนดเสร็จ" value={item.dueAt ? new Date(item.dueAt).toLocaleString("th-TH") : "ยังไม่กำหนด"} danger={overdue} /></dl><div className="flex max-w-lg flex-wrap items-center justify-start gap-2 lg:justify-end" aria-label={`การดำเนินการสำหรับ ${item.code}`}>
    {kind === "notification" && item.status === "DRAFT" && permitted("NOTIFICATION_SUBMIT") && <Button size="sm" onClick={() => void command(`${base}/submit`, { comment: "ส่งใบแจ้งเพื่อพิจารณา" }, "ส่งใบแจ้งแล้ว")}>ส่งใบแจ้ง</Button>}
    {kind === "notification" && item.status === "SUBMITTED" && permitted("NOTIFICATION_REVIEW") && <Button size="sm" onClick={() => void command(`${base}/review`, { action: "START_REVIEW", comment: "เริ่มตรวจสอบ" }, "เริ่มตรวจสอบแล้ว")}>เริ่มตรวจสอบ</Button>}
    {kind === "notification" && item.status === "UNDER_REVIEW" && permitted("NOTIFICATION_APPROVE") && <Button size="sm" onClick={() => void command(`${base}/review`, { action: "APPROVE", comment: "อนุมัติให้ดำเนินงาน" }, "อนุมัติใบแจ้งแล้ว")}>อนุมัติ</Button>}
    {kind === "notification" && item.status === "UNDER_REVIEW" && permitted("NOTIFICATION_REQUEST_INFORMATION") && <Button size="sm" variant="outline" onClick={() => { const comment = ask("ระบุข้อมูลที่ต้องการเพิ่มเติม"); if (comment) void command(`${base}/review`, { action: "REQUEST_INFORMATION", comment }, "ส่งคำขอข้อมูลแล้ว"); }}>ขอข้อมูลเพิ่ม</Button>}
    {kind === "notification" && item.status === "UNDER_REVIEW" && permitted("NOTIFICATION_REJECT") && <Button size="sm" variant="outline" onClick={() => { const comment = ask("ระบุเหตุผลที่ปฏิเสธ"); if (comment) void command(`${base}/review`, { action: "REJECT", comment }, "ปฏิเสธใบแจ้งแล้ว"); }}>ปฏิเสธ</Button>}
    {kind === "notification" && item.status === "NEEDS_INFORMATION" && permitted("NOTIFICATION_SUBMIT") && <Button size="sm" onClick={() => { const response = ask("ระบุข้อมูลเพิ่มเติม"); if (response) void command(`${base}/provide-information`, { response, attachmentIds: [] }, "ส่งข้อมูลเพิ่มเติมแล้ว"); }}>ให้ข้อมูลเพิ่ม</Button>}
    {kind === "notification" && item.status === "APPROVED" && permitted("WORK_ORDER_CREATE") && techId() && <Button size="sm" onClick={() => void command(`${base}/create-work-order`, { technicianId: techId(), instructions: "ตรวจสอบและดำเนินการตามมาตรฐานความปลอดภัย", teamName: "Maintenance" }, "สร้างและมอบหมาย Work Order แล้ว")}>สร้าง Work Order</Button>}
    {kind === "notification" && item.status === "READY_TO_CLOSE" && permitted("NOTIFICATION_CLOSE") && <Button size="sm" onClick={() => void command(`${base}/close`, { comment: "Operator ยืนยันปิดใบแจ้ง" }, "ปิดใบแจ้งแล้ว")}>ปิดใบแจ้ง</Button>}
    {kind === "work-order" && "assignedTo" in item && item.status === "ASSIGNED" && item.assignedTo === currentUser?.id && permitted("WORK_ORDER_ACCEPT_ASSIGNMENT") && <Button size="sm" onClick={() => void command(`${base}/accept-assignment`, { note: "รับทราบการมอบหมาย" }, "รับมอบหมายแล้ว")}>รับมอบหมาย</Button>}
    {kind === "work-order" && "assignedTo" in item && ["TECHNICIAN_ACCEPTED", "RETURNED_TO_TECHNICIAN"].includes(item.status) && item.assignedTo === currentUser?.id && permitted("WORK_ORDER_START") && <Button size="sm" onClick={() => void command(`${base}/start`, { note: item.status === "RETURNED_TO_TECHNICIAN" ? "เริ่มตรวจซ้ำ" : "เริ่มปฏิบัติงาน" }, "เริ่มงานแล้ว")}>เริ่มงาน</Button>}
    {kind === "work-order" && "assignedTo" in item && item.status === "IN_PROGRESS" && item.assignedTo === currentUser?.id && permitted("WORK_ORDER_UPDATE_PROGRESS") && <Button size="sm" variant="outline" onClick={() => { const reason = ask("ระบุเหตุผลที่รออะไหล่"); if (reason) void command(`${base}/wait`, { status: "WAITING_FOR_PARTS", reason }, "บันทึกสถานะรออะไหล่แล้ว"); }}>รออะไหล่</Button>}
    {kind === "work-order" && "assignedTo" in item && ["WAITING_FOR_PARTS", "WAITING_FOR_VENDOR", "WAITING_FOR_ACCESS", "ON_HOLD"].includes(item.status) && item.assignedTo === currentUser?.id && permitted("WORK_ORDER_UPDATE_PROGRESS") && <Button size="sm" onClick={() => void command(`${base}/resume`, { note: "เหตุรอได้รับการแก้ไขแล้ว" }, "กลับมาดำเนินงานแล้ว")}>ดำเนินงานต่อ</Button>}
    {kind === "work-order" && "assignedTo" in item && item.status === "IN_PROGRESS" && item.assignedTo === currentUser?.id && permitted("WORK_ORDER_SUBMIT_COMPLETION") && <Button size="sm" onClick={() => { const summary = ask("สรุปงานและผลการแก้ไข"); if (summary) void command(`${base}/submit-completion`, { diagnosis: summary, rootCauseUnknownReason: "บันทึกสาเหตุโดยละเอียดในสรุปงาน", correctiveAction: summary, workSummary: summary, laborMinutes: 30, partsFinalized: true, noPartsUsed: true, testProcedure: "ทดสอบการทำงานตามสภาวะใช้งาน", testResult: "ผ่าน", beforePhotoAttachmentIds: [], afterPhotoAttachmentIds: [] }, "ส่ง completion revision แล้ว"); }}>ส่งผลการซ่อม</Button>}
    {kind === "work-order" && ["TECHNICIAN_COMPLETED", "UNDER_MANAGER_REVIEW"].includes(item.status) && permitted("WORK_ORDER_APPROVE_COMPLETION") && <Button size="sm" onClick={() => void command(`${base}/manager-decision`, { decision: "APPROVE", comment: "ตรวจหลักฐานและผลทดสอบแล้ว" }, "Manager อนุมัติงานแล้ว")}>อนุมัติผลซ่อม</Button>}
    {kind === "work-order" && ["TECHNICIAN_COMPLETED", "UNDER_MANAGER_REVIEW"].includes(item.status) && permitted("WORK_ORDER_RETURN_FOR_RECHECK") && <Button size="sm" variant="outline" onClick={() => { const comment = ask("ระบุเหตุผลและสิ่งที่ต้องแก้ไข"); if (comment) void command(`${base}/manager-decision`, { decision: "RETURN", comment, requiredActions: [comment] }, "ส่งกลับให้ตรวจซ้ำแล้ว"); }}>ส่งตรวจซ้ำ</Button>}
    {kind === "work-order" && item.status === "OPERATOR_REJECTED" && permitted("WORK_ORDER_RETURN_FOR_RECHECK") && <Button size="sm" onClick={() => { const comment = ask("ระบุคำสั่งตรวจซ้ำ"); if (comment) void command(`${base}/return-operator-rejection`, { decision: "RETURN", comment, requiredActions: [comment] }, "ส่งงานกลับให้ช่างแล้ว"); }}>ส่งกลับให้ช่าง</Button>}
    {kind === "work-order" && item.status === "WAITING_FOR_OPERATOR_ACCEPTANCE" && permitted("NOTIFICATION_ACCEPT_WORK") && <Button size="sm" onClick={() => void command(`${base}/operator-decision`, { decision: "ACCEPT", comment: "ผลการซ่อมเป็นที่ยอมรับ" }, "ยอมรับงานแล้ว")}>ยอมรับงาน</Button>}
    {kind === "work-order" && item.status === "WAITING_FOR_OPERATOR_ACCEPTANCE" && permitted("NOTIFICATION_REJECT_WORK") && <Button size="sm" variant="outline" onClick={() => { const reason = ask("ระบุปัญหาที่ยังพบ"); if (reason) void command(`${base}/operator-decision`, { decision: "REJECT", reason, remainingProblem: reason, attachmentIds: [] }, "ส่งคำขอตรวจซ้ำแล้ว"); }}>ขอตรวจซ้ำ</Button>}
    {kind === "work-order" && item.status === "OPERATOR_ACCEPTED" && permitted("WORK_ORDER_CLOSE") && <Button size="sm" onClick={() => void command(`${base}/close`, { note: "ปิดหลัง Operator ยอมรับงาน" }, "ปิด Work Order แล้ว")}>ปิด Work Order</Button>}
  </div></CardContent></Card>;
}
function Info({ label: term, value, danger, icon }: { label: string; value: string; danger?: boolean; icon?: React.ReactNode }) { return <div><dt className="mb-1 text-xs text-slate-500">{term}</dt><dd className={cn("flex items-center gap-1 font-medium", danger && "text-red-700")}>{icon}{value}</dd></div>; }
function Field({ label: text, children, wide }: { label: string; children: React.ReactNode; wide?: boolean }) { return <label className={cn("grid gap-1 text-sm font-medium", wide && "md:col-span-2")}><span>{text}</span>{children}</label>; }
