"use client";

import { useEffect, useMemo, useState, type FormEvent, type ReactNode } from "react";
import Image from "next/image";
import { BellRing, Boxes, ClipboardCheck, Plus, Wrench } from "lucide-react";
import { PageContainer, PageHeader } from "@/components/shared/page-header";
import { Alert } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { cn } from "@/lib/utils";

type Role = "ADMIN" | "DATA_SOURCE_CREATOR" | "DASHBOARD_CREATOR" | "VIEWER";
type User = { id: string; fullName: string; role: Role };
type Asset = { id: string; code: string; name: string; location: string; criticality: string; status: string; typeName: string; categoryName: string | null };
type Notification = { id: string; code: string; title: string; description: string; type: string; priority: string; severity: string; equipmentOperatingStatus: string; status: string; assetId: string; assetCode: string; assetName: string; photoAttachmentIds: string | null; dueAt: string | null; createdAt: string; requestedByName: string };
type WorkOrder = { id: string; code: string; title: string; description: string; priority: string; severity: string; status: WorkStatus; backlogReason: string | null; notificationId: string; assetId: string; assetCode: string; assetName: string; assignedTo: string | null; dueAt: string | null; startedAt: string | null; verifiedAt: string | null; closedAt: string | null; updatedAt: string };
type WorkStatus = "OPEN" | "BACKLOG" | "IN_PROGRESS" | "COMPLETION_PENDING" | "VERIFIED" | "CLOSED";
type Task = { id: string; sequence: number; title: string; description: string | null; required: boolean; kind: "JOB_STEP" | "CHECKLIST"; status: "OPEN" | "IN_PROGRESS" | "COMPLETED" };
type Completion = { id: string; result: string; solution: string; durationMinutes: number; beforePhotoAttachmentIds: string | null; afterPhotoAttachmentIds: string | null; completedAt: string };
type Event = { id: string; eventType: string; fromStatus: WorkStatus | null; toStatus: WorkStatus | null; note: string | null; createdAt: string };
type Detail = { order: WorkOrder; tasks: Task[]; execution: Array<{ id: string; description: string; minutesSpent: number; overtimeMinutes: number; overtimeMultiplier: string; actionAt: string }>; completions: Completion[]; verifications: Array<{ id: string; decision: string; note: string; verifiedAt: string }>; events: Event[]; usedSpareParts: Array<{ id: string; code: string; name: string; quantity: string; unit: string | null; note: string | null; usedAt: string }> };
type Overview = { assets: Asset[]; notifications: Notification[]; workOrders: WorkOrder[]; users: User[]; assetTypes: Array<{ id: string; code: string; name: string }>; assetCategories: Array<{ id: string; code: string; name: string }>; spareParts: Array<{ id: string; code: string; name: string; unit: string | null }>; departments: Array<{ id: string; code: string; name: string }> };
type CurrentUser = { id: string; fullName: string; role: Role };
type Mutate = (url: string, payload: unknown, success: string, refreshDetailId?: string) => Promise<boolean>;

const emptyOverview: Overview = { assets: [], notifications: [], workOrders: [], users: [], assetTypes: [], assetCategories: [], spareParts: [], departments: [] };
const formatDate = (value: string | null) => value ? new Date(value).toLocaleString([], { dateStyle: "medium", timeStyle: "short" }) : "Not set";
const attachmentIds = (value: string | null) => { try { const ids = JSON.parse(value || "[]"); return Array.isArray(ids) ? ids.filter((id): id is string => typeof id === "string") : []; } catch { return []; } };
const label = (value: string) => value.toLowerCase().replaceAll("_", " ").replace(/(^|\s)\S/g, (letter) => letter.toUpperCase());
const isSupervisor = (role?: Role) => role === "ADMIN" || role === "DATA_SOURCE_CREATOR";
const canExecute = (role?: Role) => role === "ADMIN" || role === "DATA_SOURCE_CREATOR" || role === "DASHBOARD_CREATOR";

async function jsonRequest(url: string, options?: RequestInit) {
  const response = await fetch(url, options); const body = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(body.error || "Request failed");
  return body;
}

async function uploadPhotos(files: File[], entityType: string, entityId: string) {
  return Promise.all(files.map(async (file) => { const form = new FormData(); form.set("file", file); form.set("entityType", entityType); form.set("entityId", entityId); const result = await jsonRequest("/api/attachments/upload", { method: "POST", body: form }); return result.attachment.id as string; }));
}

const dangerValues = new Set(["CRITICAL", "REJECTED", "CANCELLED", "OVERDUE"]);
const warningValues = new Set(["HIGH", "BACKLOG", "COMPLETION_PENDING", "RETURNED", "ON_HOLD"]);
const successValues = new Set(["ACTIVE", "COMPLETED", "VERIFIED", "CLOSED", "APPROVED"]);
function StatusPill({ value }: { value: string }) { return <Badge className={cn("whitespace-nowrap", dangerValues.has(value) && "border-red-200 bg-red-50 text-red-900", warningValues.has(value) && "border-amber-200 bg-amber-50 text-amber-900", successValues.has(value) && "border-emerald-200 bg-emerald-50 text-emerald-900")}>{label(value)}</Badge>; }
function PhotoStrip({ title, ids }: { title: string; ids: string[] }) { if (ids.length === 0) return null; return <div><h4 className="mb-2 text-sm font-bold text-slate-700">{title}</h4><div className="grid grid-cols-2 gap-2 sm:grid-cols-4">{ids.map((id) => <a key={id} href={`/api/attachments/${id}/content`} target="_blank" rel="noreferrer" className="overflow-hidden rounded-lg border border-slate-200"><Image unoptimized width={240} height={240} src={`/api/attachments/${id}/content`} alt={`${title} evidence`} className="aspect-square w-full object-cover" /></a>)}</div></div>; }

function Field({ label: fieldLabel, children, hint }: { label: string; children: ReactNode; hint?: string }) {
  return <label className="maintenance-field"><span>{fieldLabel}</span>{children}{hint && <small>{hint}</small>}</label>;
}

export default function MaintenanceWorkspace() {
  const [overview, setOverview] = useState<Overview>(emptyOverview);
  const [currentUser, setCurrentUser] = useState<CurrentUser | null>(null);
  const [tab, setTab] = useState<"pipeline" | "assets" | "notifications">("pipeline");
  const [detail, setDetail] = useState<Detail | null>(null);
  const [panel, setPanel] = useState<"asset" | "notification" | null>(null);
  const [busy, setBusy] = useState(true);
  const [message, setMessage] = useState("");
  const [error, setError] = useState("");

  async function loadOverview() {
    const [data, me] = await Promise.all([jsonRequest("/api/maintenance/overview"), jsonRequest("/api/auth/me")]);
    setOverview(data); setCurrentUser(me.user); setBusy(false);
  }

  useEffect(() => {
    let active = true;
    Promise.all([jsonRequest("/api/maintenance/overview"), jsonRequest("/api/auth/me")])
      .then(([data, me]) => { if (active) { setOverview(data); setCurrentUser(me.user); setBusy(false); } })
      .catch((reason) => { if (active) { setError(reason.message); setBusy(false); } });
    return () => { active = false; };
  }, []);

  async function loadDetail(id: string) { setError(""); try { setDetail(await jsonRequest(`/api/maintenance/work-orders/${id}`)); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to load work order"); } }
  async function mutate(url: string, payload: unknown, success: string, refreshDetailId?: string) {
    setError(""); setMessage("");
    try { await jsonRequest(url, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); setMessage(success); await loadOverview(); if (refreshDetailId) await loadDetail(refreshDetailId); return true; }
    catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to save changes"); return false; }
  }

  async function createAsset(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); if (await mutate("/api/maintenance/assets", { code: data.get("code"), name: data.get("name"), description: data.get("description"), assetTypeId: data.get("assetTypeId"), assetCategoryId: data.get("assetCategoryId") || null, location: data.get("location"), criticality: data.get("criticality"), status: "ACTIVE", ownerUserId: data.get("ownerUserId") || null }, "Asset created")) setPanel(null); }
  async function createNotification(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const files = data.getAll("photos").filter((value): value is File => value instanceof File && value.size > 0); const draftId = crypto.randomUUID(); setError(""); try { const photoAttachmentIds = await uploadPhotos(files, "MAINTENANCE_NOTIFICATION_DRAFT", draftId); if (await mutate("/api/maintenance/notifications", { assetId: data.get("assetId"), title: data.get("title"), description: data.get("description"), type: data.get("type"), priority: data.get("priority"), severity: data.get("severity"), equipmentOperatingStatus: data.get("equipmentOperatingStatus"), breakdown: data.get("breakdown") === "on", departmentId: data.get("departmentId") || null, assignedPersonId: data.get("assignedPersonId") || null, supervisorId: data.get("supervisorId") || null, photoAttachmentIds, dueAt: data.get("dueAt") ? new Date(String(data.get("dueAt"))).toISOString() : null }, "Maintenance notification reported")) setPanel(null); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to upload photos"); } }

  const counts = useMemo(() => ({ newNotifications: overview.notifications.filter((item) => item.status === "NEW").length, activeWork: overview.workOrders.filter((item) => !["CLOSED", "VERIFIED"].includes(item.status)).length, pendingVerification: overview.workOrders.filter((item) => item.status === "COMPLETION_PENDING").length, closed: overview.workOrders.filter((item) => item.status === "CLOSED").length }), [overview]);
  const pageTitle = tab === "pipeline" ? "Maintenance work pipeline" : tab === "assets" ? "Asset register" : "Maintenance notifications";
  const pageDescription = tab === "pipeline" ? "Move work from reported condition through supervised verification and close." : tab === "assets" ? "Maintain the equipment identity that anchors every request and work order." : "Report, review, and authorize maintenance against an active asset.";
  return <PageContainer className="max-w-[90rem]" id="maintenance-main">
      <PageHeader eyebrow="Controlled maintenance flow" title={pageTitle} description={pageDescription} icon={<Wrench className="size-5" />} actions={<>{canExecute(currentUser?.role) && <Button variant="outline" onClick={() => { setPanel("asset"); setTab("assets"); }}><Boxes className="size-4" />New asset</Button>}<Button onClick={() => { setPanel("notification"); setTab("notifications"); }}><Plus className="size-4" />Report notification</Button></>} />
      <nav className="maintenance-tabs" aria-label="Maintenance workspace">
        <button className={tab === "pipeline" ? "active" : ""} aria-current={tab === "pipeline" ? "page" : undefined} onClick={() => setTab("pipeline")}>Work pipeline</button>
        <button className={tab === "assets" ? "active" : ""} aria-current={tab === "assets" ? "page" : undefined} onClick={() => setTab("assets")}>Asset register</button>
        <button className={tab === "notifications" ? "active" : ""} aria-current={tab === "notifications" ? "page" : undefined} onClick={() => setTab("notifications")}>Notifications</button>
      </nav>
        <div className="grid gap-3" aria-live="polite" aria-atomic="true">{message && <Alert variant="success">{message}</Alert>}{error && <Alert variant="destructive">{error}</Alert>}</div>
        {busy ? <MaintenanceSkeleton /> : <>
          <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4" aria-label="Maintenance summary"><Metric icon={<BellRing className="size-5" />} label="New notifications" value={counts.newNotifications} helper="Awaiting review" /><Metric icon={<Wrench className="size-5" />} label="Active work" value={counts.activeWork} helper="Backlog to completion" /><Metric icon={<ClipboardCheck className="size-5" />} label="Verification queue" value={counts.pendingVerification} helper="Supervisor action" /><Metric icon={<Boxes className="size-5" />} label="Closed" value={counts.closed} helper="Verified records" /></section>
          {panel === "asset" && <AssetForm overview={overview} onSubmit={createAsset} onCancel={() => setPanel(null)} />}
          {panel === "notification" && <NotificationForm overview={overview} onSubmit={createNotification} onCancel={() => setPanel(null)} />}
          {tab === "pipeline" && <Pipeline orders={overview.workOrders} onOpen={loadDetail} detail={detail} role={currentUser?.role} mutate={mutate} spareParts={overview.spareParts} />}
          {tab === "assets" && <AssetRegister assets={overview.assets} />}
          {tab === "notifications" && <NotificationQueue notifications={overview.notifications} users={overview.users} role={currentUser?.role} mutate={mutate} />}
        </>}
  </PageContainer>;
}

function Metric({ icon, label: metricLabel, value, helper }: { icon: ReactNode; label: string; value: number; helper: string }) { return <Card><CardContent className="flex items-start gap-3 p-4"><span className="grid size-10 shrink-0 place-items-center rounded-lg bg-blue-50 text-blue-800">{icon}</span><div><p className="text-sm font-semibold text-slate-600">{metricLabel}</p><strong className="mt-1 block text-2xl font-bold tabular-nums text-slate-950">{value}</strong><small className="text-xs text-slate-500">{helper}</small></div></CardContent></Card>; }

function MaintenanceSkeleton() { return <div className="space-y-4" aria-label="Loading maintenance data"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[1, 2, 3, 4].map((item) => <Skeleton key={item} className="h-28" />)}</div><Skeleton className="h-96" /></div>; }

function AssetForm({ overview, onSubmit, onCancel }: { overview: Overview; onSubmit: (event: FormEvent<HTMLFormElement>) => void; onCancel: () => void }) {
  return <section className="maintenance-form-card" aria-labelledby="asset-form-title"><div><p className="maintenance-eyebrow">ASSET FOUNDATION</p><h2 id="asset-form-title">Register an asset</h2><p>Codes are normalized to uppercase and must be unique.</p></div>{overview.assetTypes.length === 0 ? <Alert variant="destructive">No active asset type exists. Run the maintenance seed after applying the migration.</Alert> : <form onSubmit={onSubmit}><div className="maintenance-form-grid"><Field label="Asset code"><input name="code" required minLength={2} maxLength={60} /></Field><Field label="Asset name"><input name="name" required minLength={2} maxLength={160} /></Field><Field label="Type"><select name="assetTypeId" required><option value="">Select type</option>{overview.assetTypes.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Category"><select name="assetCategoryId"><option value="">No category</option>{overview.assetCategories.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Location"><input name="location" required minLength={2} maxLength={190} /></Field><Field label="Criticality"><select name="criticality" defaultValue="MEDIUM"><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>CRITICAL</option></select></Field><Field label="Owner"><select name="ownerUserId"><option value="">Unassigned</option>{overview.users.map((item) => <option key={item.id} value={item.id}>{item.fullName}</option>)}</select></Field><Field label="Description"><textarea name="description" rows={3} maxLength={4000} /></Field></div><div className="maintenance-form-actions"><Button type="button" variant="outline" onClick={onCancel}>Cancel</Button><Button type="submit">Create asset</Button></div></form>}</section>;
}

function NotificationForm({ overview, onSubmit, onCancel }: { overview: Overview; onSubmit: (event: FormEvent<HTMLFormElement>) => void; onCancel: () => void }) {
  return <section className="maintenance-form-card" aria-labelledby="notification-form-title"><div><p className="maintenance-eyebrow">REPORT CONDITION</p><h2 id="notification-form-title">New corrective maintenance notification</h2><p>Capture the operating condition and evidence before supervisor review.</p></div>{overview.assets.length === 0 ? <Alert variant="destructive">Register an active asset before reporting a notification.</Alert> : <form onSubmit={onSubmit}><div className="maintenance-form-grid"><Field label="Asset"><select name="assetId" required><option value="">Select asset</option>{overview.assets.filter((item) => item.status === "ACTIVE").map((item) => <option key={item.id} value={item.id}>{item.code} — {item.name}</option>)}</select></Field><Field label="Subject"><input name="title" required minLength={3} maxLength={190} /></Field><Field label="Type"><select name="type" defaultValue="CORRECTIVE"><option>CORRECTIVE</option><option>BREAKDOWN</option><option>INSPECTION</option></select></Field><Field label="Priority"><select name="priority" defaultValue="MEDIUM"><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>CRITICAL</option></select></Field><Field label="Severity"><select name="severity" defaultValue="MODERATE"><option>MINOR</option><option>MODERATE</option><option>MAJOR</option><option>CRITICAL</option></select></Field><Field label="Equipment operating status"><select name="equipmentOperatingStatus" defaultValue="UNKNOWN"><option>RUNNING</option><option>STOPPED</option><option>DEGRADED</option><option>UNKNOWN</option></select></Field><Field label="Department ID" hint="Legacy department reference; optional during staged migration"><input name="departmentId" type="text" /></Field><Field label="Assigned person"><select name="assignedPersonId"><option value="">Assign during review</option>{overview.users.map((item) => <option key={item.id} value={item.id}>{item.fullName}</option>)}</select></Field><Field label="Supervisor"><select name="supervisorId"><option value="">Assign during review</option>{overview.users.filter((item) => isSupervisor(item.role)).map((item) => <option key={item.id} value={item.id}>{item.fullName}</option>)}</select></Field><Field label="Requested due date"><input name="dueAt" type="datetime-local" /></Field><Field label="Photo attachments" hint="JPEG, PNG, or WebP; maximum 5 MB each"><input name="photos" type="file" accept="image/jpeg,image/png,image/webp" multiple /></Field><Field label="Description"><textarea name="description" required minLength={5} maxLength={8000} rows={4} /></Field><label className="maintenance-check"><input name="breakdown" type="checkbox" /> Equipment failure / breakdown</label></div><div className="maintenance-form-actions"><Button type="button" variant="outline" onClick={onCancel}>Cancel</Button><Button type="submit">Submit notification</Button></div></form>}</section>;
}

function AssetRegister({ assets: rows }: { assets: Asset[] }) { return <section className="maintenance-card"><div className="maintenance-card-head"><div><h2>Assets</h2><p>{rows.length} registered assets</p></div></div><div className="maintenance-table-wrap"><table className="maintenance-table"><thead><tr><th>Asset</th><th>Type</th><th>Location</th><th>Criticality</th><th>Status</th></tr></thead><tbody>{rows.map((asset) => <tr key={asset.id}><td><strong>{asset.code}</strong><small>{asset.name}</small></td><td>{asset.typeName}<small>{asset.categoryName || "Uncategorized"}</small></td><td>{asset.location}</td><td><StatusPill value={asset.criticality} /></td><td><StatusPill value={asset.status} /></td></tr>)}</tbody></table>{rows.length === 0 && <p className="maintenance-empty">No assets registered yet.</p>}</div></section>; }

function NotificationQueue({ notifications, users, role, mutate }: { notifications: Notification[]; users: User[]; role?: Role; mutate: Mutate }) {
  return <section className="maintenance-card"><div className="maintenance-card-head"><div><h2>Notification review queue</h2><p>One immutable review decision per notification</p></div></div><div className="maintenance-list">{notifications.map((item) => <article className="notification-row" key={item.id}><div className="notification-code"><strong>{item.code}</strong><StatusPill value={item.status} /></div><div><h3>{item.title}</h3><p>{item.assetCode} · {item.assetName} · Reported by {item.requestedByName}</p><small>{item.description}</small><div className="mt-2 flex flex-wrap gap-2"><StatusPill value={item.priority} /><StatusPill value={item.severity} /><StatusPill value={item.equipmentOperatingStatus} /></div></div>{item.status === "NEW" && isSupervisor(role) ? <ReviewForm item={item} users={users} mutate={mutate} /> : <div className="notification-meta"><time>{formatDate(item.dueAt)}</time></div>}</article>)}{notifications.length === 0 && <p className="maintenance-empty">No notifications reported yet.</p>}</div></section>;
}

function ReviewForm({ item, users, mutate }: { item: Notification; users: User[]; mutate: Mutate }) {
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const due = data.get("dueAt"); await mutate(`/api/maintenance/notifications/${item.id}/review`, { decision: data.get("decision"), note: data.get("note"), backlogReason: data.get("backlogReason"), assignedTo: data.get("assignedTo") || null, dueAt: due ? new Date(String(due)).toISOString() : null }, `${item.code} reviewed and converted`); }
  return <form className="review-form" onSubmit={submit}><Field label="Decision"><select name="decision" defaultValue="APPROVED"><option>APPROVED</option><option>BACKLOG</option><option>REJECTED</option></select></Field><Field label="Technician"><select name="assignedTo"><option value="">Not required for rejection</option>{users.filter((user) => canExecute(user.role)).map((user) => <option key={user.id} value={user.id}>{user.fullName}</option>)}</select></Field><Field label="Due"><input name="dueAt" type="datetime-local" /></Field><Field label="Review / rejection note"><input name="note" required minLength={3} maxLength={4000} /></Field><Field label="Backlog reason" hint="Required when the decision is Backlog"><input name="backlogReason" maxLength={4000} /></Field><Button type="submit">Review &amp; convert</Button></form>;
}

function Pipeline({ orders, onOpen, detail, role, mutate, spareParts: parts }: { orders: WorkOrder[]; onOpen: (id: string) => void; detail: Detail | null; role?: Role; mutate: Mutate; spareParts: Overview["spareParts"] }) {
  return <div className="pipeline-grid"><section className="maintenance-card"><div className="maintenance-card-head"><div><h2>Work orders</h2><p>Select a record to manage execution</p></div></div><div className="work-order-list">{orders.map((order) => <button key={order.id} className={detail?.order.id === order.id ? "selected" : ""} onClick={() => onOpen(order.id)}><span><strong>{order.code}</strong><small>{order.assetCode} · {order.assetName}</small></span><span><StatusPill value={order.status} /><small>{formatDate(order.updatedAt)}</small></span></button>)}{orders.length === 0 && <p className="maintenance-empty">Approved notifications will create work orders here.</p>}</div></section>{detail ? <WorkOrderDetail detail={detail} role={role} mutate={mutate} spareParts={parts} /> : <section className="maintenance-card maintenance-detail-empty"><span>01 → 02 → 03</span><h2>Select a work order</h2><p>Tasks, execution, completion, verification, and closure stay together in one auditable record.</p></section>}</div>;
}

function WorkOrderDetail({ detail, role, mutate, spareParts: parts }: { detail: Detail; role?: Role; mutate: Mutate; spareParts: Overview["spareParts"] }) {
  const { order } = detail; const endpoint = `/api/maintenance/work-orders/${order.id}`; const latestCompletion = detail.completions[0];
  const action = (name: string, payload: unknown, message: string) => mutate(`${endpoint}/${name}`, payload, message, order.id);
  return <section className="maintenance-card work-detail"><div className="work-detail-head"><div><p className="maintenance-eyebrow">{order.assetCode} · {order.assetName}</p><h2>{order.code}</h2><p>{order.title}</p></div><StatusPill value={order.status} /></div><div className="workflow-rail" aria-label="Work order progress">{["OPEN", "IN_PROGRESS", "COMPLETION_PENDING", "VERIFIED", "CLOSED"].map((step, index) => <div key={step} className={step === order.status || (["BACKLOG"].includes(order.status) && step === "OPEN") ? "current" : ""}><span>{index + 1}</span><small>{label(step)}</small></div>)}</div>
    {(order.status === "OPEN" || order.status === "BACKLOG") && canExecute(role) && <div className="maintenance-action-strip"><p>Work is authorized and ready for the assignee.</p><Button onClick={() => action("start", {}, `${order.code} started`)}>Start work</Button></div>}
    <section className="work-section"><div className="work-section-title"><div><h3>Job steps &amp; checklist</h3><p>Every required item must be complete before submission.</p></div></div><div className="task-list">{detail.tasks.map((task) => <article key={task.id}><span className="task-number">{task.sequence}</span><div><strong>{task.title}</strong><small>{label(task.kind)} · {task.required ? "Required" : "Optional"}{task.description ? ` · ${task.description}` : ""}</small></div><StatusPill value={task.status} />{canExecute(role) && ["OPEN", "BACKLOG", "IN_PROGRESS"].includes(order.status) && task.status !== "COMPLETED" && <button className="secondary-button" onClick={() => action("task-status", { taskId: task.id, status: "COMPLETED" }, "Task completed")}>Complete</button>}</article>)}{detail.tasks.length === 0 && <p className="maintenance-empty">No steps added. Legacy behavior permits completion with no tasks.</p>}</div>{canExecute(role) && ["OPEN", "BACKLOG", "IN_PROGRESS"].includes(order.status) && <CompactForm legend="Add job item" fields={<><Field label="Type"><select name="kind"><option>JOB_STEP</option><option>CHECKLIST</option></select></Field><Field label="Title"><input name="title" required minLength={2} /></Field><Field label="Description"><input name="description" maxLength={4000} /></Field><label className="maintenance-check"><input name="required" type="checkbox" defaultChecked /> Required item</label></>} onSubmit={(data) => action("tasks", { title: data.get("title"), description: data.get("description"), kind: data.get("kind"), required: data.get("required") === "on" }, "Job item added")} submitLabel="Add item" />}</section>
    {order.status === "IN_PROGRESS" && canExecute(role) && <><section className="work-section"><h3>Work notes &amp; man-hour</h3>{detail.execution.map((entry) => <article className="execution-entry" key={entry.id}><strong>{entry.minutesSpent} min</strong><span>{entry.description}{entry.overtimeMinutes > 0 ? ` · OT ${entry.overtimeMinutes} min × ${entry.overtimeMultiplier}` : ""}</span><time>{formatDate(entry.actionAt)}</time></article>)}<CompactForm legend="Record work" fields={<><Field label="Work note"><input name="description" required minLength={3} /></Field><Field label="Regular minutes"><input name="minutesSpent" type="number" min={1} max={1440} required /></Field><Field label="Overtime minutes"><input name="overtimeMinutes" type="number" min={0} max={1440} defaultValue={0} /></Field><Field label="OT multiplier"><select name="overtimeMultiplier" defaultValue="1"><option value="1">Normal</option><option value="1.5">1.5×</option><option value="2">2×</option><option value="3">3×</option></select></Field><Field label="Action time"><input name="actionAt" type="datetime-local" required defaultValue={new Date().toISOString().slice(0, 16)} /></Field></>} onSubmit={(data) => action("execution", { description: data.get("description"), minutesSpent: Number(data.get("minutesSpent")), overtimeMinutes: Number(data.get("overtimeMinutes")), overtimeMultiplier: Number(data.get("overtimeMultiplier")), actionAt: new Date(String(data.get("actionAt"))).toISOString() }, "Execution recorded")} submitLabel="Record work" /></section><section className="work-section"><h3>Used spare parts</h3>{detail.usedSpareParts.map((part) => <article className="execution-entry" key={part.id}><strong>{part.quantity} {part.unit || "unit"}</strong><span>{part.code} — {part.name}</span><time>{formatDate(part.usedAt)}</time></article>)}{parts.length > 0 && <CompactForm legend="Record spare usage" fields={<><Field label="Spare part"><select name="sparePartId" required><option value="">Select spare part</option>{parts.map((part) => <option key={part.id} value={part.id}>{part.code} — {part.name}</option>)}</select></Field><Field label="Quantity"><input name="quantity" type="number" min="0.0001" step="0.0001" required /></Field><Field label="Note"><input name="note" maxLength={4000} /></Field></>} onSubmit={(data) => action("spare-parts", { sparePartId: data.get("sparePartId"), quantity: Number(data.get("quantity")), note: data.get("note") }, "Spare usage recorded")} submitLabel="Add spare part" />}</section><CompletionForm workOrderId={order.id} submit={(payload) => action("completion", payload, "Completion submitted for supervisor verification")} /></>}
    {latestCompletion && <section className="work-section"><h3>Completion evidence</h3><div className="grid gap-4 sm:grid-cols-2"><PhotoStrip title="Before" ids={attachmentIds(latestCompletion.beforePhotoAttachmentIds)} /><PhotoStrip title="After" ids={attachmentIds(latestCompletion.afterPhotoAttachmentIds)} /></div></section>}
    {order.status === "COMPLETION_PENDING" && isSupervisor(role) && latestCompletion && <VerificationForm completion={latestCompletion} submit={(payload) => action("verification", payload, "Supervisor decision recorded")} />}
    {order.status === "VERIFIED" && isSupervisor(role) && <CompactForm legend="Close verified work" fields={<Field label="Closure note"><input name="note" required minLength={3} maxLength={4000} /></Field>} onSubmit={(data) => action("close", { note: data.get("note") }, `${order.code} closed`)} submitLabel="Close work order" />}
    <section className="work-section"><h3>Audit timeline</h3><ol className="event-timeline">{detail.events.map((event) => <li key={event.id}><span /><div><strong>{label(event.eventType)}</strong><small>{event.note || `${event.fromStatus ? label(event.fromStatus) : "Created"} → ${event.toStatus ? label(event.toStatus) : "Recorded"}`}</small></div><time>{formatDate(event.createdAt)}</time></li>)}</ol></section>
  </section>;
}

function CompactForm({ legend, fields, onSubmit, submitLabel }: { legend: string; fields: ReactNode; onSubmit: (data: FormData) => Promise<unknown>; submitLabel: string }) { async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); await onSubmit(new FormData(event.currentTarget)); } return <form className="compact-form" onSubmit={submit}><fieldset><legend>{legend}</legend><div>{fields}<Button type="submit">{submitLabel}</Button></div></fieldset></form>; }

function CompletionForm({ workOrderId, submit }: { workOrderId: string; submit: (payload: unknown) => Promise<unknown> }) {
  async function complete(data: FormData) { const before = data.getAll("beforePhotos").filter((value): value is File => value instanceof File && value.size > 0); const after = data.getAll("afterPhotos").filter((value): value is File => value instanceof File && value.size > 0); const [beforePhotoAttachmentIds, afterPhotoAttachmentIds] = await Promise.all([uploadPhotos(before, "WORK_ORDER_BEFORE", workOrderId), uploadPhotos(after, "WORK_ORDER_AFTER", workOrderId)]); return submit({ result: data.get("result"), problem: data.get("problem"), cause: data.get("cause"), solution: data.get("solution"), escalation: data.get("escalation"), notes: data.get("notes"), durationMinutes: Number(data.get("durationMinutes")), beforePhotoAttachmentIds, afterPhotoAttachmentIds }); }
  return <section className="work-section"><CompactForm legend="Completion record" fields={<><Field label="Result"><input name="result" required minLength={2} maxLength={190} /></Field><Field label="Problem"><input name="problem" maxLength={8000} /></Field><Field label="Cause"><input name="cause" maxLength={8000} /></Field><Field label="Solution"><textarea name="solution" required minLength={3} maxLength={8000} rows={3} /></Field><Field label="Escalation"><input name="escalation" maxLength={8000} /></Field><Field label="Completion notes"><textarea name="notes" maxLength={8000} rows={2} /></Field><Field label="Duration (minutes)"><input name="durationMinutes" type="number" required min={1} max={525600} /></Field><Field label="Before photos"><input name="beforePhotos" type="file" accept="image/jpeg,image/png,image/webp" multiple /></Field><Field label="After photos"><input name="afterPhotos" type="file" accept="image/jpeg,image/png,image/webp" multiple /></Field></>} onSubmit={complete} submitLabel="Submit for verification" /></section>;
}

function VerificationForm({ completion, submit }: { completion: Completion; submit: (payload: unknown) => Promise<unknown> }) { return <section className="work-section supervisor-panel"><p className="maintenance-eyebrow">SUPERVISOR GATE</p><h3>Verify completion</h3><dl><div><dt>Result</dt><dd>{completion.result}</dd></div><div><dt>Solution</dt><dd>{completion.solution}</dd></div><div><dt>Duration</dt><dd>{completion.durationMinutes} minutes</dd></div></dl><CompactForm legend="Supervisor decision" fields={<><Field label="Decision"><select name="decision"><option>VERIFIED</option><option>RETURNED</option></select></Field><Field label="Verification note"><input name="note" required minLength={3} maxLength={4000} /></Field></>} onSubmit={(data) => submit({ completionId: completion.id, decision: data.get("decision"), note: data.get("note") })} submitLabel="Record decision" /></section>; }
