"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { AssetCombobox } from "@/components/shared/asset-combobox";

type Item = { id: string; code?: string; name: string; description?: string; status?: string; kind?: string; phase?: string; parentId?: string; version: number; progress?: string; plannedStartAt?: string; plannedFinishAt?: string; workOrderId?: string; woCode?: string; reason?: string };
type Ref = { sites: { id: string; name: string; organizationId: string }[]; departments: { id: string; name: string; siteId: string | null }[]; users: { id: string; fullName: string }[]; canManage: boolean; canGenerate: boolean; isAdmin: boolean };
type Data = { items?: Item[]; templates?: Item[]; project?: Item; program?: Item; tasks?: Item[]; dates?: string[]; occurrences?: { id: string; scheduledDate: string; status: string; workOrderId?: string }[]; events?: { id: string; eventType: string; note: string }[] };
type Field = { name: string; label: string; type?: string; options?: { value: string; label: string }[]; optional?: boolean; value?: string };
async function request(path: string, body?: unknown) {
  const response = await fetch(`/api/planning/${path}`, body ? { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) } : undefined);
  const data = await response.json(); if (!response.ok) throw new Error(data.error || "Unable to complete request"); return data;
}

function Editor({ title, fields, submit, withSteps = false }: { title: string; fields: Field[]; submit: (v: Record<string, unknown>) => Promise<void>; withSteps?: boolean }) {
  const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [asset, setAsset] = useState("");
  return <details className="rounded-xl border bg-white p-5"><summary className="cursor-pointer text-lg font-semibold">{title}</summary><form className="mt-5 grid gap-4 sm:grid-cols-2" onSubmit={async e => {
    e.preventDefault(); const form = e.currentTarget; const v: Record<string, unknown> = Object.fromEntries(new FormData(form));
    for (const field of fields) { if (field.type === "asset") v[field.name] = asset; if (field.type === "datetime-local" && v[field.name]) v[field.name] = new Date(String(v[field.name])).toISOString(); if (field.type === "number") v[field.name] = Number(v[field.name]); if (field.optional && !v[field.name]) delete v[field.name]; }
    if (withSteps) { v.steps = String(v.stepLines ?? "").split("\n").map(s => s.trim()).filter(Boolean).map(title => ({ title, required: true, kind: "JOB_STEP", description: "" })); delete v.stepLines; }
    setBusy(true); setError(""); try { await submit(v); form.reset(); setAsset(""); } catch (e) { setError(e instanceof Error ? e.message : "Unable to save"); } finally { setBusy(false); }
  }}>
    {fields.map(field => <label key={field.name} className="space-y-1 text-sm font-medium"><span>{field.label}{!field.optional && " *"}</span>{field.type === "asset" ? <AssetCombobox value={asset} onValueChange={setAsset} /> : field.options ? <select name={field.name} required={!field.optional} className="wo-input" defaultValue={field.value ?? ""}><option value="">เลือก</option>{field.options.map(o => <option key={o.value} value={o.value}>{o.label}</option>)}</select> : field.type === "textarea" ? <Textarea name={field.name} required={!field.optional} defaultValue={field.value} /> : <Input name={field.name} type={field.type ?? "text"} required={!field.optional} defaultValue={field.value} />}</label>)}
    {withSteps && <label className="space-y-1 text-sm font-medium sm:col-span-2">ขั้นตอนงานที่ต้องทำ (หนึ่งขั้นตอนต่อบรรทัด)<Textarea name="stepLines" rows={4} /></label>}
    {error && <p role="alert" className="text-red-700 sm:col-span-2">{error}</p>}<div className="sm:col-span-2"><Button disabled={busy}>{busy ? "กำลังบันทึก…" : "บันทึก"}</Button></div>
  </form></details>;
}

export default function PlanningWorkspace({ area, id }: { area: "projects" | "programs"; id?: string }) {
  const [data, setData] = useState<Data>({}); const [refs, setRefs] = useState<Ref>(); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [loaded, setLoaded] = useState(false); const [note, setNote] = useState(""); const [view, setView] = useState("list"); const [preview, setPreview] = useState<{ task: Item; errors: string[] }>(); const [catchUp, setCatchUp] = useState(false); const [result, setResult] = useState("");
  const [previewRange, setPreviewRange] = useState("");
  const reload = useCallback(async () => { const [next, references] = await Promise.all([request(`${area}${id ? `/${id}` : ""}${area === "programs" && id && previewRange ? `?${previewRange}` : ""}`), request(`references?area=${area}`)]); setData(next); setRefs(references); setError(""); setLoaded(true); }, [area, id, previewRange]);
  useEffect(() => { let alive = true; Promise.all([request(`${area}${id ? `/${id}` : ""}${area === "programs" && id && previewRange ? `?${previewRange}` : ""}`), request(`references?area=${area}`)]).then(([next, references]) => { if (alive) { setData(next); setRefs(references); setError(""); setLoaded(true); } }).catch(e => { if (alive) { setError(e.message); setLoaded(true); } }); return () => { alive = false; }; }, [area, id, previewRange]);
  async function mutate(path: string, v: unknown) { setBusy(true); setError(""); try { const response = await request(path, v); await reload(); return response; } catch (e) { setError(e instanceof Error ? e.message : "Request failed"); throw e; } finally { setBusy(false); } }
  function command(path: string, version: number) { void mutate(path, { version, note }).catch(() => {}); }
  const options = (items: readonly string[]) => items.map(value => ({ value, label: value }));
  const people = refs?.users.map(u => ({ value: u.id, label: u.fullName })) ?? [];
  const scopeFields: Field[] = [{ name: "siteId", label: "Site", options: refs?.sites.map(s => ({ value: s.id, label: s.name })) ?? [] }, { name: "departmentId", label: "Department", optional: true, options: refs?.departments.map(d => ({ value: d.id, label: d.name })) ?? [] }];
  const withScope = (v: Record<string, unknown>): Record<string, unknown> => ({ ...v, organizationId: refs?.sites.find(s => s.id === v.siteId)?.organizationId });
  const dateFields: Field[] = [{ name: "plannedStartAt", label: "เริ่มตามแผน", type: "datetime-local" }, { name: "plannedFinishAt", label: "เสร็จตามแผน", type: "datetime-local" }];
  const commonFields: Field[] = [{ name: "name", label: "ชื่อ" }, { name: "description", label: "รายละเอียด", type: "textarea" }];
  const current = data.project ?? data.program;
  return <main className="mx-auto max-w-7xl space-y-6 p-4 md:p-6">
    <header className="space-y-2"><div className="flex gap-4 text-sm text-blue-700"><Link href="/projects">Shutdown Projects</Link><Link href="/preventive-maintenance/programs">Preventive Maintenance</Link></div><h1 className="text-2xl font-bold">{current?.name ?? (area === "projects" ? "Shutdown Project Management" : "Preventive Maintenance")}</h1><p className="text-sm text-slate-600">{area === "projects" ? "วางแผนงาน • Convert Task เป็น WO • ติดตามผลปิดงานกลับโปรเจกต์" : "สร้าง Template และแผนรอบบำรุงรักษา พร้อมตรวจวันและสร้าง Work Order"}</p></header>
    {error && <p role="alert" className="rounded-lg border border-red-200 bg-red-50 p-4 text-red-700">{error}</p>}{!loaded && <p role="status">กำลังโหลด…</p>}
    {current && <section className="rounded-xl border bg-white p-5"><div className="flex flex-wrap gap-4"><span className="font-semibold">{current.status}</span>{current.progress != null && <span>ความคืบหน้า {current.progress}%</span>}<span className="text-slate-500">{current.code}</span></div>{current.progress != null && <progress aria-label="Project progress" className="mt-3 w-full" value={Number(current.progress)} max={100} />}</section>}
    {current && (refs?.canManage || (area === "programs" && refs?.canGenerate)) && <label className="block max-w-2xl space-y-1 text-sm font-medium">เหตุผลสำหรับคำสั่ง / บันทึกการดำเนินการ<Input value={note} onChange={e => setNote(e.target.value)} placeholder="ระบุเหตุผลอย่างน้อย 3 ตัวอักษร" /></label>}
    {current && refs?.canManage && <div className="flex flex-wrap gap-2">{(area === "projects" ? ({ DRAFT: ["plan", "cancel"], PLANNED: ["start", "hold", "replan"], IN_PROGRESS: ["hold"], ON_HOLD: ["resume"], COMPLETED: ["close", "replan"] } as Record<string, string[]>)[current.status ?? ""] ?? [] : current.status === "ACTIVE" ? ["pause"] : ["activate"]).map(c => <Button key={c} disabled={busy || note.trim().length < 3} variant="outline" onClick={() => command(`${area}/${id}/${c}`, current.version)}>{c}</Button>)}</div>}
    {!id && refs?.canManage && area === "projects" && <Editor title="สร้าง Shutdown Project" fields={[...scopeFields, { name: "code", label: "รหัสโครงการ" }, ...commonFields, { name: "ownerId", label: "Owner", options: people }, { name: "operatorId", label: "ผู้ตรวจรับงาน", options: people }, ...dateFields]} submit={async v => { await mutate("projects", withScope(v)); }} />}
    {!id && refs?.canManage && area === "programs" && <><Editor title="สร้าง PM Template" withSteps fields={[...scopeFields, { name: "name", label: "ชื่อ Template" }]} submit={async v => { await mutate("templates", withScope(v)); }} /><Editor title="สร้าง PM Program" fields={[...scopeFields, { name: "name", label: "ชื่อแผน PM" }, { name: "priority", label: "Priority", options: options(["LOW", "MEDIUM", "HIGH", "CRITICAL"]), value: "MEDIUM" }, { name: "estimatedMinutes", label: "เวลาประมาณการ (นาที)", type: "number", value: "60" }, { name: "assetId", label: "Asset", type: "asset" }, { name: "templateId", label: "Template", options: data.templates?.map(t => ({ value: t.id, label: t.name })) ?? [] }, { name: "assignedTo", label: "ช่างผู้รับผิดชอบ", options: people }, { name: "operatorId", label: "ผู้ตรวจรับงาน", options: people }, { name: "startDate", label: "วันเริ่ม", type: "date" }, { name: "expiryDate", label: "วันสิ้นสุด", type: "date" }, { name: "frequency", label: "หน่วยรอบ", options: options(["DAY", "WEEK", "MONTH"]) }, { name: "interval", label: "ทุกกี่หน่วย", type: "number", value: "1" }, { name: "timezone", label: "Timezone", value: "Asia/Bangkok" }, { name: "localTime", label: "เวลาในพื้นที่", type: "time", value: "08:00" }, { name: "leadTimeDays", label: "สร้างล่วงหน้า (วัน)", type: "number", value: "7" }]} submit={async v => { await mutate("programs", withScope(v)); }} /></>}
    {refs?.isAdmin && !id && <Editor title="กำหนดขอบเขต Asset ก่อนวางแผน" fields={[...scopeFields, { name: "assetId", label: "Asset", type: "asset" }]} submit={async v => { const { assetId, ...scope } = withScope(v); await mutate(`assets/${assetId}/scope`, scope); }} />}
    {id && area === "projects" && refs?.canManage && ["DRAFT", "PLANNED"].includes(current?.status ?? "") && <Editor title="เพิ่ม Task หรือ Milestone" withSteps fields={[...commonFields, { name: "kind", label: "ชนิดงาน", options: options(["EXECUTION", "SUMMARY", "MILESTONE"]) }, { name: "phase", label: "ช่วงงาน", options: options(["PREPARATION", "SHUTDOWN", "RESTORATION"]) }, { name: "parentId", label: "กลุ่มงานแม่", optional: true, options: data.tasks?.filter(t => t.kind === "SUMMARY").map(t => ({ value: t.id, label: t.name })) ?? [] }, { name: "assetId", label: "Asset", type: "asset", optional: true }, { name: "assignedTo", label: "ผู้รับผิดชอบ", options: people, optional: true }, ...dateFields, { name: "estimatedMinutes", label: "เวลาประมาณการ (นาที)", type: "number", value: "60" }]} submit={async v => { await mutate(`projects/${id}/tasks`, v); }} />}
    {!id && <section aria-label={area === "projects" ? "Project list" : "PM program list"} className="rounded-xl border bg-white">
      <div className="divide-y sm:hidden">{data.items?.map(p => <article key={p.id} className="space-y-2 p-4"><Link className="block break-words font-semibold text-blue-700" href={area === "projects" ? `/projects/${p.id}` : `/preventive-maintenance/programs/${p.id}`}>{p.code} {p.name}</Link><div className="flex flex-wrap gap-x-4 gap-y-1 text-sm"><span>สถานะ: {p.status}</span>{p.progress != null && <span>ความคืบหน้า: {p.progress}%</span>}</div></article>)}</div>
      <div className="hidden overflow-x-auto sm:block"><table className="w-full text-left text-sm"><thead className="bg-slate-50"><tr><th scope="col" className="p-4">ชื่อ / รหัส</th><th scope="col" className="p-4">สถานะ</th>{area === "projects" && <th scope="col" className="p-4">ความคืบหน้า</th>}</tr></thead><tbody>{data.items?.map(p => <tr key={p.id} className="border-t"><td className="p-4"><Link className="font-semibold text-blue-700" href={area === "projects" ? `/projects/${p.id}` : `/preventive-maintenance/programs/${p.id}`}>{p.code} {p.name}</Link></td><td className="p-4">{p.status}</td>{area === "projects" && <td className="p-4">{p.progress != null ? `${p.progress}%` : "—"}</td>}</tr>)}</tbody></table></div>
      {loaded && !data.items?.length && <p className="p-6 text-slate-500">ยังไม่มีรายการในขอบเขตที่คุณเข้าถึงได้</p>}
    </section>}
    {data.tasks && <><div className="flex gap-2" role="group" aria-label="Task view">{["list", "board", "gantt"].map(v => <Button key={v} variant={view === v ? "default" : "outline"} onClick={() => setView(v)}>{v}</Button>)}</div><div className={view === "board" ? "grid gap-3 md:grid-cols-3" : "space-y-3"}>{data.tasks.map(t => <article key={t.id} className="rounded-xl border bg-white p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">{t.parentId ? "↳ " : ""}{t.name}</h2><p className="text-sm text-slate-500">{t.kind} · {t.phase} · {t.status}</p></div><div className="flex flex-wrap gap-2">{t.workOrderId ? <Button asChild variant="outline"><Link href={`/work-orders/${t.workOrderId}`}>{t.woCode || "Open Work Order"}</Link></Button> : refs?.canManage && <>{t.status === "DRAFT" && t.kind !== "SUMMARY" && <Button disabled={busy || note.length < 3} onClick={() => command(`tasks/${t.id}/ready`, t.version)}>Ready</Button>}{t.status === "READY" && t.kind === "EXECUTION" && <Button disabled={busy || note.length < 3} onClick={() => { void mutate(`tasks/${t.id}/preview`, { version: t.version, note }).then(r => setPreview(r)).catch(() => {}); }}>Preview WO</Button>}{t.status === "READY" && t.kind === "MILESTONE" && <Button disabled={busy || note.length < 3} onClick={() => command(`tasks/${t.id}/complete-milestone`, t.version)}>ยืนยัน Milestone</Button>}</>}</div></div>{view === "gantt" && t.plannedStartAt && t.plannedFinishAt && <div className="mt-3"><p className="text-xs">{new Date(t.plannedStartAt).toLocaleString()} → {new Date(t.plannedFinishAt).toLocaleString()}</p><div className="mt-2 h-3 rounded bg-slate-100"><div className="h-3 rounded bg-blue-500" style={{ marginLeft: `${Math.max(0, Math.min(95, (+new Date(t.plannedStartAt) - +new Date(current!.plannedStartAt!)) / Math.max(1, +new Date(current!.plannedFinishAt!) - +new Date(current!.plannedStartAt!)) * 100))}%`, width: `${Math.max(1, Math.min(100, (+new Date(t.plannedFinishAt) - +new Date(t.plannedStartAt)) / Math.max(1, +new Date(current!.plannedFinishAt!) - +new Date(current!.plannedStartAt!)) * 100))}%` }} /></div></div>}</article>)}</div></>}
    {preview?.task && <section className="rounded-xl border-2 border-blue-300 bg-blue-50 p-5" aria-label="Conversion preview"><h2 className="font-semibold">Preview WO: {preview.task.name}</h2><p>{preview.task.description}</p>{preview.errors.map(e => <p className="text-red-700" key={e}>{e}</p>)}<div className="mt-4 flex gap-2"><Button disabled={busy || !!preview.errors.length || note.length < 3} onClick={() => { void mutate(`tasks/${preview.task.id}/convert`, { version: preview.task.version, note }).then(() => setPreview(undefined)).catch(() => {}); }}>ยืนยัน Convert เป็น WO</Button><Button variant="outline" onClick={() => setPreview(undefined)}>ยกเลิก</Button></div></section>}
    {data.dates && current && <section className="space-y-3"><h2 className="text-lg font-semibold">Schedule preview</h2><form className="flex flex-wrap items-end gap-3" onSubmit={e => { e.preventDefault(); const v = new FormData(e.currentTarget); const range = { from: String(v.get("from")), to: String(v.get("to")) }; if (range.from > range.to || (+new Date(range.to) - +new Date(range.from)) / 86400000 > 365) { setError("วันสิ้นสุดต้องไม่ก่อนวันเริ่ม และช่วงวันที่ต้องไม่เกิน 366 วัน"); return; } setError(""); setPreviewRange(new URLSearchParams(range).toString()); }}><label className="text-sm">ตั้งแต่วันที่<Input name="from" type="date" required defaultValue={data.dates[0]} /></label><label className="text-sm">ถึงวันที่<Input name="to" type="date" required defaultValue={data.dates.at(-1)} /></label><Button variant="outline">ดูช่วงวันที่</Button></form><p className="text-sm text-slate-500">เลือกช่วงได้สูงสุด 366 วัน; การสร้างรอบย้อนหลังต้องยืนยันและระบุเหตุผล</p>{!data.dates.length && <p role="status">ไม่มีรอบตามแผนในช่วงวันที่นี้</p>}<label className="flex gap-2 text-sm"><input type="checkbox" checked={catchUp} onChange={e => setCatchUp(e.target.checked)} />ยืนยันการสร้างงานย้อนหลังสำหรับรอบที่ขาด</label>{result && <p role="status">{result}</p>}<div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{data.dates.map(date => { const occurrence = data.occurrences?.find(o => o.scheduledDate === date); return <article key={date} className="rounded-xl border bg-white p-4"><p className="font-semibold">{date}</p><p className="my-2 text-sm">{occurrence?.status ?? "Scheduled"}</p>{occurrence?.workOrderId ? <Link className="text-blue-700" href={`/work-orders/${occurrence.workOrderId}`}>Open Work Order</Link> : !occurrence && refs?.canGenerate && <Button disabled={busy || note.length < 3 || current.status !== "ACTIVE"} onClick={() => { void mutate(`programs/${id}/generate`, { version: current.version, dates: [date], note, catchUp }).then(r => setResult(r.results.map((v: { date: string; error?: string }) => `${v.date}: ${v.error || "สร้างสำเร็จ"}`).join("; "))).catch(() => {}); }}>Generate WO</Button>}</article>; })}</div></section>}
    {!!data.events?.length && <section className="rounded-xl border bg-white p-5"><h2 className="mb-3 font-semibold">History</h2>{data.events.map(e => <p key={e.id} className="border-t py-2 text-sm"><span className="font-medium">{e.eventType}</span> · {e.note}</p>)}</section>}
  </main>;
}
