import type { NextRequest } from "next/server";
import { getRequestMeta } from "@/lib/auth/request";
import { requirePermission } from "@/lib/auth/session";
import { getInventoryDocument } from "@/lib/inventory/service";
import { apiError } from "@/lib/http";

const escapeHtml = (value: unknown) => String(value ?? "—").replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;").replaceAll("'", "&#39;");
const readable = (value: unknown) => value ? new Date(String(value)).toLocaleString("en-GB") : "—";
const money = (value: unknown) => value === null || value === undefined ? "—" : Number(value).toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 });

export async function GET(request: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  const meta = getRequestMeta(request);
  try {
    const session = await requirePermission(request, "INVENTORY_REQUEST_VIEW");
    const document = await getInventoryDocument((await params).id, session.user);
    const rows = document.lines.map((line) => `<tr><td>${escapeHtml(line.stockItem.code)} — ${escapeHtml(line.stockItem.name)}</td><td>${escapeHtml(line.sourceLocation?.code ?? "—")}</td><td>${escapeHtml(line.destinationLocation?.code ?? "—")}</td><td>${escapeHtml(line.sourceReceiptLine?.document.documentNumber ?? "—")}</td><td>${escapeHtml(line.requestedQuantity)}</td><td>${escapeHtml(line.approvedQuantity ?? "—")}</td><td>${escapeHtml(line.unit)}</td><td>${escapeHtml(money(line.unitCost))}</td><td>${escapeHtml(money(line.totalAmount))}</td></tr>`).join("");
    const approvals = document.approvals.map((approval) => `<li><strong>${escapeHtml(approval.step)}</strong> — ${escapeHtml(approval.status)} — ${escapeHtml(approval.decisionByName ?? approval.requestedByName)} — ${escapeHtml(approval.decisionComment ?? "")}</li>`).join("");
    const html = `<!doctype html><html><head><meta charset="utf-8"><title>${escapeHtml(document.documentNumber)}</title><style>@page{size:A4;margin:14mm}*{box-sizing:border-box}body{font:12px Arial,sans-serif;color:#172033;margin:0}header{border-bottom:3px solid #175cd3;padding-bottom:12px;margin-bottom:16px}h1{font-size:22px;margin:4px 0}h2{font-size:15px;margin:22px 0 8px}.actions{margin-bottom:14px}.meta{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.meta div{border:1px solid #d7deea;padding:8px}.meta b{display:block;font-size:10px;color:#56637a;text-transform:uppercase;margin-bottom:3px}table{width:100%;border-collapse:collapse}th,td{border:1px solid #b9c3d3;padding:6px;text-align:left;vertical-align:top}th{background:#eef4ff}.signatures{display:grid;grid-template-columns:repeat(3,1fr);gap:24px;margin-top:50px}.signature{border-top:1px solid #172033;padding-top:6px;text-align:center}.qr{border:1px dashed #64748b;padding:12px;text-align:center;font-family:monospace}@media print{.actions{display:none}}</style></head><body><div class="actions"><button onclick="window.print()">Print / Save PDF</button></div><header><div>MA Next Maintenance Intelligence</div><h1>${escapeHtml(document.documentType)} · ${escapeHtml(document.documentNumber)}</h1><div>Status: ${escapeHtml(document.status)}</div></header><section class="meta"><div><b>Document date</b>${escapeHtml(readable(document.documentDate))}</div><div><b>Requester</b>${escapeHtml(document.requesterName)}</div><div><b>Plant / site</b>${escapeHtml(document.siteId)}</div><div><b>Department</b>${escapeHtml(document.departmentId)}</div><div><b>Purpose</b>${escapeHtml(document.purpose)}</div><div><b>Submitted</b>${escapeHtml(readable(document.submittedAt))}</div><div><b>Posted</b>${escapeHtml(readable(document.postedAt))}</div><div><b>Attachments</b>${document.attachments.length}</div></section><h2>Lines</h2><table><thead><tr><th>Stock item</th><th>Source</th><th>Destination</th><th>Source Receipt</th><th>Requested</th><th>Approved</th><th>Unit</th><th>Unit cost</th><th>Amount</th></tr></thead><tbody>${rows || `<tr><td colspan="9">No lines</td></tr>`}</tbody></table><h2>Approval timeline</h2><ul>${approvals || "<li>No approval history</li>"}</ul><h2>QR / reference</h2><div class="qr">${escapeHtml(document.documentNumber)}</div><div class="signatures"><div class="signature">Requester / Date</div><div class="signature">Maintenance Manager / Date</div><div class="signature">Warehouse Manager / Date</div></div></body></html>`;
    return new Response(html, { headers: { "content-type": "text/html; charset=utf-8", "content-disposition": `inline; filename="${document.documentNumber}.html"` } });
  } catch (error) { return apiError(error, meta.requestId); }
}
