"use client";
import { useEffect, useState, type FormEvent } from "react";
import { masterDataTypeSchema, masterDataValueSchema } from "@/lib/master-data/validation";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";

type TypeRow = { id: string; code: string; name: string; description: string | null; system: boolean; active: boolean; values: Array<{ id: string; code: string; label: string; active: boolean; sortOrder: number }> };
async function request(options?: RequestInit) { const response = await fetch("/api/master-data", options); const body = await response.json(); if (!response.ok) throw new Error(body.error || "Request failed"); return body; }
export function MasterDataWorkspace() { const [types, setTypes] = useState<TypeRow[]>([]); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); async function load() { setTypes((await request()).types); setLoading(false); } useEffect(() => { let active = true; request().then((body) => { if (active) { setTypes(body.types); setLoading(false); } }).catch((reason) => { if (active) { setError(reason.message); setLoading(false); } }); return () => { active = false; }; }, []); async function submit(kind: "type" | "value", event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); const data = Object.fromEntries(new FormData(event.currentTarget)); const parsed = kind === "type" ? masterDataTypeSchema.safeParse({ ...data, active: true }) : masterDataValueSchema.safeParse({ ...data, active: true }); if (!parsed.success) return setError(parsed.error.issues[0]?.message || "Invalid form"); try { await request({ method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ kind, data: parsed.data }) }); event.currentTarget.reset(); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to save"); } }
  return <main className="mx-auto max-w-7xl space-y-6 p-4 md:p-8"><header><p className="text-xs font-bold uppercase tracking-[.18em] text-blue-700">Configuration</p><h1 className="mt-2 text-3xl font-bold tracking-tight">Configurable master data</h1><p className="mt-2 max-w-2xl text-slate-600">Add controlled code lists without embedding business vocabulary in application code.</p></header>{error && <p role="alert" className="rounded-lg bg-red-50 p-3 text-sm font-semibold text-red-800">{error}</p>}<div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle>New data type</CardTitle><CardDescription>Define a reusable controlled vocabulary.</CardDescription></CardHeader><CardContent><form className="grid gap-3" onSubmit={(event) => submit("type", event)}><Field name="code" label="Type code" /><Field name="name" label="Name" /><Field name="description" label="Description" optional /><Button>Create data type</Button></form></CardContent></Card><Card><CardHeader><CardTitle>New value</CardTitle><CardDescription>Add a selectable value to an existing type.</CardDescription></CardHeader><CardContent><form className="grid gap-3" onSubmit={(event) => submit("value", event)}><div className="grid gap-1.5"><Label htmlFor="masterDataTypeId">Data type</Label><select id="masterDataTypeId" name="masterDataTypeId" required className="min-h-11 rounded-lg border border-slate-300 bg-white px-3 text-sm"><option value="">Select</option>{types.map((type) => <option key={type.id} value={type.id}>{type.name}</option>)}</select></div><Field name="code" label="Value code" /><Field name="label" label="Label" /><Field name="sortOrder" label="Sort order" type="number" defaultValue="0" /><Button disabled={!types.length}>Add value</Button></form></CardContent></Card></div><section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3" aria-busy={loading}>{loading ? <Card><CardContent className="p-6 text-slate-500">Loading master data…</CardContent></Card> : types.map((type) => <Card key={type.id}><CardHeader><div className="flex items-center justify-between"><CardTitle>{type.name}</CardTitle>{type.system && <Badge>System</Badge>}</div><CardDescription>{type.code} · {type.description || "No description"}</CardDescription></CardHeader><CardContent>{type.values.length ? <ul className="divide-y divide-slate-100">{type.values.map((value) => <li key={value.id} className="flex items-center justify-between py-2 text-sm"><span><strong>{value.code}</strong> · {value.label}</span><span className="text-xs text-slate-500">#{value.sortOrder}</span></li>)}</ul> : <p className="text-sm text-slate-500">No values configured.</p>}</CardContent></Card>)}{!loading && !types.length && <Card><CardContent className="p-6 text-slate-500">No master-data types exist. Create the first controlled vocabulary above.</CardContent></Card>}</section></main>; }
function Field({ name, label, optional, type = "text", defaultValue }: { name: string; label: string; optional?: boolean; type?: string; defaultValue?: string }) { return <div className="grid gap-1.5"><Label htmlFor={name}>{label}</Label><Input id={name} name={name} type={type} required={!optional} defaultValue={defaultValue} /></div>; }
