"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { Bell, CheckCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";

type Recipient = { id: string; status: "UNREAD" | "READ"; readAt: string | null; notification: { title: string; message: string; type: string; actionUrl: string | null; createdAt: string } };
export function NotificationCenter() { const [items, setItems] = useState<Recipient[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); async function load() { const response = await fetch("/api/notifications"); const body = await response.json(); if (!response.ok) throw new Error(body.error); setItems(body.notifications); setLoading(false); } useEffect(() => { let active = true; fetch("/api/notifications").then(async (response) => ({ response, body: await response.json() })).then(({ response, body }) => { if (!response.ok) throw new Error(body.error); if (active) { setItems(body.notifications); setLoading(false); } }).catch((reason) => { if (active) { setError(reason.message); setLoading(false); } }); return () => { active = false; }; }, []); async function markRead(id: string) { const response = await fetch(`/api/notifications/${id}/read`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ status: "READ" }) }); if (!response.ok) return setError((await response.json()).error); await load(); }
  return <main className="mx-auto max-w-5xl space-y-6 p-4 md:p-8"><header className="flex items-start gap-4"><span className="grid size-12 place-items-center rounded-2xl bg-blue-100 text-blue-800"><Bell className="size-6" /></span><div><p className="text-xs font-bold uppercase tracking-[.18em] text-blue-700">Inbox</p><h1 className="mt-1 text-3xl font-bold tracking-tight">Notification center</h1><p className="mt-2 text-slate-600">Operational updates and actions assigned to your account.</p></div></header>{error && <p role="alert" className="rounded-lg bg-red-50 p-3 text-sm font-semibold text-red-800">{error}</p>}<section className="grid gap-3" aria-busy={loading}>{loading ? <Card><CardContent className="p-6 text-slate-500">Loading notifications…</CardContent></Card> : items.map((item) => <Card key={item.id} className={item.status === "UNREAD" ? "border-blue-300" : undefined}><CardHeader><div className="flex flex-wrap items-start justify-between gap-3"><div><CardTitle className="flex items-center gap-2">{item.notification.title}{item.status === "UNREAD" && <Badge>Unread</Badge>}</CardTitle><CardDescription>{item.notification.type.replaceAll("_", " ")} · {new Date(item.notification.createdAt).toLocaleString()}</CardDescription></div>{item.status === "UNREAD" && <Button variant="outline" size="sm" onClick={() => markRead(item.id)}><CheckCheck className="size-4" />Mark read</Button>}</div></CardHeader><CardContent><p className="leading-7 text-slate-700">{item.notification.message}</p>{item.notification.actionUrl && <Button asChild variant="secondary" className="mt-4"><Link href={item.notification.actionUrl}>Open related record</Link></Button>}</CardContent></Card>)}{!loading && !items.length && <Card><CardContent className="p-10 text-center"><Bell className="mx-auto size-8 text-slate-400" /><p className="mt-3 font-semibold">You are all caught up</p><p className="mt-1 text-sm text-slate-500">New operational notifications will appear here.</p></CardContent></Card>}</section></main>; }
