import type { NotificationStatus, WorkOrderStatus } from "../db/schema";

export const notificationResponsibility: Record<NotificationStatus, { role: string; action: string }> = {
  NEW: { role: "Maintenance Manager", action: "Start review" }, BACKLOG: { role: "Maintenance Manager", action: "Create Work Order" }, COMPLETED: { role: "Operator", action: "Close Notification" },
  DRAFT: { role: "Operator", action: "Complete and submit Notification" }, SUBMITTED: { role: "Maintenance Manager", action: "Start review" }, UNDER_REVIEW: { role: "Maintenance Manager", action: "Approve, reject, or return for revision" }, RETURNED: { role: "Operator", action: "Revise and resubmit Notification" }, NEEDS_INFORMATION: { role: "Operator", action: "Provide requested information" }, REJECTED: { role: "None", action: "No action required" }, APPROVED: { role: "Maintenance Manager", action: "Create and assign Work Order" }, CONVERTED_TO_WORK_ORDER: { role: "Maintenance", action: "Complete linked Work Orders" }, IN_MAINTENANCE: { role: "Maintenance", action: "Complete linked Work Orders" }, WAITING_FOR_OPERATOR_ACCEPTANCE: { role: "Operator", action: "Accept work or request recheck" }, OPERATOR_REJECTED: { role: "Maintenance Manager", action: "Return a Work Order for recheck" }, OPERATOR_ACCEPTED: { role: "Maintenance Manager", action: "Close all linked Work Orders" }, READY_TO_CLOSE: { role: "Operator", action: "Close Notification" }, CLOSED: { role: "None", action: "Closed" }, CANCELLED: { role: "None", action: "Cancelled" },
};

export const workOrderResponsibility: Record<WorkOrderStatus, { role: string; action: string }> = {
  OPEN: { role: "Maintenance Manager", action: "Assign Technician" }, BACKLOG: { role: "Technician", action: "Resume work" }, COMPLETION_PENDING: { role: "Maintenance Manager", action: "Review completion" }, VERIFIED: { role: "Operator", action: "Review maintenance result" },
  CREATED: { role: "Maintenance Manager", action: "Assign Technician" }, ASSIGNED: { role: "Technician", action: "Accept assignment" }, TECHNICIAN_ACCEPTED: { role: "Technician", action: "Start work" }, IN_PROGRESS: { role: "Technician", action: "Perform work and submit completion" }, WAITING_FOR_PARTS: { role: "Technician", action: "Resume when parts arrive" }, WAITING_FOR_VENDOR: { role: "Technician", action: "Resume after vendor support" }, WAITING_FOR_ACCESS: { role: "Technician", action: "Resume when access is available" }, ON_HOLD: { role: "Technician", action: "Resolve hold and resume" }, TECHNICIAN_COMPLETED: { role: "Maintenance Manager", action: "Review completion revision" }, UNDER_MANAGER_REVIEW: { role: "Maintenance Manager", action: "Approve or return for recheck" }, RETURNED_TO_TECHNICIAN: { role: "Technician", action: "Recheck and submit a new revision" }, MANAGER_APPROVED: { role: "Maintenance Manager", action: "Request Operator acceptance" }, WAITING_FOR_OPERATOR_ACCEPTANCE: { role: "Operator", action: "Accept work or request recheck" }, OPERATOR_REJECTED: { role: "Maintenance Manager", action: "Review rejection and return for recheck" }, OPERATOR_ACCEPTED: { role: "Maintenance Manager", action: "Close Work Order" }, CLOSED: { role: "None", action: "Closed" }, CANCELLED: { role: "None", action: "Cancelled" },
};

export function elapsedSince(value: Date | string, now = new Date()) { return Math.max(0, now.getTime() - new Date(value).getTime()); }
export function isOverdue(dueAt: Date | string | null | undefined, status: string, now = new Date()) { return Boolean(dueAt && !["CLOSED", "CANCELLED", "REJECTED"].includes(status) && new Date(dueAt) < now); }
