-- Versioned, reusable sequential approval engine and PR/PO purchasing domain.

ALTER TABLE `approval_tasks`
  MODIFY COLUMN `approval_type` ENUM('NOTIFICATION','WORK_ORDER','WORK_COMPLETION','MATERIAL_REQUEST','PURCHASE_REQUEST','PURCHASE_ORDER','PREVENTIVE_MAINTENANCE','INVENTORY') NOT NULL;

CREATE TABLE `approval_workflows` (
  `id` VARCHAR(36) NOT NULL,
  `workflow_name` VARCHAR(190) NOT NULL,
  `document_type` ENUM('PURCHASE_REQUEST','PURCHASE_ORDER') NOT NULL,
  `department_id` VARCHAR(36) NULL,
  `min_amount_thb` DECIMAL(20,6) NOT NULL,
  `max_amount_thb` DECIMAL(20,6) NULL,
  `currency_basis` VARCHAR(40) NOT NULL DEFAULT 'THB_EQUIVALENT',
  `effective_from` DATETIME(3) NOT NULL,
  `effective_to` DATETIME(3) NULL,
  `status` ENUM('DRAFT','ACTIVE','INACTIVE') NOT NULL DEFAULT 'DRAFT',
  `is_active` BOOLEAN NOT NULL DEFAULT false,
  `priority` INT NOT NULL DEFAULT 0,
  `version` INT NOT NULL DEFAULT 1,
  `created_by` VARCHAR(36) NOT NULL,
  `updated_by` VARCHAR(36) NOT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `approval_workflows_route_idx` (`document_type`,`is_active`,`priority`),
  INDEX `approval_workflows_amount_idx` (`department_id`,`min_amount_thb`,`max_amount_thb`),
  CONSTRAINT `approval_workflows_department_fk` FOREIGN KEY (`department_id`) REFERENCES `departments` (`id`) ON DELETE SET NULL,
  CONSTRAINT `approval_workflows_created_by_fk` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`),
  CONSTRAINT `approval_workflows_updated_by_fk` FOREIGN KEY (`updated_by`) REFERENCES `users` (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `approval_workflow_versions` (
  `id` VARCHAR(36) NOT NULL,
  `workflow_id` VARCHAR(36) NOT NULL,
  `version` INT NOT NULL,
  `document_type` ENUM('PURCHASE_REQUEST','PURCHASE_ORDER') NOT NULL,
  `department_id` VARCHAR(36) NULL,
  `min_amount_thb` DECIMAL(20,6) NOT NULL,
  `max_amount_thb` DECIMAL(20,6) NULL,
  `currency_basis` VARCHAR(40) NOT NULL DEFAULT 'THB_EQUIVALENT',
  `effective_from` DATETIME(3) NOT NULL,
  `effective_to` DATETIME(3) NULL,
  `priority` INT NOT NULL DEFAULT 0,
  `created_by` VARCHAR(36) NOT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `approval_workflow_versions_workflow_version_uq` (`workflow_id`,`version`),
  INDEX `approval_workflow_versions_route_idx` (`document_type`,`department_id`,`min_amount_thb`,`max_amount_thb`),
  CONSTRAINT `approval_workflow_versions_workflow_fk` FOREIGN KEY (`workflow_id`) REFERENCES `approval_workflows` (`id`) ON DELETE CASCADE,
  CONSTRAINT `approval_workflow_versions_department_fk` FOREIGN KEY (`department_id`) REFERENCES `departments` (`id`) ON DELETE SET NULL,
  CONSTRAINT `approval_workflow_versions_created_by_fk` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `approval_workflow_steps` (
  `id` VARCHAR(36) NOT NULL,
  `workflow_version_id` VARCHAR(36) NOT NULL,
  `step_number` INT NOT NULL,
  `step_name` VARCHAR(160) NOT NULL,
  `approver_type` ENUM('SPECIFIC_USER','DEPARTMENT_MANAGER','ROLE','REQUESTER_MANAGER','PURCHASE_MANAGER') NOT NULL,
  `approver_user_id` VARCHAR(36) NULL,
  `approver_username_snapshot` VARCHAR(80) NULL,
  `approver_role` VARCHAR(120) NULL,
  `alternate_user_id` VARCHAR(36) NULL,
  `alternate_username_snapshot` VARCHAR(80) NULL,
  `min_amount_thb` DECIMAL(20,6) NOT NULL DEFAULT 0,
  `max_amount_thb` DECIMAL(20,6) NULL,
  `is_required` BOOLEAN NOT NULL DEFAULT true,
  `allow_self_approval` BOOLEAN NOT NULL DEFAULT false,
  `can_reject` BOOLEAN NOT NULL DEFAULT true,
  `can_return_for_revision` BOOLEAN NOT NULL DEFAULT true,
  `can_delegate` BOOLEAN NOT NULL DEFAULT false,
  `escalation_duration_hours` INT NULL,
  `is_active` BOOLEAN NOT NULL DEFAULT true,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `approval_workflow_steps_number_uq` (`workflow_version_id`,`step_number`),
  INDEX `approval_workflow_steps_approver_idx` (`approver_user_id`,`is_active`),
  CONSTRAINT `approval_workflow_steps_version_fk` FOREIGN KEY (`workflow_version_id`) REFERENCES `approval_workflow_versions` (`id`) ON DELETE CASCADE,
  CONSTRAINT `approval_workflow_steps_approver_fk` FOREIGN KEY (`approver_user_id`) REFERENCES `users` (`id`),
  CONSTRAINT `approval_workflow_steps_alternate_fk` FOREIGN KEY (`alternate_user_id`) REFERENCES `users` (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `approval_instances` (
  `id` VARCHAR(36) NOT NULL,
  `document_type` ENUM('PURCHASE_REQUEST','PURCHASE_ORDER') NOT NULL,
  `document_id` VARCHAR(36) NOT NULL,
  `workflow_id` VARCHAR(36) NOT NULL,
  `workflow_version_id` VARCHAR(36) NOT NULL,
  `workflow_version` INT NOT NULL,
  `cycle_number` INT NOT NULL DEFAULT 1,
  `document_amount` DECIMAL(20,6) NOT NULL,
  `currency_code` VARCHAR(10) NOT NULL,
  `exchange_rate_to_thb` DECIMAL(20,10) NOT NULL,
  `document_amount_thb` DECIMAL(20,6) NOT NULL,
  `department_id` VARCHAR(36) NULL,
  `current_step_number` INT NULL,
  `status` ENUM('PENDING','APPROVED','REJECTED','RETURNED_FOR_REVISION','CANCELLED') NOT NULL DEFAULT 'PENDING',
  `submitted_by` VARCHAR(36) NOT NULL,
  `submitted_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `completed_at` DATETIME(3) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `approval_instances_document_cycle_uq` (`document_type`,`document_id`,`cycle_number`),
  INDEX `approval_instances_document_status_idx` (`document_type`,`document_id`,`status`),
  INDEX `approval_instances_queue_idx` (`status`,`current_step_number`),
  INDEX `approval_instances_workflow_idx` (`workflow_id`,`workflow_version`),
  CONSTRAINT `approval_instances_workflow_fk` FOREIGN KEY (`workflow_id`) REFERENCES `approval_workflows` (`id`),
  CONSTRAINT `approval_instances_version_fk` FOREIGN KEY (`workflow_version_id`) REFERENCES `approval_workflow_versions` (`id`),
  CONSTRAINT `approval_instances_department_fk` FOREIGN KEY (`department_id`) REFERENCES `departments` (`id`) ON DELETE SET NULL,
  CONSTRAINT `approval_instances_submitted_by_fk` FOREIGN KEY (`submitted_by`) REFERENCES `users` (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `approval_instance_steps` (
  `id` VARCHAR(36) NOT NULL,
  `approval_instance_id` VARCHAR(36) NOT NULL,
  `workflow_step_id` VARCHAR(36) NULL,
  `step_number` INT NOT NULL,
  `step_name` VARCHAR(160) NOT NULL,
  `approver_type` ENUM('SPECIFIC_USER','DEPARTMENT_MANAGER','ROLE','REQUESTER_MANAGER','PURCHASE_MANAGER') NOT NULL,
  `assigned_user_id` VARCHAR(36) NOT NULL,
  `assigned_username_snapshot` VARCHAR(80) NOT NULL,
  `original_approver_user_id` VARCHAR(36) NOT NULL,
  `original_approver_username_snapshot` VARCHAR(80) NOT NULL,
  `actual_approver_user_id` VARCHAR(36) NULL,
  `alternate_user_id` VARCHAR(36) NULL,
  `alternate_username_snapshot` VARCHAR(80) NULL,
  `min_amount_thb` DECIMAL(20,6) NOT NULL DEFAULT 0,
  `max_amount_thb` DECIMAL(20,6) NULL,
  `is_required` BOOLEAN NOT NULL DEFAULT true,
  `allow_self_approval` BOOLEAN NOT NULL DEFAULT false,
  `can_reject` BOOLEAN NOT NULL DEFAULT true,
  `can_return_for_revision` BOOLEAN NOT NULL DEFAULT true,
  `can_delegate` BOOLEAN NOT NULL DEFAULT false,
  `status` ENUM('WAITING','PENDING','APPROVED','REJECTED','RETURNED','SKIPPED','CANCELLED') NOT NULL DEFAULT 'WAITING',
  `last_action` ENUM('SUBMITTED','OPENED','APPROVED','REJECTED','RETURNED_FOR_REVISION','DELEGATED','COMMENTED','CANCELLED','RESUBMITTED') NULL,
  `comment` TEXT NULL,
  `action_at` DATETIME(3) NULL,
  `due_at` DATETIME(3) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `approval_instance_steps_number_uq` (`approval_instance_id`,`step_number`),
  INDEX `approval_instance_steps_assignee_status_idx` (`assigned_user_id`,`status`),
  INDEX `approval_instance_steps_due_idx` (`status`,`due_at`),
  CONSTRAINT `approval_instance_steps_instance_fk` FOREIGN KEY (`approval_instance_id`) REFERENCES `approval_instances` (`id`) ON DELETE CASCADE,
  CONSTRAINT `approval_instance_steps_workflow_step_fk` FOREIGN KEY (`workflow_step_id`) REFERENCES `approval_workflow_steps` (`id`) ON DELETE SET NULL,
  CONSTRAINT `approval_instance_steps_assigned_fk` FOREIGN KEY (`assigned_user_id`) REFERENCES `users` (`id`),
  CONSTRAINT `approval_instance_steps_original_fk` FOREIGN KEY (`original_approver_user_id`) REFERENCES `users` (`id`),
  CONSTRAINT `approval_instance_steps_actual_fk` FOREIGN KEY (`actual_approver_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `approval_instance_steps_alternate_fk` FOREIGN KEY (`alternate_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `approval_actions` (
  `id` VARCHAR(36) NOT NULL,
  `approval_instance_id` VARCHAR(36) NOT NULL,
  `approval_instance_step_id` VARCHAR(36) NULL,
  `action` ENUM('SUBMITTED','OPENED','APPROVED','REJECTED','RETURNED_FOR_REVISION','DELEGATED','COMMENTED','CANCELLED','RESUBMITTED') NOT NULL,
  `actor_user_id` VARCHAR(36) NOT NULL,
  `actor_username_snapshot` VARCHAR(80) NOT NULL,
  `original_approver_user_id` VARCHAR(36) NULL,
  `actual_approver_user_id` VARCHAR(36) NULL,
  `comment` TEXT NULL,
  `metadata` LONGTEXT NULL,
  `action_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  INDEX `approval_actions_instance_idx` (`approval_instance_id`,`action_at`),
  INDEX `approval_actions_actor_idx` (`actor_user_id`,`action_at`),
  CONSTRAINT `approval_actions_instance_fk` FOREIGN KEY (`approval_instance_id`) REFERENCES `approval_instances` (`id`) ON DELETE CASCADE,
  CONSTRAINT `approval_actions_step_fk` FOREIGN KEY (`approval_instance_step_id`) REFERENCES `approval_instance_steps` (`id`) ON DELETE SET NULL,
  CONSTRAINT `approval_actions_actor_fk` FOREIGN KEY (`actor_user_id`) REFERENCES `users` (`id`),
  CONSTRAINT `approval_actions_original_fk` FOREIGN KEY (`original_approver_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `approval_actions_actual_fk` FOREIGN KEY (`actual_approver_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `approval_delegations` (
  `id` VARCHAR(36) NOT NULL,
  `primary_approver_id` VARCHAR(36) NOT NULL,
  `delegate_user_id` VARCHAR(36) NOT NULL,
  `delegation_start` DATETIME(3) NOT NULL,
  `delegation_end` DATETIME(3) NOT NULL,
  `reason` TEXT NULL,
  `active` BOOLEAN NOT NULL DEFAULT true,
  `created_by` VARCHAR(36) NOT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `approval_delegations_primary_date_idx` (`primary_approver_id`,`active`,`delegation_start`,`delegation_end`),
  INDEX `approval_delegations_delegate_date_idx` (`delegate_user_id`,`active`,`delegation_start`,`delegation_end`),
  CONSTRAINT `approval_delegations_primary_fk` FOREIGN KEY (`primary_approver_id`) REFERENCES `users` (`id`),
  CONSTRAINT `approval_delegations_delegate_fk` FOREIGN KEY (`delegate_user_id`) REFERENCES `users` (`id`),
  CONSTRAINT `approval_delegations_created_by_fk` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `purchase_requests` (
  `id` VARCHAR(36) NOT NULL,
  `request_number` VARCHAR(80) NOT NULL,
  `requester_id` VARCHAR(36) NOT NULL,
  `department_id` VARCHAR(36) NOT NULL,
  `status` ENUM('DRAFT','PENDING_APPROVAL','RETURNED_FOR_REVISION','APPROVED','REJECTED','PARTIALLY_CONVERTED','CONVERTED','CANCELLED') NOT NULL DEFAULT 'DRAFT',
  `currency_code` VARCHAR(10) NOT NULL DEFAULT 'THB',
  `exchange_rate_to_thb` DECIMAL(20,10) NOT NULL DEFAULT 1,
  `estimated_total_amount` DECIMAL(20,6) NOT NULL DEFAULT 0,
  `estimated_total_amount_thb` DECIMAL(20,6) NOT NULL DEFAULT 0,
  `submitted_at` DATETIME(3) NULL,
  `approved_at` DATETIME(3) NULL,
  `rejected_at` DATETIME(3) NULL,
  `returned_at` DATETIME(3) NULL,
  `cycle_number` INT NOT NULL DEFAULT 0,
  `revision_number` INT NOT NULL DEFAULT 0,
  `remark` TEXT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  `created_by` VARCHAR(36) NOT NULL,
  `updated_by` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `purchase_requests_number_uq` (`request_number`),
  INDEX `purchase_requests_status_department_idx` (`status`,`department_id`),
  INDEX `purchase_requests_requester_idx` (`requester_id`,`created_at`),
  CONSTRAINT `purchase_requests_requester_fk` FOREIGN KEY (`requester_id`) REFERENCES `users` (`id`),
  CONSTRAINT `purchase_requests_department_fk` FOREIGN KEY (`department_id`) REFERENCES `departments` (`id`),
  CONSTRAINT `purchase_requests_created_by_fk` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`),
  CONSTRAINT `purchase_requests_updated_by_fk` FOREIGN KEY (`updated_by`) REFERENCES `users` (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `purchase_request_lines` (
  `id` VARCHAR(36) NOT NULL,
  `purchase_request_id` VARCHAR(36) NOT NULL,
  `line_number` INT NOT NULL,
  `stock_item_id` VARCHAR(36) NOT NULL,
  `stock_code_snapshot` VARCHAR(80) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `quantity` DECIMAL(20,6) NOT NULL,
  `estimated_unit_price` DECIMAL(20,6) NOT NULL,
  `discount_amount` DECIMAL(20,6) NOT NULL DEFAULT 0,
  `line_total` DECIMAL(20,6) NOT NULL,
  `remark` TEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `purchase_request_lines_number_uq` (`purchase_request_id`,`line_number`),
  INDEX `purchase_request_lines_stock_item_idx` (`stock_item_id`),
  CONSTRAINT `purchase_request_lines_request_fk` FOREIGN KEY (`purchase_request_id`) REFERENCES `purchase_requests` (`id`) ON DELETE CASCADE,
  CONSTRAINT `purchase_request_lines_stock_item_fk` FOREIGN KEY (`stock_item_id`) REFERENCES `stock_items` (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `purchase_request_vendors` (
  `id` VARCHAR(36) NOT NULL,
  `purchase_request_id` VARCHAR(36) NOT NULL,
  `vendor_id` VARCHAR(36) NOT NULL,
  `vendor_name_snapshot` VARCHAR(190) NOT NULL,
  `rank` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `purchase_request_vendors_request_vendor_uq` (`purchase_request_id`,`vendor_id`),
  UNIQUE INDEX `purchase_request_vendors_request_rank_uq` (`purchase_request_id`,`rank`),
  INDEX `purchase_request_vendors_vendor_idx` (`vendor_id`),
  CONSTRAINT `purchase_request_vendors_request_fk` FOREIGN KEY (`purchase_request_id`) REFERENCES `purchase_requests` (`id`) ON DELETE CASCADE,
  CONSTRAINT `purchase_request_vendors_vendor_fk` FOREIGN KEY (`vendor_id`) REFERENCES `vendors` (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `purchase_orders` (
  `id` VARCHAR(36) NOT NULL,
  `order_number` VARCHAR(80) NOT NULL,
  `purchase_request_id` VARCHAR(36) NULL,
  `vendor_id` VARCHAR(36) NOT NULL,
  `vendor_name_snapshot` VARCHAR(190) NOT NULL,
  `creator_id` VARCHAR(36) NOT NULL,
  `department_id` VARCHAR(36) NOT NULL,
  `status` ENUM('DRAFT','PENDING_APPROVAL','RETURNED_FOR_REVISION','APPROVED','ISSUED','PARTIAL_RECEIVED','RECEIVED','CLOSED','REJECTED','CANCELLED') NOT NULL DEFAULT 'DRAFT',
  `purchase_method` VARCHAR(80) NULL,
  `currency_code` VARCHAR(10) NOT NULL DEFAULT 'THB',
  `exchange_rate_to_thb` DECIMAL(20,10) NOT NULL DEFAULT 1,
  `subtotal_amount` DECIMAL(20,6) NOT NULL DEFAULT 0,
  `item_discount_amount` DECIMAL(20,6) NOT NULL DEFAULT 0,
  `header_discount_amount` DECIMAL(20,6) NOT NULL DEFAULT 0,
  `vat_amount` DECIMAL(20,6) NOT NULL DEFAULT 0,
  `grand_total_amount` DECIMAL(20,6) NOT NULL DEFAULT 0,
  `grand_total_amount_thb` DECIMAL(20,6) NOT NULL DEFAULT 0,
  `submitted_at` DATETIME(3) NULL,
  `approved_at` DATETIME(3) NULL,
  `issued_at` DATETIME(3) NULL,
  `issued_by` VARCHAR(36) NULL,
  `cycle_number` INT NOT NULL DEFAULT 0,
  `revision_number` INT NOT NULL DEFAULT 0,
  `remark` TEXT NULL,
  `internal_remark` TEXT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  `created_by` VARCHAR(36) NOT NULL,
  `updated_by` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `purchase_orders_number_uq` (`order_number`),
  INDEX `purchase_orders_status_department_idx` (`status`,`department_id`),
  INDEX `purchase_orders_creator_idx` (`creator_id`,`created_at`),
  INDEX `purchase_orders_request_idx` (`purchase_request_id`),
  CONSTRAINT `purchase_orders_request_fk` FOREIGN KEY (`purchase_request_id`) REFERENCES `purchase_requests` (`id`) ON DELETE SET NULL,
  CONSTRAINT `purchase_orders_vendor_fk` FOREIGN KEY (`vendor_id`) REFERENCES `vendors` (`id`),
  CONSTRAINT `purchase_orders_creator_fk` FOREIGN KEY (`creator_id`) REFERENCES `users` (`id`),
  CONSTRAINT `purchase_orders_department_fk` FOREIGN KEY (`department_id`) REFERENCES `departments` (`id`),
  CONSTRAINT `purchase_orders_issued_by_fk` FOREIGN KEY (`issued_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `purchase_orders_created_by_fk` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`),
  CONSTRAINT `purchase_orders_updated_by_fk` FOREIGN KEY (`updated_by`) REFERENCES `users` (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `purchase_order_lines` (
  `id` VARCHAR(36) NOT NULL,
  `purchase_order_id` VARCHAR(36) NOT NULL,
  `line_number` INT NOT NULL,
  `stock_item_id` VARCHAR(36) NOT NULL,
  `stock_code_snapshot` VARCHAR(80) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `quantity` DECIMAL(20,6) NOT NULL,
  `unit_price` DECIMAL(20,6) NOT NULL,
  `item_discount_amount` DECIMAL(20,6) NOT NULL DEFAULT 0,
  `line_subtotal` DECIMAL(20,6) NOT NULL,
  `line_total` DECIMAL(20,6) NOT NULL,
  `received_quantity` DECIMAL(20,6) NOT NULL DEFAULT 0,
  `remark` TEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `purchase_order_lines_number_uq` (`purchase_order_id`,`line_number`),
  INDEX `purchase_order_lines_stock_item_idx` (`stock_item_id`),
  CONSTRAINT `purchase_order_lines_order_fk` FOREIGN KEY (`purchase_order_id`) REFERENCES `purchase_orders` (`id`) ON DELETE CASCADE,
  CONSTRAINT `purchase_order_lines_stock_item_fk` FOREIGN KEY (`stock_item_id`) REFERENCES `stock_items` (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

ALTER TABLE `inventory_document_lines`
  ADD COLUMN `purchase_order_id` VARCHAR(36) NULL,
  ADD INDEX `inventory_document_lines_purchase_order_idx` (`purchase_order_id`),
  ADD CONSTRAINT `inventory_document_lines_purchase_order_fk`
    FOREIGN KEY (`purchase_order_id`) REFERENCES `purchase_orders` (`id`) ON DELETE SET NULL;
