import type { Role } from "@/lib/db/schema";

export type Permission =
  | "VIEW_ORGANIZATION" | "MANAGE_ORGANIZATION" | "VIEW_MASTER_DATA" | "MANAGE_MASTER_DATA"
  | "VIEW_NOTIFICATIONS" | "MANAGE_NOTIFICATIONS" | "VIEW_ATTACHMENTS" | "MANAGE_ATTACHMENTS"
  | "MANAGE_USERS" | "VIEW_LOGIN_HISTORY" | "VIEW_AUDIT_LOGS" | "VIEW_MAINTENANCE"
  | "ASSET_READ" | "ASSET_CREATE" | "ASSET_UPDATE" | "ASSET_ARCHIVE" | "ASSET_HIERARCHY_MANAGE"
  | "ASSET_CUSTOM_FIELDS_MANAGE" | "CREATE_MAINTENANCE_NOTIFICATION" | "REVIEW_MAINTENANCE_NOTIFICATION"
  | "MANAGE_WORK_ORDERS" | "EXECUTE_WORK_ORDERS" | "VERIFY_WORK_ORDERS" | "CLOSE_WORK_ORDERS"
  | "NOTIFICATION_CREATE" | "NOTIFICATION_EDIT_OWN_DRAFT" | "NOTIFICATION_SUBMIT" | "NOTIFICATION_VIEW"
  | "NOTIFICATION_REVIEW" | "NOTIFICATION_REQUEST_INFORMATION" | "NOTIFICATION_REJECT" | "NOTIFICATION_APPROVE"
  | "NOTIFICATION_ACCEPT_WORK" | "NOTIFICATION_REJECT_WORK" | "NOTIFICATION_CLOSE"
  | "WORK_ORDER_CREATE" | "WORK_ORDER_VIEW" | "WORK_ORDER_ASSIGN" | "WORK_ORDER_REASSIGN"
  | "WORK_ORDER_ACCEPT_ASSIGNMENT" | "WORK_ORDER_START" | "WORK_ORDER_UPDATE_PROGRESS"
  | "WORK_ORDER_SUBMIT_COMPLETION" | "WORK_ORDER_REVIEW_COMPLETION" | "WORK_ORDER_APPROVE_COMPLETION"
  | "WORK_ORDER_RETURN_FOR_RECHECK" | "WORK_ORDER_CLOSE" | "WORK_ORDER_OVERRIDE_WARNING"
  | "VIEW_APPROVAL_CENTER" | "VIEW_INVENTORY" | "MANAGE_INVENTORY" | "INVENTORY_STOCK_ITEM_MANAGE"
  | "INVENTORY_LOCATION_MANAGE" | "INVENTORY_VENDOR_MANAGE" | "INVENTORY_REQUEST_CREATE"
  | "INVENTORY_REQUEST_VIEW" | "INVENTORY_REQUEST_SUBMIT" | "INVENTORY_APPROVE_MAINTENANCE"
  | "INVENTORY_APPROVE_WAREHOUSE" | "INVENTORY_POST" | "INVENTORY_COUNT_MANAGE" | "INVENTORY_COUNT_REVIEW"
  | "INVENTORY_REPORT_VIEW" | "INVENTORY_CONFIG_MANAGE" | "INVENTORY_EXPORT"
  | "AUDIT_VIEW" | "USER_MANAGE" | "ROLE_MANAGE" | "MANAGE_DATA_SOURCES" | "CREATE_DASHBOARD"
  | "VIEW_DASHBOARD" | "EXPORT_DATA" | "USE_COPILOT";

const foundation: Permission[] = ["VIEW_ORGANIZATION", "VIEW_MASTER_DATA", "VIEW_NOTIFICATIONS", "VIEW_ATTACHMENTS", "VIEW_MAINTENANCE", "ASSET_READ", "VIEW_DASHBOARD", "AUDIT_VIEW"];
const notificationCreator: Permission[] = ["NOTIFICATION_CREATE", "NOTIFICATION_EDIT_OWN_DRAFT", "NOTIFICATION_SUBMIT", "NOTIFICATION_VIEW"];
const workViewer: Permission[] = ["WORK_ORDER_VIEW"];
const inventoryReader: Permission[] = ["VIEW_APPROVAL_CENTER", "VIEW_INVENTORY", "INVENTORY_REQUEST_VIEW", "INVENTORY_REPORT_VIEW"];
const inventoryRequester: Permission[] = ["INVENTORY_REQUEST_CREATE", "INVENTORY_REQUEST_SUBMIT"];
const adminInventory: Permission[] = ["MANAGE_INVENTORY", "INVENTORY_STOCK_ITEM_MANAGE", "INVENTORY_LOCATION_MANAGE", "INVENTORY_VENDOR_MANAGE", "INVENTORY_REQUEST_CREATE", "INVENTORY_REQUEST_VIEW", "INVENTORY_REQUEST_SUBMIT", "INVENTORY_APPROVE_MAINTENANCE", "INVENTORY_APPROVE_WAREHOUSE", "INVENTORY_POST", "INVENTORY_COUNT_MANAGE", "INVENTORY_COUNT_REVIEW", "INVENTORY_REPORT_VIEW", "INVENTORY_CONFIG_MANAGE", "INVENTORY_EXPORT"];
const warehouseManagerInventory: Permission[] = ["MANAGE_INVENTORY", "INVENTORY_STOCK_ITEM_MANAGE", "INVENTORY_LOCATION_MANAGE", "INVENTORY_VENDOR_MANAGE", "INVENTORY_REQUEST_CREATE", "INVENTORY_REQUEST_VIEW", "INVENTORY_REQUEST_SUBMIT", "INVENTORY_APPROVE_WAREHOUSE", "INVENTORY_POST", "INVENTORY_COUNT_MANAGE", "INVENTORY_REPORT_VIEW", "INVENTORY_EXPORT"];

function permissions(...groups: Permission[][]) { return new Set<Permission>(groups.flat()); }

export const rolePermissions: Record<Role, ReadonlySet<Permission>> = {
  ADMIN: permissions(foundation, notificationCreator, workViewer, adminInventory, ["MANAGE_ORGANIZATION", "MANAGE_MASTER_DATA", "MANAGE_NOTIFICATIONS", "MANAGE_ATTACHMENTS", "MANAGE_USERS", "VIEW_LOGIN_HISTORY", "VIEW_AUDIT_LOGS", "ASSET_CREATE", "ASSET_UPDATE", "ASSET_ARCHIVE", "ASSET_HIERARCHY_MANAGE", "ASSET_CUSTOM_FIELDS_MANAGE", "CREATE_MAINTENANCE_NOTIFICATION", "REVIEW_MAINTENANCE_NOTIFICATION", "MANAGE_WORK_ORDERS", "EXECUTE_WORK_ORDERS", "VERIFY_WORK_ORDERS", "CLOSE_WORK_ORDERS", "MANAGE_DATA_SOURCES", "CREATE_DASHBOARD", "EXPORT_DATA", "USE_COPILOT", "NOTIFICATION_REVIEW", "NOTIFICATION_REQUEST_INFORMATION", "NOTIFICATION_REJECT", "NOTIFICATION_APPROVE", "NOTIFICATION_ACCEPT_WORK", "NOTIFICATION_REJECT_WORK", "NOTIFICATION_CLOSE", "WORK_ORDER_CREATE", "WORK_ORDER_ASSIGN", "WORK_ORDER_REASSIGN", "WORK_ORDER_ACCEPT_ASSIGNMENT", "WORK_ORDER_START", "WORK_ORDER_UPDATE_PROGRESS", "WORK_ORDER_SUBMIT_COMPLETION", "WORK_ORDER_REVIEW_COMPLETION", "WORK_ORDER_APPROVE_COMPLETION", "WORK_ORDER_RETURN_FOR_RECHECK", "WORK_ORDER_CLOSE", "WORK_ORDER_OVERRIDE_WARNING", "USER_MANAGE", "ROLE_MANAGE"]),
  DATA_SOURCE_CREATOR: permissions(foundation, notificationCreator, workViewer, ["VIEW_APPROVAL_CENTER", "MANAGE_ATTACHMENTS", "ASSET_CREATE", "ASSET_UPDATE", "ASSET_HIERARCHY_MANAGE", "ASSET_CUSTOM_FIELDS_MANAGE", "CREATE_MAINTENANCE_NOTIFICATION", "REVIEW_MAINTENANCE_NOTIFICATION", "MANAGE_WORK_ORDERS", "EXECUTE_WORK_ORDERS", "VERIFY_WORK_ORDERS", "CLOSE_WORK_ORDERS", "MANAGE_DATA_SOURCES", "USE_COPILOT", "NOTIFICATION_REVIEW", "NOTIFICATION_REQUEST_INFORMATION", "NOTIFICATION_REJECT", "NOTIFICATION_APPROVE", "WORK_ORDER_CREATE", "WORK_ORDER_ASSIGN", "WORK_ORDER_REASSIGN", "WORK_ORDER_UPDATE_PROGRESS", "WORK_ORDER_REVIEW_COMPLETION", "WORK_ORDER_APPROVE_COMPLETION", "WORK_ORDER_RETURN_FOR_RECHECK", "WORK_ORDER_CLOSE"]),
  DASHBOARD_CREATOR: permissions(foundation, notificationCreator, workViewer, ["CREATE_MAINTENANCE_NOTIFICATION", "EXECUTE_WORK_ORDERS", "CREATE_DASHBOARD", "USE_COPILOT", "WORK_ORDER_ACCEPT_ASSIGNMENT", "WORK_ORDER_START", "WORK_ORDER_UPDATE_PROGRESS", "WORK_ORDER_SUBMIT_COMPLETION"]),
  VIEWER: permissions(foundation, notificationCreator, workViewer, ["CREATE_MAINTENANCE_NOTIFICATION", "USE_COPILOT", "NOTIFICATION_ACCEPT_WORK", "NOTIFICATION_REJECT_WORK", "NOTIFICATION_CLOSE"]),
  OPERATOR: permissions(foundation, notificationCreator, workViewer, ["NOTIFICATION_CREATE", "NOTIFICATION_EDIT_OWN_DRAFT", "NOTIFICATION_SUBMIT", "NOTIFICATION_VIEW", "NOTIFICATION_ACCEPT_WORK", "NOTIFICATION_REJECT_WORK", "NOTIFICATION_CLOSE"]),
  MAINTENANCE: permissions(foundation, notificationCreator, workViewer, inventoryReader, inventoryRequester, ["MANAGE_ATTACHMENTS", "WORK_ORDER_ACCEPT_ASSIGNMENT", "WORK_ORDER_START", "WORK_ORDER_UPDATE_PROGRESS", "WORK_ORDER_SUBMIT_COMPLETION"]),
  MAINTENANCE_MANAGER: permissions(foundation, notificationCreator, workViewer, inventoryReader, ["MANAGE_ATTACHMENTS", "NOTIFICATION_REVIEW", "NOTIFICATION_REQUEST_INFORMATION", "NOTIFICATION_REJECT", "NOTIFICATION_APPROVE", "INVENTORY_APPROVE_MAINTENANCE", "WORK_ORDER_CREATE", "WORK_ORDER_ASSIGN", "WORK_ORDER_REASSIGN", "WORK_ORDER_UPDATE_PROGRESS", "WORK_ORDER_REVIEW_COMPLETION", "WORK_ORDER_APPROVE_COMPLETION", "WORK_ORDER_RETURN_FOR_RECHECK", "WORK_ORDER_CLOSE"]),
  WAREHOUSE_MANAGER: permissions(foundation, inventoryReader, warehouseManagerInventory, ["MANAGE_ATTACHMENTS"]),
  PLANT_MANAGER: permissions(foundation, inventoryReader, ["MANAGE_ATTACHMENTS", "INVENTORY_COUNT_REVIEW"]),
  TECHNICIAN: permissions(foundation, notificationCreator, workViewer, ["MANAGE_ATTACHMENTS", "WORK_ORDER_ACCEPT_ASSIGNMENT", "WORK_ORDER_START", "WORK_ORDER_UPDATE_PROGRESS", "WORK_ORDER_SUBMIT_COMPLETION"]),
};

export function hasPermission(role: Role, permission: Permission) { return rolePermissions[role].has(permission); }
export const canManageUsers = (role: Role) => hasPermission(role, "MANAGE_USERS");
export const canManageDataSources = (role: Role) => hasPermission(role, "MANAGE_DATA_SOURCES");
export const canCreateDashboard = (role: Role) => hasPermission(role, "CREATE_DASHBOARD");
export const canViewAuditLogs = (role: Role) => hasPermission(role, "VIEW_AUDIT_LOGS");
export const canUseCopilot = (role: Role) => hasPermission(role, "USE_COPILOT");
export const canReviewMaintenance = (role: Role) => hasPermission(role, "REVIEW_MAINTENANCE_NOTIFICATION");
export const canExecuteWorkOrders = (role: Role) => hasPermission(role, "EXECUTE_WORK_ORDERS");
export const canVerifyWorkOrders = (role: Role) => hasPermission(role, "VERIFY_WORK_ORDERS");
export const canReadAssets = (role: Role) => hasPermission(role, "ASSET_READ");
export const canViewInventory = (role: Role) => hasPermission(role, "VIEW_INVENTORY");
