import type { Role } from "@/lib/db/schema";

export type Permission =
  | "VIEW_ORGANIZATION"
  | "MANAGE_ORGANIZATION"
  | "VIEW_MASTER_DATA"
  | "MANAGE_MASTER_DATA"
  | "VIEW_NOTIFICATIONS"
  | "MANAGE_NOTIFICATIONS"
  | "VIEW_ATTACHMENTS"
  | "MANAGE_ATTACHMENTS"
  | "MANAGE_USERS"
  | "VIEW_LOGIN_HISTORY"
  | "VIEW_AUDIT_LOGS"
  | "VIEW_MAINTENANCE"
  | "ASSET_READ"
  | "ASSET_CREATE"
  | "ASSET_UPDATE"
  | "ASSET_ARCHIVE"
  | "ASSET_HIERARCHY_MANAGE"
  | "ASSET_CUSTOM_FIELDS_MANAGE"
  | "CREATE_MAINTENANCE_NOTIFICATION"
  | "REVIEW_MAINTENANCE_NOTIFICATION"
  | "MANAGE_WORK_ORDERS"
  | "EXECUTE_WORK_ORDERS"
  | "VERIFY_WORK_ORDERS"
  | "CLOSE_WORK_ORDERS"
  | "MANAGE_DATA_SOURCES"
  | "CREATE_DASHBOARD"
  | "VIEW_DASHBOARD"
  | "EXPORT_DATA"
  | "USE_COPILOT";

export const rolePermissions: Record<Role, ReadonlySet<Permission>> = {
  ADMIN: new Set(["VIEW_ORGANIZATION", "MANAGE_ORGANIZATION", "VIEW_MASTER_DATA", "MANAGE_MASTER_DATA", "VIEW_NOTIFICATIONS", "MANAGE_NOTIFICATIONS", "VIEW_ATTACHMENTS", "MANAGE_ATTACHMENTS", "MANAGE_USERS", "VIEW_LOGIN_HISTORY", "VIEW_AUDIT_LOGS", "VIEW_MAINTENANCE", "ASSET_READ", "ASSET_CREATE", "ASSET_UPDATE", "ASSET_ARCHIVE", "ASSET_HIERARCHY_MANAGE", "ASSET_CUSTOM_FIELDS_MANAGE", "CREATE_MAINTENANCE_NOTIFICATION", "REVIEW_MAINTENANCE_NOTIFICATION", "MANAGE_WORK_ORDERS", "EXECUTE_WORK_ORDERS", "VERIFY_WORK_ORDERS", "CLOSE_WORK_ORDERS", "MANAGE_DATA_SOURCES", "CREATE_DASHBOARD", "VIEW_DASHBOARD", "EXPORT_DATA", "USE_COPILOT"]),
  DATA_SOURCE_CREATOR: new Set(["VIEW_ORGANIZATION", "VIEW_MASTER_DATA", "VIEW_NOTIFICATIONS", "VIEW_ATTACHMENTS", "MANAGE_ATTACHMENTS", "VIEW_MAINTENANCE", "ASSET_READ", "ASSET_CREATE", "ASSET_UPDATE", "ASSET_HIERARCHY_MANAGE", "ASSET_CUSTOM_FIELDS_MANAGE", "CREATE_MAINTENANCE_NOTIFICATION", "REVIEW_MAINTENANCE_NOTIFICATION", "MANAGE_WORK_ORDERS", "EXECUTE_WORK_ORDERS", "VERIFY_WORK_ORDERS", "CLOSE_WORK_ORDERS", "MANAGE_DATA_SOURCES", "VIEW_DASHBOARD", "USE_COPILOT"]),
  DASHBOARD_CREATOR: new Set(["VIEW_ORGANIZATION", "VIEW_MASTER_DATA", "VIEW_NOTIFICATIONS", "VIEW_ATTACHMENTS", "VIEW_MAINTENANCE", "ASSET_READ", "CREATE_MAINTENANCE_NOTIFICATION", "MANAGE_WORK_ORDERS", "EXECUTE_WORK_ORDERS", "CREATE_DASHBOARD", "VIEW_DASHBOARD", "USE_COPILOT"]),
  VIEWER: new Set(["VIEW_ORGANIZATION", "VIEW_MASTER_DATA", "VIEW_NOTIFICATIONS", "VIEW_ATTACHMENTS", "VIEW_MAINTENANCE", "ASSET_READ", "CREATE_MAINTENANCE_NOTIFICATION", "VIEW_DASHBOARD", "USE_COPILOT"]),
};

export function hasPermission(role: Role, permission: Permission) {
  return rolePermissions[role].has(permission);
}
export const canManageUsers = (role: Role) => hasPermission(role, "MANAGE_USERS");
export const canManageDataSources = (role: Role) => hasPermission(role, "MANAGE_DATA_SOURCES");
export const canCreateDashboard = (role: Role) => hasPermission(role, "CREATE_DASHBOARD");
export const canViewAuditLogs = (role: Role) => hasPermission(role, "VIEW_AUDIT_LOGS");
export const canUseCopilot = (role: Role) => hasPermission(role, "USE_COPILOT");
export const canReviewMaintenance = (role: Role) => hasPermission(role, "REVIEW_MAINTENANCE_NOTIFICATION");
export const canExecuteWorkOrders = (role: Role) => hasPermission(role, "EXECUTE_WORK_ORDERS");
export const canVerifyWorkOrders = (role: Role) => hasPermission(role, "VERIFY_WORK_ORDERS");
export const canReadAssets = (role: Role) => hasPermission(role, "ASSET_READ");
