import type { Role } from "@/lib/db/schema";

export type Permission =
  | "VIEW_ORGANIZATION"
  | "MANAGE_ORGANIZATION"
  | "VIEW_MASTER_DATA"
  | "MANAGE_MASTER_DATA"
  | "VIEW_NOTIFICATIONS"
  | "MANAGE_NOTIFICATIONS"
  | "VIEW_ATTACHMENTS"
  | "MANAGE_ATTACHMENTS"
  | "MANAGE_USERS"
  | "VIEW_LOGIN_HISTORY"
  | "VIEW_AUDIT_LOGS"
  | "VIEW_MAINTENANCE"
  | "ASSET_READ"
  | "ASSET_CREATE"
  | "ASSET_UPDATE"
  | "ASSET_ARCHIVE"
  | "ASSET_HIERARCHY_MANAGE"
  | "ASSET_CUSTOM_FIELDS_MANAGE"
  | "CREATE_MAINTENANCE_NOTIFICATION"
  | "REVIEW_MAINTENANCE_NOTIFICATION"
  | "MANAGE_WORK_ORDERS"
  | "EXECUTE_WORK_ORDERS"
  | "VERIFY_WORK_ORDERS"
  | "CLOSE_WORK_ORDERS"
  | "NOTIFICATION_CREATE"
  | "NOTIFICATION_EDIT_OWN_DRAFT"
  | "NOTIFICATION_SUBMIT"
  | "NOTIFICATION_VIEW"
  | "NOTIFICATION_REVIEW"
  | "NOTIFICATION_REQUEST_INFORMATION"
  | "NOTIFICATION_REJECT"
  | "NOTIFICATION_APPROVE"
  | "NOTIFICATION_ACCEPT_WORK"
  | "NOTIFICATION_REJECT_WORK"
  | "NOTIFICATION_CLOSE"
  | "WORK_ORDER_CREATE"
  | "WORK_ORDER_VIEW"
  | "WORK_ORDER_ASSIGN"
  | "WORK_ORDER_REASSIGN"
  | "WORK_ORDER_ACCEPT_ASSIGNMENT"
  | "WORK_ORDER_START"
  | "WORK_ORDER_UPDATE_PROGRESS"
  | "WORK_ORDER_SUBMIT_COMPLETION"
  | "WORK_ORDER_REVIEW_COMPLETION"
  | "WORK_ORDER_APPROVE_COMPLETION"
  | "WORK_ORDER_RETURN_FOR_RECHECK"
  | "WORK_ORDER_CLOSE"
  | "WORK_ORDER_OVERRIDE_WARNING"
  | "AUDIT_VIEW"
  | "USER_MANAGE"
  | "ROLE_MANAGE"
  | "MANAGE_DATA_SOURCES"
  | "CREATE_DASHBOARD"
  | "VIEW_DASHBOARD"
  | "EXPORT_DATA"
  | "USE_COPILOT";

export const rolePermissions: Record<Role, ReadonlySet<Permission>> = {
  ADMIN: new Set(["VIEW_ORGANIZATION", "MANAGE_ORGANIZATION", "VIEW_MASTER_DATA", "MANAGE_MASTER_DATA", "VIEW_NOTIFICATIONS", "MANAGE_NOTIFICATIONS", "VIEW_ATTACHMENTS", "MANAGE_ATTACHMENTS", "MANAGE_USERS", "VIEW_LOGIN_HISTORY", "VIEW_AUDIT_LOGS", "VIEW_MAINTENANCE", "ASSET_READ", "ASSET_CREATE", "ASSET_UPDATE", "ASSET_ARCHIVE", "ASSET_HIERARCHY_MANAGE", "ASSET_CUSTOM_FIELDS_MANAGE", "CREATE_MAINTENANCE_NOTIFICATION", "REVIEW_MAINTENANCE_NOTIFICATION", "MANAGE_WORK_ORDERS", "EXECUTE_WORK_ORDERS", "VERIFY_WORK_ORDERS", "CLOSE_WORK_ORDERS", "MANAGE_DATA_SOURCES", "CREATE_DASHBOARD", "VIEW_DASHBOARD", "EXPORT_DATA", "USE_COPILOT", "NOTIFICATION_CREATE", "NOTIFICATION_EDIT_OWN_DRAFT", "NOTIFICATION_SUBMIT", "NOTIFICATION_VIEW", "NOTIFICATION_REVIEW", "NOTIFICATION_REQUEST_INFORMATION", "NOTIFICATION_REJECT", "NOTIFICATION_APPROVE", "NOTIFICATION_ACCEPT_WORK", "NOTIFICATION_REJECT_WORK", "NOTIFICATION_CLOSE", "WORK_ORDER_CREATE", "WORK_ORDER_VIEW", "WORK_ORDER_ASSIGN", "WORK_ORDER_REASSIGN", "WORK_ORDER_ACCEPT_ASSIGNMENT", "WORK_ORDER_START", "WORK_ORDER_UPDATE_PROGRESS", "WORK_ORDER_SUBMIT_COMPLETION", "WORK_ORDER_REVIEW_COMPLETION", "WORK_ORDER_APPROVE_COMPLETION", "WORK_ORDER_RETURN_FOR_RECHECK", "WORK_ORDER_CLOSE", "WORK_ORDER_OVERRIDE_WARNING", "AUDIT_VIEW", "USER_MANAGE", "ROLE_MANAGE"]),
  DATA_SOURCE_CREATOR: new Set(["VIEW_ORGANIZATION", "VIEW_MASTER_DATA", "VIEW_NOTIFICATIONS", "VIEW_ATTACHMENTS", "MANAGE_ATTACHMENTS", "VIEW_MAINTENANCE", "ASSET_READ", "ASSET_CREATE", "ASSET_UPDATE", "ASSET_HIERARCHY_MANAGE", "ASSET_CUSTOM_FIELDS_MANAGE", "CREATE_MAINTENANCE_NOTIFICATION", "REVIEW_MAINTENANCE_NOTIFICATION", "MANAGE_WORK_ORDERS", "EXECUTE_WORK_ORDERS", "VERIFY_WORK_ORDERS", "CLOSE_WORK_ORDERS", "MANAGE_DATA_SOURCES", "VIEW_DASHBOARD", "USE_COPILOT", "NOTIFICATION_CREATE", "NOTIFICATION_EDIT_OWN_DRAFT", "NOTIFICATION_SUBMIT", "NOTIFICATION_VIEW", "NOTIFICATION_REVIEW", "NOTIFICATION_REQUEST_INFORMATION", "NOTIFICATION_REJECT", "NOTIFICATION_APPROVE", "WORK_ORDER_CREATE", "WORK_ORDER_VIEW", "WORK_ORDER_ASSIGN", "WORK_ORDER_REASSIGN", "WORK_ORDER_UPDATE_PROGRESS", "WORK_ORDER_REVIEW_COMPLETION", "WORK_ORDER_APPROVE_COMPLETION", "WORK_ORDER_RETURN_FOR_RECHECK", "WORK_ORDER_CLOSE", "AUDIT_VIEW"]),
  DASHBOARD_CREATOR: new Set(["VIEW_ORGANIZATION", "VIEW_MASTER_DATA", "VIEW_NOTIFICATIONS", "VIEW_ATTACHMENTS", "VIEW_MAINTENANCE", "ASSET_READ", "CREATE_MAINTENANCE_NOTIFICATION", "MANAGE_WORK_ORDERS", "EXECUTE_WORK_ORDERS", "CREATE_DASHBOARD", "VIEW_DASHBOARD", "USE_COPILOT", "NOTIFICATION_VIEW", "WORK_ORDER_VIEW", "WORK_ORDER_ACCEPT_ASSIGNMENT", "WORK_ORDER_START", "WORK_ORDER_UPDATE_PROGRESS", "WORK_ORDER_SUBMIT_COMPLETION", "AUDIT_VIEW"]),
  VIEWER: new Set(["VIEW_ORGANIZATION", "VIEW_MASTER_DATA", "VIEW_NOTIFICATIONS", "VIEW_ATTACHMENTS", "VIEW_MAINTENANCE", "ASSET_READ", "CREATE_MAINTENANCE_NOTIFICATION", "VIEW_DASHBOARD", "USE_COPILOT", "NOTIFICATION_CREATE", "NOTIFICATION_EDIT_OWN_DRAFT", "NOTIFICATION_SUBMIT", "NOTIFICATION_VIEW", "NOTIFICATION_ACCEPT_WORK", "NOTIFICATION_REJECT_WORK", "NOTIFICATION_CLOSE", "WORK_ORDER_VIEW", "AUDIT_VIEW"]),
  OPERATOR: new Set(["VIEW_ORGANIZATION", "VIEW_MASTER_DATA", "VIEW_NOTIFICATIONS", "VIEW_ATTACHMENTS", "VIEW_MAINTENANCE", "ASSET_READ", "NOTIFICATION_CREATE", "NOTIFICATION_EDIT_OWN_DRAFT", "NOTIFICATION_SUBMIT", "NOTIFICATION_VIEW", "NOTIFICATION_ACCEPT_WORK", "NOTIFICATION_REJECT_WORK", "NOTIFICATION_CLOSE", "WORK_ORDER_VIEW", "AUDIT_VIEW"]),
  MAINTENANCE_MANAGER: new Set(["VIEW_ORGANIZATION", "VIEW_MASTER_DATA", "VIEW_NOTIFICATIONS", "VIEW_ATTACHMENTS", "MANAGE_ATTACHMENTS", "VIEW_MAINTENANCE", "ASSET_READ", "NOTIFICATION_CREATE", "NOTIFICATION_EDIT_OWN_DRAFT", "NOTIFICATION_SUBMIT", "NOTIFICATION_VIEW", "NOTIFICATION_REVIEW", "NOTIFICATION_REQUEST_INFORMATION", "NOTIFICATION_REJECT", "NOTIFICATION_APPROVE", "WORK_ORDER_CREATE", "WORK_ORDER_VIEW", "WORK_ORDER_ASSIGN", "WORK_ORDER_REASSIGN", "WORK_ORDER_UPDATE_PROGRESS", "WORK_ORDER_REVIEW_COMPLETION", "WORK_ORDER_APPROVE_COMPLETION", "WORK_ORDER_RETURN_FOR_RECHECK", "WORK_ORDER_CLOSE", "AUDIT_VIEW"]),
  TECHNICIAN: new Set(["VIEW_ORGANIZATION", "VIEW_MASTER_DATA", "VIEW_NOTIFICATIONS", "VIEW_ATTACHMENTS", "MANAGE_ATTACHMENTS", "VIEW_MAINTENANCE", "ASSET_READ", "NOTIFICATION_VIEW", "WORK_ORDER_VIEW", "WORK_ORDER_ACCEPT_ASSIGNMENT", "WORK_ORDER_START", "WORK_ORDER_UPDATE_PROGRESS", "WORK_ORDER_SUBMIT_COMPLETION", "AUDIT_VIEW"]),
};

export function hasPermission(role: Role, permission: Permission) {
  return rolePermissions[role].has(permission);
}
export const canManageUsers = (role: Role) => hasPermission(role, "MANAGE_USERS");
export const canManageDataSources = (role: Role) => hasPermission(role, "MANAGE_DATA_SOURCES");
export const canCreateDashboard = (role: Role) => hasPermission(role, "CREATE_DASHBOARD");
export const canViewAuditLogs = (role: Role) => hasPermission(role, "VIEW_AUDIT_LOGS");
export const canUseCopilot = (role: Role) => hasPermission(role, "USE_COPILOT");
export const canReviewMaintenance = (role: Role) => hasPermission(role, "REVIEW_MAINTENANCE_NOTIFICATION");
export const canExecuteWorkOrders = (role: Role) => hasPermission(role, "EXECUTE_WORK_ORDERS");
export const canVerifyWorkOrders = (role: Role) => hasPermission(role, "VERIFY_WORK_ORDERS");
export const canReadAssets = (role: Role) => hasPermission(role, "ASSET_READ");
