"use client";
import Link from "next/link";
import { ChevronRight, Home } from "lucide-react";
import { usePathname } from "next/navigation";

const names: Record<string, string> = { dashboard: "Dashboard", admin: "Administration", users: "Users & Access", "audit-logs": "Audit Log", "login-history": "Login History", organization: "Organization", settings: "Settings", "master-data": "Master Data", notifications: "แจ้งซ่อม", inbox: "My Inbox", profile: "Profile", security: "Security", maintenance: "Maintenance", assets: "Assets", "work-orders": "Work Orders", approvals: "Approval Center", inventory: "Inventory", items: "Stock Items", locations: "Locations", vendors: "Vendors", "on-hand": "Stock On-hand", transactions: "Documents", requests: "Requests", "po-receipts": "PO Receipts", counts: "Stock Count", movement: "Stock Movement", "stock-card": "Stock Card", configuration: "Configuration", new: "New", edit: "Edit" };
export function Breadcrumbs() {
  const segments = usePathname().split("/").filter(Boolean);
  return <nav aria-label="Breadcrumb" className="flex min-w-0 items-center gap-1 text-sm text-slate-500"><Link href="/dashboard" className="inline-flex min-h-10 items-center gap-2 rounded-md px-1 hover:text-slate-950 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-600"><Home className="size-4" /><span className="sr-only xl:not-sr-only">Dashboard</span></Link>{segments.filter((segment) => segment !== "dashboard").map((segment, index, visible) => { const originalIndex = segments.indexOf(segment); const href = `/${segments.slice(0, originalIndex + 1).join("/")}`; const current = index === visible.length - 1; const isIdentifier = /^[0-9a-f]{8}-/i.test(segment); return <span key={`${href}-${index}`} className="flex min-w-0 items-center gap-1"><ChevronRight className="size-4 shrink-0" /><Link href={href} aria-current={current ? "page" : undefined} className={current ? "max-w-52 truncate font-semibold text-slate-950" : "max-w-40 truncate hover:text-slate-950"}>{isIdentifier ? "Details" : names[segment] || decodeURIComponent(segment)}</Link></span>; })}</nav>;
}
