"use client";
import Link from "next/link";
import { ChevronRight, Home } from "lucide-react";
import { usePathname } from "next/navigation";

const names: Record<string, string> = { dashboard: "ภาพรวมงาน", admin: "ดูแลระบบ", users: "ผู้ใช้และสิทธิ์", "audit-logs": "ประวัติการเปลี่ยนแปลง", "login-history": "Login History", organization: "โครงสร้างองค์กร", settings: "Settings", "master-data": "ข้อมูลหลัก", notifications: "แจ้งซ่อม", inbox: "กล่องข้อความ", profile: "Profile", security: "Security", maintenance: "งานซ่อม", assets: "ทรัพย์สิน", "work-orders": "ใบสั่งงานซ่อม", approvals: "ศูนย์อนุมัติ", inventory: "คลัง", items: "สินค้าและอะไหล่", locations: "สถานที่จัดเก็บ", vendors: "ผู้ขาย", "on-hand": "ยอดคงเหลือ", transactions: "เอกสารคลัง", requests: "คำขอเบิก", "po-receipts": "รับของจาก PO", counts: "ตรวจนับสต็อก", movement: "ความเคลื่อนไหวสต็อก", "stock-card": "บัตรสต็อก", configuration: "Configuration", "purchase-requests": "ใบขอซื้อ (PR)", "purchase-orders": "ใบสั่งซื้อ (PO)", "approval-workflows": "สายอนุมัติ", new: "สร้างใหม่", edit: "แก้ไข" };
export function Breadcrumbs() {
  const segments = usePathname().split("/").filter(Boolean);
  return <nav aria-label="Breadcrumb" className="flex min-w-0 items-center gap-1 text-sm text-slate-500"><Link href="/dashboard" className="inline-flex min-h-10 items-center gap-2 rounded-md px-1 hover:text-slate-950 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-600"><Home className="size-4" /><span className="sr-only xl:not-sr-only">ภาพรวมงาน</span></Link>{segments.filter((segment) => segment !== "dashboard").map((segment, index, visible) => { const originalIndex = segments.indexOf(segment); const href = `/${segments.slice(0, originalIndex + 1).join("/")}`; const current = index === visible.length - 1; const isIdentifier = /^[0-9a-f]{8}-/i.test(segment); return <span key={`${href}-${index}`} className="flex min-w-0 items-center gap-1"><ChevronRight className="size-4 shrink-0" /><Link href={href} aria-current={current ? "page" : undefined} className={current ? "max-w-52 truncate font-semibold text-slate-950" : "max-w-40 truncate hover:text-slate-950"}>{isIdentifier ? "รายละเอียด" : names[segment] || decodeURIComponent(segment)}</Link></span>; })}</nav>;
}
